// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0074:Use compound assignment", Justification = "<Pending>", Scope = "member", Target = "~P:JBToolkit.ColorHelper.ColourHelper.IntensityValue.ChildA")]
[assembly: SuppressMessage("Style", "IDE0074:Use compound assignment", Justification = "<Pending>", Scope = "member", Target = "~P:JBToolkit.ColorHelper.ColourHelper.IntensityValue.ChildB")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.ClickTracking.clickTrackingParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.browserName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.browserVersion")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.clientName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.clientVersion")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.experimentIds")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.experimentsToken")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.gl")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.hl")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.locationInfo")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.musicAppInfo")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.osName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.osVersion")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Client.utcOffsetMinutes")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.context")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Context.activePlayers")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Context.capabilities")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Context.clickTracking")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Context.client")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Context.request")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Context.user")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.InternalExperimentFlag.key")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.InternalExperimentFlag.value")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.LocationInfo.locationPermissionAuthorizationStatus")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.MusicAppInfo.musicActivityMasterSwitch")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.MusicAppInfo.musicLocationMasterSwitch")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.MusicAppInfo.pwaInstallabilityStatus")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.parameters")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.query")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Request.internalExperimentFlags")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.Request.sessionIndex")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchContext.User.enableSafetyMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Content.sectionListRenderer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Content2.itemSectionRenderer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Content3.messageRenderer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.contents")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Contents.tabbedSearchResultsRenderer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Endpoint.clickTrackingParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Endpoint.searchEndpoint")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Icon.iconType")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.ItemSectionRenderer.contents")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.ItemSectionRenderer.trackingParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.MessageRenderer.icon")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.MessageRenderer.text")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.MessageRenderer.trackingParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Param.key")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Param.value")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.responseContext")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.ResponseContext.serviceTrackingParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.ResponseContext.visitorData")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Run.text")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.SearchEndpoint.paramaters")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.SearchEndpoint.query")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.SectionListRenderer.contents")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.SectionListRenderer.trackingParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.ServiceTrackingParam.paramaters")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.ServiceTrackingParam.service")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Tab.tabRenderer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.TabbedSearchResultsRenderer.tabs")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.TabRenderer.content")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.TabRenderer.endpoint")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.TabRenderer.selected")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.TabRenderer.title")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.TabRenderer.trackingParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.Text.runs")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:YTMusicUploader.Providers.RequestModels.SearchResult.trackingParams")]
