.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/obj/x86/Release/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/obj/x86/Release/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
