.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/CustomControls/AntiAliasedLabel.cs" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/CustomControls/AntiAliasedLabel.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.AntiAliasedLabel\fP"
.br
.RI "Adds better anti-aliasing to a label for better visuals Warning: Can look fuzzy when used in certain places "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.WinForms\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
