.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/BrowseArtistsResultsContext.cs" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/BrowseArtistsResultsContext.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Responsecontext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Servicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Param\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Contents\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Singlecolumnbrowseresultsrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Tab\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Tabrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Content\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Sectionlistrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Content1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musiccarouselshelfrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Header\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musiccarouselshelfbasicheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Title\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitydata1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Endicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Iconlinkrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Icon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Tooltip\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Backgroundoverlay\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Verticalgradient\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Content2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Thumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Thumbnail\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Thumbnail1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Title1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Subtitle\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpoint3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpointmusicsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpointmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Menu\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Menurenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibility\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitydata2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Item\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Menunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Text\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Icon1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Addtoplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Shareentityendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpointmusicsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpointmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpoint4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextsupportedconfigs3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextmusicconfig3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Menuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Text1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Icon2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Serviceendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Queueaddendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Queuetarget\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Command\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Addtotoastaction\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Item1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Notificationtextrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Successresponsetext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Togglemenuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Defaulttext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Defaulticon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Defaultserviceendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Likeendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Target\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Toggledtext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run8\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Toggledicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Toggledserviceendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Likeendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Target1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitydata3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitydata4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Thumbnailoverlay\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicitemthumbnailoverlayrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Background\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Verticalgradient1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Content3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicplaybuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Playnavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchplaylistendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpointmusicsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpointmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Playicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Pauseicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Playingicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilityplaydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitydata5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitypausedata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitydata6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Itemsectionrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Header1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Itemsectiontabbedheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Tab1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Itemsectiontabrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Title2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run9\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Endpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpoint5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Enditem\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Dropdownrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Entry\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Dropdownitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Label\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run10\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Onselectcommand\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpoint6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Content4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicshelfrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Shelfdivider\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicshelfdividerrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Content5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Thumbnail2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicthumbnailrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Thumbnail3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Thumbnail4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Menu1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Menurenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibility1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Accessibilitydata7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Item2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Menunavigationitemrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Text2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run11\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Icon3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchplaylistendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpoint7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextsupportedconfigs4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Browseendpointcontextmusicconfig4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Flexcolumn\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemflexcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Text3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Run12\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Continuation\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Nextcontinuationdata\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.RequestModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
