.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/BrowseArtistsResultsContinuationContext.cs" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/BrowseArtistsResultsContinuationContext.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Responsecontext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Servicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Param\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Continuationcontents\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicshelfcontinuation\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Shelfdivider\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicshelfdividerrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Content\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicresponsivelistitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Thumbnail\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Thumbnail1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Thumbnail2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Menu\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Menurenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Accessibility\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Accessibilitydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Item\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Menunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Text\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Run\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Icon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Navigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Watchplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Navigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Browseendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Browseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Browseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Flexcolumn\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicresponsivelistitemflexcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Text1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Run1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Continuation\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Nextcontinuationdata\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.RequestModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
