.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/BrowsePlaylistsResultsContext.cs" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/BrowsePlaylistsResultsContext.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Responsecontext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Servicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Param\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Contents\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Singlecolumnbrowseresultsrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Tab\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Tabrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Content\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Sectionlistrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Content1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musiccarouselshelfrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Header\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musiccarouselshelfbasicheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Title\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitydata1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Endicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Iconlinkrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Icon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Tooltip\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Backgroundoverlay\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Verticalgradient\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Content2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Thumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Thumbnail\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Thumbnail1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Title1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Subtitle\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpointmusicsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpointmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menu\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menurenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibility\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitydata2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Item\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Text\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Icon1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Addtoplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Shareentityendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpointmusicsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpointmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextsupportedconfigs3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextmusicconfig3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Text1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Icon2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Serviceendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Queueaddendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Queuetarget\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Command\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Addtotoastaction\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Item1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Notificationtextrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Successresponsetext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Togglemenuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Defaulttext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Defaulticon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Defaultserviceendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Likeendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Target\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Action\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musiclibrarystatusupdatecommand\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Feedbackendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Toggledtext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run8\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Toggledicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Toggledserviceendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Likeendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Target1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Feedbackendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Thumbnailoverlay\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musicitemthumbnailoverlayrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Background\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Verticalgradient1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Content3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musicplaybuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Playnavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchplaylistendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpointmusicsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchendpointmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Playicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Pauseicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Playingicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilityplaydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitydata3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitypausedata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitydata4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Itemsectionrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Header1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Itemsectiontabbedheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Tab1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Itemsectiontabrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Title2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run9\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Endpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Enditem\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Dropdownrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Entry\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Dropdownitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Label\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run10\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Onselectcommand\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Content4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Gridrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Item2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Thumbnailrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musicthumbnailrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Thumbnail2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Thumbnail3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Title3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run11\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Createplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextsupportedconfigs4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextmusicconfig4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Createplaylistendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint8\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextsupportedconfigs5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextmusicconfig5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Subtitle1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run12\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpoint9\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextsupportedconfigs6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Browseendpointcontextmusicconfig6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menu1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menurenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibility1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitydata5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Item3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menunavigationitemrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Text2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run13\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Icon3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Navigationendpoint8\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchplaylistendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Playlisteditorendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Addtoplaylistendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Shareentityendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Confirmdialogendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Content5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Confirmdialogrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Title4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run14\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Confirmbutton\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Buttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Text3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run15\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Serviceendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Deleteplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Cancelbutton\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Buttonrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Text4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run16\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Dialogmessage\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run17\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menuserviceitemrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Text5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run18\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Icon4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Serviceendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Queueaddendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Queuetarget1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Command1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Addtotoastaction1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Item4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Notificationtextrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Successresponsetext1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Run19\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Thumbnailoverlay1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musicitemthumbnailoverlayrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Background1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Verticalgradient2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Content6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musicplaybuttonrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Playnavigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Watchplaylistendpoint3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Playicon1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Pauseicon1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Playingicon1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilityplaydata1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitydata6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitypausedata1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Accessibilitydata7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Continuation\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Nextcontinuationdata\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.RequestModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
