.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Helpers/ColourHelper.cs" 3 "Sun Nov 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Helpers/ColourHelper.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.ColourHelper\fP"
.br
.RI "Methods to convert RGB to hex, hex to RGB, alter colour brightness, lightness, intensity, also generate random 'nice' colours\&. "
.ti -1c
.RI "class \fBJBToolkit\&.ColourHelper\&.ColourGenerator\fP"
.br
.RI "Generates random colours close to primary colours as hex string and doesn't repeat a colour "
.ti -1c
.RI "class \fBJBToolkit\&.ColourHelper\&.PatternGenerator\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ColourHelper\&.IntensityGenerator\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ColourHelper\&.IntensityValue\fP"
.br
.ti -1c
.RI "class \fBJBToolkit\&.ColourHelper\&.IntensityValueWalker\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
