.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/CreatePlaylistRequestContext.cs" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/CreatePlaylistRequestContext.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\fP"
.br
.RI "Deserialised HttpWebRequest request body sent for creating a playlist "
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Context\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Locationinfo\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Musicappinfo\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Capabilities\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Request\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Internalexperimentflag\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Activeplayers\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.User\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.RequestModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
