.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/DataModels Directory Reference" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/DataModels Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_DbModels\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDbModel\&.cs\fP"
.br
.ti -1c
.RI "file \fBMusicFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettings\&.cs\fP"
.br
.ti -1c
.RI "file \fBWatchFolder\&.cs\fP"
.br
.in -1c
