.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader Directory Reference" 3 "Wed Aug 26 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBusiness\fP"
.br
.ti -1c
.RI "directory \fBCustomControls\fP"
.br
.ti -1c
.RI "directory \fBDialogues\fP"
.br
.ti -1c
.RI "directory \fBHelpers\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.ti -1c
.RI "directory \fBProviders\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGlobal\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalSuppressions\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.Delegates\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.Events\&.Buttons\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.Events\&.Checkboxes\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.Events\&.FileSystemWatcher\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.Events\&.Menu\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.Events\&.TextBoxes\&.cs\fP"
.br
.ti -1c
.RI "file \fBProgram\&.cs\fP"
.br
.in -1c
