.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers Directory Reference" 3 "Sun Aug 23 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBModels\fP"
.br
.ti -1c
.RI "directory \fBRepos\fP"
.br
.ti -1c
.RI "directory \fBRequests\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDataAccess\&.cs\fP"
.br
.ti -1c
.RI "file \fBRequests\&.cs\fP"
.br
.in -1c
