.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Services Directory Reference" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Services Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArtistService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIArtistService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIRecordingService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIReleaseGroupService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIReleaseService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIWorkService\&.cs\fP"
.br
.ti -1c
.RI "file \fBRecordingService\&.cs\fP"
.br
.ti -1c
.RI "file \fBReleaseGroupService\&.cs\fP"
.br
.ti -1c
.RI "file \fBReleaseService\&.cs\fP"
.br
.ti -1c
.RI "file \fBWorkService\&.cs\fP"
.br
.in -1c
