.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz Directory Reference" 3 "Wed Aug 26 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCache\fP"
.br
.ti -1c
.RI "directory \fBEntities\fP"
.br
.ti -1c
.RI "directory \fBResources\fP"
.br
.ti -1c
.RI "directory \fBServices\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMusicBrainzClient\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryParameters\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryResult\&.cs\fP"
.br
.ti -1c
.RI "file \fBUrlBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBWebServiceException\&.cs\fP"
.br
.in -1c
