.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities Directory Reference" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCollections\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArea\&.cs\fP"
.br
.ti -1c
.RI "file \fBArtist\&.cs\fP"
.br
.ti -1c
.RI "file \fBCoverArtArchive\&.cs\fP"
.br
.ti -1c
.RI "file \fBDisc\&.cs\fP"
.br
.ti -1c
.RI "file \fBLabel\&.cs\fP"
.br
.ti -1c
.RI "file \fBLabelInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBLifeSpan\&.cs\fP"
.br
.ti -1c
.RI "file \fBMedium\&.cs\fP"
.br
.ti -1c
.RI "file \fBNameCredit\&.cs\fP"
.br
.ti -1c
.RI "file \fBRating\&.cs\fP"
.br
.ti -1c
.RI "file \fBRecording\&.cs\fP"
.br
.ti -1c
.RI "file \fBRelation\&.cs\fP"
.br
.ti -1c
.RI "file \fBRelease\&.cs\fP"
.br
.ti -1c
.RI "file \fBReleaseGroup\&.cs\fP"
.br
.ti -1c
.RI "file \fBTag\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextRepresentation\&.cs\fP"
.br
.ti -1c
.RI "file \fBTrack\&.cs\fP"
.br
.ti -1c
.RI "file \fBUrl\&.cs\fP"
.br
.ti -1c
.RI "file \fBWork\&.cs\fP"
.br
.in -1c
