.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/bin/Release/84.0.522.63 Directory Reference" 3 "Sun Aug 23 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/bin/Release/84.0.522.63 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBMLModels\fP"
.br
.in -1c
