.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Dialogues Directory Reference" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Dialogues Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConnectToYTMusic\&.cs\fP"
.br
.ti -1c
.RI "file \fBConnectToYTMusic\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBIssueLog\&.cs\fP"
.br
.ti -1c
.RI "file \fBIssueLog\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBUploadLog\&.cs\fP"
.br
.ti -1c
.RI "file \fBUploadLog\&.Designer\&.cs\fP"
.br
.in -1c
