.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels Directory Reference" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArtistCache\&.cs\fP"
.br
.ti -1c
.RI "file \fBBrowseArtistRequestContext\&.cs\fP"
.br
.ti -1c
.RI "file \fBBrowseArtistResultsContext\&.cs\fP"
.br
.ti -1c
.RI "file \fBBrowseArtistResultsContinuationContext\&.cs\fP"
.br
.ti -1c
.RI "file \fBBrowseArtistsResultsContext\&.cs\fP"
.br
.ti -1c
.RI "file \fBBrowseArtistsResultsContinuationContext\&.cs\fP"
.br
.ti -1c
.RI "file \fBIRequestModel\&.cs\fP"
.br
.ti -1c
.RI "file \fBSearchContext\&.cs\fP"
.br
.ti -1c
.RI "file \fBSearchResultsContext\&.cs\fP"
.br
.in -1c
