.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/Collections Directory Reference" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/Collections Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArtistList\&.cs\fP"
.br
.ti -1c
.RI "file \fBRecordingList\&.cs\fP"
.br
.ti -1c
.RI "file \fBReleaseGroupList\&.cs\fP"
.br
.ti -1c
.RI "file \fBReleaseList\&.cs\fP"
.br
.in -1c
