.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/CustomControls Directory Reference" 3 "Sun Aug 23 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/CustomControls Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBGraphics\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAntiAliasedLabel\&.cs\fP"
.br
.ti -1c
.RI "file \fBFastScrollDataGridView\&.cs\fP"
.br
.ti -1c
.RI "file \fBOptimisedMetroForm\&.cs\fP"
.br
.ti -1c
.RI "file \fBRoundButton\&.cs\fP"
.br
.ti -1c
.RI "file \fBRoundTextBox\&.cs\fP"
.br
.in -1c
