.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Business/Pipes Directory Reference" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Business/Pipes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIIpcContracts\&.cs\fP"
.br
.ti -1c
.RI "file \fBWcfClient\&.cs\fP"
.br
.ti -1c
.RI "file \fBWcfServer\&.cs\fP"
.br
.in -1c
