.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/obj/x64/Release Directory Reference" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/obj/x64/Release Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETFramework,Version=v4\&.7\&.2\&.AssemblyAttributes\&.cs\fP"
.br
.in -1c
