.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Requests/Playlists Directory Reference" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Requests/Playlists Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAddPlaylistItems\&.cs\fP"
.br
.ti -1c
.RI "file \fBCreatePlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBDeletePlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBGetPlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBGetPlaylists\&.cs\fP"
.br
.ti -1c
.RI "file \fBRemovePlaylistItems\&.cs\fP"
.br
.in -1c
