.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Playlist/Models Directory Reference" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Playlist/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBasePlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBBasePlaylistEntry\&.cs\fP"
.br
.ti -1c
.RI "file \fBHlsPlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBHlsPlaylistEntry\&.cs\fP"
.br
.ti -1c
.RI "file \fBM3uPlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBM3UPlaylistEntry\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlsPlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlsPlaylistEntry\&.cs\fP"
.br
.ti -1c
.RI "file \fBWplPlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBWplPlaylistEntry\&.cs\fP"
.br
.ti -1c
.RI "file \fBZplPlaylist\&.cs\fP"
.br
.ti -1c
.RI "file \fBZplPlaylistEntry\&.cs\fP"
.br
.in -1c
