.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Requests Directory Reference" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Requests Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBPlaylists\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCheckAuthorisation\&.cs\fP"
.br
.ti -1c
.RI "file \fBCheckUploaded\&.cs\fP"
.br
.ti -1c
.RI "file \fBDeleteFromYTMusic\&.cs\fP"
.br
.ti -1c
.RI "file \fBGetArtists\&.cs\fP"
.br
.ti -1c
.RI "file \fBGetArtistSongs\&.cs\fP"
.br
.ti -1c
.RI "file \fBUploadTrack\&.cs\fP"
.br
.in -1c
