.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Resources Directory Reference" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Resources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConstants\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBMessages\&.Designer\&.cs\fP"
.br
.in -1c
