.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/DataAccess.cs" 3 "Wed Aug 26 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/DataAccess.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.DataAccess\fP"
.br
.RI "Abastract database repository access class\&. "
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.DbOperationResult\fP"
.br
.RI "Database process execution and query result object\&. Contains if there's any errors and the time taken to perform the database operation\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
