.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/DeleteFromYTMusicRequestContext.cs" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/DeleteFromYTMusicRequestContext.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\fP"
.br
.RI "Deserialised HttpWebRequest request body sent for a YouTube Music entity deletion "
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Context\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Client\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Locationinfo\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Musicappinfo\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Capabilities\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Request\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Internalexperimentflag\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Clicktracking\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.Activeplayers\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.DeleteFromYTMusicRequestContext\&.User\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.RequestModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
