.TH "EventArgs" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Business\&.Pipes\&.DataReceivedEventArgs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
