.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Helpers/FastFileSearcher.cs" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Helpers/FastFileSearcher.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.FileData\fP"
.br
.RI "Contains information about a file returned by the FastDirectoryEnumerator class\&. 
.br
 "
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.WIN32_FIND_DATA\fP"
.br
.RI "Contains information about the file that is found by the FindFirstFile or FindNextFile functions\&. "
.ti -1c
.RI "class \fBJBToolkit\&.Windows\&.FastDirectoryEnumerator\fP"
.br
.RI "A fast enumerator of files in a directory\&. Use this if you need to get attributes for all files in a directory\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Windows\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
