.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Business/FileUploader.cs" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Business/FileUploader.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Business\&.FileUploader\fP"
.br
.RI "Responsive for managing uploading music files to YouTube Music\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Business\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
