.TH "IDisposable" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDisposable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.StreamHelpers\&.SafeFileStream\fP, \fBYTMusicUploader\&.Business\&.Pipes\&.IIpcServer\fP, and \fBYTMusicUploader\&.MusicBrainz\&.API\&.MusicBrainzClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
