.TH "IEnumerable" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEnumerable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.MusicBrainz\&.API\&.QueryParameters< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
