.TH "IEqualityComparer" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEqualityComparer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.FileDataComparer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
