.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Business/Pipes/IIpcContracts.cs" 3 "Mon Aug 24 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Business/Pipes/IIpcContracts.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBYTMusicUploader\&.Business\&.Pipes\&.IIpcClient\fP"
.br
.ti -1c
.RI "interface \fBYTMusicUploader\&.Business\&.Pipes\&.IIpcServer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Business\&.Pipes\&.DataReceivedEventArgs\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Business\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Business\&.Pipes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
