.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Helpers/ImageHelper.cs" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Helpers/ImageHelper.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.Imaging\&.ImageHelper\fP"
.br
.RI "Image helper methods "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.Imaging\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
