.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Helpers/InstalledApplicationHelper.cs" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Helpers/InstalledApplicationHelper.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Helpers\&.InstalledApplicationHelper\fP"
.br
.RI "Checks if the YT Music Uploader application is installed and if so what version (used for auto update) "
.ti -1c
.RI "class \fBYTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\fP"
.br
.RI "Checks if the YT Music Uploader application is installed and if so what version (used for auto update) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Helpers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
