.TH "IRequestCache" 3 "Tue Aug 25 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRequestCache
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Business\&.MusicBrainz\&.FileRequestCache\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
