.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Services/IWorkService.cs" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Services/IWorkService.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBYTMusicUploader\&.MusicBrainz\&.API\&.Services\&.IWorkService\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\&.Services\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
