.TH "JBToolkit.ColourHelper.ColourGenerator" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ColourHelper.ColourGenerator \- Generates random colours close to primary colours as hex string and doesn't repeat a colour  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBNextColour\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Color \fBGetRandomColour\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates random colours close to primary colours as hex string and doesn't repeat a colour 


.SH "Member Function Documentation"
.PP 
.SS "static Color JBToolkit\&.ColourHelper\&.ColourGenerator\&.GetRandomColour ()\fC [static]\fP"

.SS "string JBToolkit\&.ColourHelper\&.ColourGenerator\&.NextColour ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
