.TH "JBToolkit.WinForms.AntiAliasedLabel" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.AntiAliasedLabel \- Adds better anti-aliasing to a label for better visuals Warning: Can look fuzzy when used in certain places  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLabel\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPaint\fP (PaintEventArgs e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adds better anti-aliasing to a label for better visuals Warning: Can look fuzzy when used in certain places 


.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.AntiAliasedLabel\&.OnPaint (PaintEventArgs e)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
