.TH "JBToolkit.WinForms.RoundTextBox" 3 "Tue Aug 25 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.RoundTextBox \- Nicer looking 'round' edge text box  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoundTextBox\fP ()"
.br
.ti -1c
.RI "void \fBSelectAll\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TextBox \fBbox\fP = new TextBox()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnTextChanged\fP (\fBEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBOnFontChanged\fP (\fBEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBOnForeColorChanged\fP (\fBEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBOnPaint\fP (PaintEventArgs e)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Color \fBBr\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override Color \fBBackColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "HorizontalAlignment \fBTextAlign\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBReadOnly\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "char \fBPasswordChar\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nicer looking 'round' edge text box 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.RoundTextBox\&.RoundTextBox ()"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.RoundTextBox\&.OnFontChanged (\fBEventArgs\fP e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundTextBox\&.OnForeColorChanged (\fBEventArgs\fP e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundTextBox\&.OnPaint (PaintEventArgs e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundTextBox\&.OnTextChanged (\fBEventArgs\fP e)\fC [protected]\fP"

.SS "void JBToolkit\&.WinForms\&.RoundTextBox\&.SelectAll ()"

.SH "Member Data Documentation"
.PP 
.SS "TextBox JBToolkit\&.WinForms\&.RoundTextBox\&.box = new TextBox()"

.SH "Property Documentation"
.PP 
.SS "override Color JBToolkit\&.WinForms\&.RoundTextBox\&.BackColor\fC [get]\fP, \fC [set]\fP"

.SS "Color JBToolkit\&.WinForms\&.RoundTextBox\&.Br\fC [get]\fP, \fC [set]\fP"

.SS "char JBToolkit\&.WinForms\&.RoundTextBox\&.PasswordChar\fC [get]\fP, \fC [set]\fP"

.SS "bool JBToolkit\&.WinForms\&.RoundTextBox\&.ReadOnly\fC [get]\fP, \fC [set]\fP"

.SS "HorizontalAlignment JBToolkit\&.WinForms\&.RoundTextBox\&.TextAlign\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
