.TH "JBToolkit.WinForms.RoundButton" 3 "Mon Aug 24 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.RoundButton \- Nicer looking 'round' edge button  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBControl\fP, and \fBIButtonControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoundButton\fP ()"
.br
.ti -1c
.RI "void \fBNotifyDefault\fP (bool value)"
.br
.ti -1c
.RI "void \fBPerformClick\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPaint\fP (PaintEventArgs e)"
.br
.ti -1c
.RI "override void \fBOnMouseDoubleClick\fP (MouseEventArgs e)"
.br
.ti -1c
.RI "override void \fBOnEnabledChanged\fP (\fBEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBOnResize\fP (\fBEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBOnMouseEnter\fP (\fBEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBOnMouseLeave\fP (\fBEventArgs\fP e)"
.br
.ti -1c
.RI "override void \fBOnMouseDown\fP (MouseEventArgs e)"
.br
.ti -1c
.RI "override void \fBOnMouseUp\fP (MouseEventArgs e)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBStroke\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Color \fBStrokeColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBRadius\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Color \fBInactive1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Color \fBInactive2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Color \fBActive1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Color \fBActive2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBTransparency\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override string \fBText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override \fBImage\fP \fBBackgroundImage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Image \fBImage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override Color \fBForeColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DialogResult \fBDialogResult\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nicer looking 'round' edge button 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.RoundButton\&.RoundButton ()"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.WinForms\&.RoundButton\&.NotifyDefault (bool value)"

.SS "override void JBToolkit\&.WinForms\&.RoundButton\&.OnEnabledChanged (\fBEventArgs\fP e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundButton\&.OnMouseDoubleClick (MouseEventArgs e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundButton\&.OnMouseDown (MouseEventArgs e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundButton\&.OnMouseEnter (\fBEventArgs\fP e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundButton\&.OnMouseLeave (\fBEventArgs\fP e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundButton\&.OnMouseUp (MouseEventArgs e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundButton\&.OnPaint (PaintEventArgs e)\fC [protected]\fP"

.SS "override void JBToolkit\&.WinForms\&.RoundButton\&.OnResize (\fBEventArgs\fP e)\fC [protected]\fP"

.SS "void JBToolkit\&.WinForms\&.RoundButton\&.PerformClick ()"

.SH "Property Documentation"
.PP 
.SS "Color JBToolkit\&.WinForms\&.RoundButton\&.Active1\fC [get]\fP, \fC [set]\fP"

.SS "Color JBToolkit\&.WinForms\&.RoundButton\&.Active2\fC [get]\fP, \fC [set]\fP"

.SS "override \fBImage\fP JBToolkit\&.WinForms\&.RoundButton\&.BackgroundImage\fC [get]\fP, \fC [set]\fP"

.SS "DialogResult JBToolkit\&.WinForms\&.RoundButton\&.DialogResult\fC [get]\fP, \fC [set]\fP"

.SS "override Color JBToolkit\&.WinForms\&.RoundButton\&.ForeColor\fC [get]\fP, \fC [set]\fP"

.SS "Image JBToolkit\&.WinForms\&.RoundButton\&.Image\fC [get]\fP, \fC [set]\fP"

.SS "Color JBToolkit\&.WinForms\&.RoundButton\&.Inactive1\fC [get]\fP, \fC [set]\fP"

.SS "Color JBToolkit\&.WinForms\&.RoundButton\&.Inactive2\fC [get]\fP, \fC [set]\fP"

.SS "int JBToolkit\&.WinForms\&.RoundButton\&.Radius\fC [get]\fP, \fC [set]\fP"

.SS "bool JBToolkit\&.WinForms\&.RoundButton\&.Stroke\fC [get]\fP, \fC [set]\fP"

.SS "Color JBToolkit\&.WinForms\&.RoundButton\&.StrokeColor\fC [get]\fP, \fC [set]\fP"

.SS "override string JBToolkit\&.WinForms\&.RoundButton\&.Text\fC [get]\fP, \fC [set]\fP"

.SS "bool JBToolkit\&.WinForms\&.RoundButton\&.Transparency\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
