.TH "JBTookit.Network" 3 "Sat Aug 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBTookit.Network
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNetworkHelper\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
