.TH "JBToolkit.WinForms.AbstractControlDescriptionProvider< TAbstract, TBase >" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.AbstractControlDescriptionProvider< TAbstract, TBase >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTypeDescriptionProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractControlDescriptionProvider\fP ()"
.br
.ti -1c
.RI "override Type \fBGetReflectionType\fP (Type objectType, object instance)"
.br
.ti -1c
.RI "override object \fBCreateInstance\fP (IServiceProvider provider, Type objectType, Type[] argTypes, object[] args)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBJBToolkit\&.WinForms\&.AbstractControlDescriptionProvider\fP< TAbstract, TBase >\&.\fBAbstractControlDescriptionProvider\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "override object \fBJBToolkit\&.WinForms\&.AbstractControlDescriptionProvider\fP< TAbstract, TBase >\&.CreateInstance (IServiceProvider provider, Type objectType, Type[] argTypes, object[] args)"

.SS "override Type \fBJBToolkit\&.WinForms\&.AbstractControlDescriptionProvider\fP< TAbstract, TBase >\&.GetReflectionType (Type objectType, object instance)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
