.TH "JBToolkit.ColorHelper.ColourHelper.PatternGenerator" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ColorHelper.ColourHelper.PatternGenerator
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBNextPattern\fP (int index)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static string JBToolkit\&.ColorHelper\&.ColourHelper\&.PatternGenerator\&.NextPattern (int index)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
