.TH "JBToolkit.WinForms" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractControlDescriptionProvider\fP"
.br
.ti -1c
.RI "class \fBAntiAliasedLabel\fP"
.br
.RI "Adds better anti-aliasing to a label for better visuals Warning: Can look fuzzy when used in certain places "
.ti -1c
.RI "class \fBFastScrollDataGridView\fP"
.br
.RI "Must smoother scrolling \fBDataGridView\fP wrapper control "
.ti -1c
.RI "class \fBOptimisedMetroForm\fP"
.br
.RI "Abstract form to inherit that uses the MetroForms styler, and optimises buffering, drawing, size grips, resizing shadow, allows custom tooltip for each control by putting a string in the control's 'Tag' property and handles client screen DPI not set to 100% more effectively\&. "
.ti -1c
.RI "class \fBRoundButton\fP"
.br
.RI "Nicer looking 'round' edge button "
.ti -1c
.RI "class \fBRoundedRectangleF\fP"
.br
.RI "Produces a rectangle graphics path with curved edges "
.ti -1c
.RI "class \fBRoundPictureBox\fP"
.br
.ti -1c
.RI "class \fBRoundTextBox\fP"
.br
.RI "Nicer looking 'round' edge text box "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMouseState\fP { \fBMouseState\&.Enter\fP, \fBMouseState\&.Leave\fP, \fBMouseState\&.Down\fP, \fBMouseState\&.Up\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBJBToolkit\&.WinForms\&.MouseState\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEnter \fP\fP
.TP
\fB\fILeave \fP\fP
.TP
\fB\fIDown \fP\fP
.TP
\fB\fIUp \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
