.TH "JBToolkit.WinForms.RoundedRectangleF" 3 "Wed Aug 26 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.RoundedRectangleF \- Produces a rectangle graphics path with curved edges  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoundedRectangleF\fP (float width, float height, float radius, float x=0, float y=0)"
.br
.RI "A rectangle grpahics paths with curved edges "
.ti -1c
.RI "\fBRoundedRectangleF\fP ()"
.br
.RI "A rectangle grpahics paths with curved edges "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RectangleF \fBRect\fP => new RectangleF(x, y, width, height)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "GraphicsPath \fBPath\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBRadius\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Produces a rectangle graphics path with curved edges 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.RoundedRectangleF\&.RoundedRectangleF (float width, float height, float radius, float x = \fC0\fP, float y = \fC0\fP)"

.PP
A rectangle grpahics paths with curved edges 
.SS "JBToolkit\&.WinForms\&.RoundedRectangleF\&.RoundedRectangleF ()"

.PP
A rectangle grpahics paths with curved edges 
.SH "Member Data Documentation"
.PP 
.SS "RectangleF JBToolkit\&.WinForms\&.RoundedRectangleF\&.Rect => new RectangleF(x, y, width, height)"

.SH "Property Documentation"
.PP 
.SS "GraphicsPath JBToolkit\&.WinForms\&.RoundedRectangleF\&.Path\fC [get]\fP"

.SS "float JBToolkit\&.WinForms\&.RoundedRectangleF\&.Radius\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
