.TH "JBToolkit.WinForms.RoundGroupBox" 3 "Sun Nov 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.RoundGroupBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGroupBox\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoundGroupBox\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPaint\fP (PaintEventArgs e)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Color \fBTitleBackColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "HatchStyle \fBTitleHatchStyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Font \fBTitleFont\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Color \fBTitleForeColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBRadious\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.RoundGroupBox\&.RoundGroupBox ()"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.RoundGroupBox\&.OnPaint (PaintEventArgs e)\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "int JBToolkit\&.WinForms\&.RoundGroupBox\&.Radious\fC [get]\fP, \fC [set]\fP"

.SS "Color JBToolkit\&.WinForms\&.RoundGroupBox\&.TitleBackColor\fC [get]\fP, \fC [set]\fP"

.SS "Font JBToolkit\&.WinForms\&.RoundGroupBox\&.TitleFont\fC [get]\fP, \fC [set]\fP"

.SS "Color JBToolkit\&.WinForms\&.RoundGroupBox\&.TitleForeColor\fC [get]\fP, \fC [set]\fP"

.SS "HatchStyle JBToolkit\&.WinForms\&.RoundGroupBox\&.TitleHatchStyle\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
