.TH "JBToolkit.StreamHelpers" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.StreamHelpers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSafeFileStream\fP"
.br
.RI "This is a wrapper around a FileStream\&. While it is not a Stream itself, it can be cast to one (keep in mind that this might throw an exception)\&. It's a mechanism for creating a stream from a file without the issue if it still being used by the calling process later when you want to access it again\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
