.TH "JBToolkit.WinForms.RoundPictureBox" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.RoundPictureBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPictureBox\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoundPictureBox\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPaint\fP (PaintEventArgs e)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.WinForms\&.RoundPictureBox\&.RoundPictureBox ()"

.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.RoundPictureBox\&.OnPaint (PaintEventArgs e)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
