.TH "JBToolkit" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAssemblies\fP"
.br
.ti -1c
.RI "namespace \fBCulture\fP"
.br
.ti -1c
.RI "namespace \fBFuzzyLogic\fP"
.br
.ti -1c
.RI "namespace \fBImaging\fP"
.br
.ti -1c
.RI "namespace \fBNetwork\fP"
.br
.ti -1c
.RI "namespace \fBStreamHelpers\fP"
.br
.ti -1c
.RI "namespace \fBThreads\fP"
.br
.ti -1c
.RI "namespace \fBWindows\fP"
.br
.ti -1c
.RI "namespace \fBWinForms\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColourHelper\fP"
.br
.RI "Methods to convert RGB to hex, hex to RGB, alter colour brightness, lightness, intensity, also generate random 'nice' colours\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
