.TH "JBToolkit.ColorHelper.ColourHelper.IntensityValueWalker" 3 "Tue Aug 25 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ColorHelper.ColourHelper.IntensityValueWalker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntensityValueWalker\fP ()"
.br
.ti -1c
.RI "void \fBMoveNext\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIntensityValue\fP \fBCurrent\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JBToolkit\&.ColorHelper\&.ColourHelper\&.IntensityValueWalker\&.IntensityValueWalker ()"

.SH "Member Function Documentation"
.PP 
.SS "void JBToolkit\&.ColorHelper\&.ColourHelper\&.IntensityValueWalker\&.MoveNext ()"

.SH "Property Documentation"
.PP 
.SS "\fBIntensityValue\fP JBToolkit\&.ColorHelper\&.ColourHelper\&.IntensityValueWalker\&.Current\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
