.TH "JBToolkit.WinForms.FastScrollDataGridView" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.WinForms.FastScrollDataGridView \- Must smoother scrolling \fBDataGridView\fP wrapper control  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDataGridView\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBWndProc\fP (ref Message m)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBDisableScroll\fP = false\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Must smoother scrolling \fBDataGridView\fP wrapper control 


.SH "Member Function Documentation"
.PP 
.SS "override void JBToolkit\&.WinForms\&.FastScrollDataGridView\&.WndProc (ref Message m)\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "bool JBToolkit\&.WinForms\&.FastScrollDataGridView\&.DisableScroll = false\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
