.TH "JBToolkit.ColourHelper" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.ColourHelper \- Methods to convert RGB to hex, hex to RGB, alter colour brightness, lightness, intensity, also generate random 'nice' colours\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColourGenerator\fP"
.br
.RI "Generates random colours close to primary colours as hex string and doesn't repeat a colour "
.ti -1c
.RI "class \fBIntensityGenerator\fP"
.br
.ti -1c
.RI "class \fBIntensityValue\fP"
.br
.ti -1c
.RI "class \fBIntensityValueWalker\fP"
.br
.ti -1c
.RI "class \fBPatternGenerator\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Color \fBHexStringToColor\fP (string hexColor)"
.br
.RI "Color hex to System\&.Drawing\&.Color "
.ti -1c
.RI "static string \fBExtractHexDigits\fP (string input)"
.br
.RI "Extract the hex color digits from a string "
.ti -1c
.RI "static Color \fBChangeColorBrightness\fP (Color color, float correctionFactor)"
.br
.RI "Change the brightness of a colour "
.ti -1c
.RI "static Bitmap \fBAdjustBrightness\fP (Image image, float brightness)"
.br
.RI "Change the brightness of an image "
.ti -1c
.RI "static Bitmap \fBLightenImage\fP (Bitmap bmp)"
.br
.RI "Lighten (the gamma) of an image "
.ti -1c
.RI "static string \fBRGBColourStringToHex\fP (string colorString)"
.br
.RI "Change RGB color string to hex string "
.ti -1c
.RI "static string \fBColorToHexString\fP (Color color)"
.br
.RI "System\&.Drawing\&.Color to hex string "
.ti -1c
.RI "static void \fBMakeTransparent\fP (\fBControl\fP control, Graphics g)"
.br
.RI "Makes a control transparent "
.in -1c
.SH "Detailed Description"
.PP 
Methods to convert RGB to hex, hex to RGB, alter colour brightness, lightness, intensity, also generate random 'nice' colours\&. 


.SH "Member Function Documentation"
.PP 
.SS "static Bitmap JBToolkit\&.ColourHelper\&.AdjustBrightness (Image image, float brightness)\fC [static]\fP"

.PP
Change the brightness of an image 
.SS "static Color JBToolkit\&.ColourHelper\&.ChangeColorBrightness (Color color, float correctionFactor)\fC [static]\fP"

.PP
Change the brightness of a colour 
.SS "static string JBToolkit\&.ColourHelper\&.ColorToHexString (Color color)\fC [static]\fP"

.PP
System\&.Drawing\&.Color to hex string 
.SS "static string JBToolkit\&.ColourHelper\&.ExtractHexDigits (string input)\fC [static]\fP"

.PP
Extract the hex color digits from a string 
.SS "static Color JBToolkit\&.ColourHelper\&.HexStringToColor (string hexColor)\fC [static]\fP"

.PP
Color hex to System\&.Drawing\&.Color 
.SS "static Bitmap JBToolkit\&.ColourHelper\&.LightenImage (Bitmap bmp)\fC [static]\fP"

.PP
Lighten (the gamma) of an image 
.SS "static void JBToolkit\&.ColourHelper\&.MakeTransparent (\fBControl\fP control, Graphics g)\fC [static]\fP"

.PP
Makes a control transparent 
.SS "static string JBToolkit\&.ColourHelper\&.RGBColourStringToHex (string colorString)\fC [static]\fP"

.PP
Change RGB color string to hex string 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
