.TH "JBToolkit.Windows.FileData" 3 "Sun Aug 23 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Windows.FileData \- Contains information about a file returned by the FastDirectoryEnumerator class\&. 
.br
  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a T:System\&.String that represents the current T:System\&.Object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly FileAttributes \fBAttributes\fP"
.br
.RI "Attributes of the file\&. "
.ti -1c
.RI "readonly DateTime \fBCreationTimeUtc\fP"
.br
.RI "File creation time in UTC "
.ti -1c
.RI "readonly DateTime \fBLastAccessTimeUtc\fP"
.br
.RI "File last access time in UTC "
.ti -1c
.RI "readonly DateTime \fBLastWriteTimeUtc\fP"
.br
.RI "File last write time in UTC "
.ti -1c
.RI "readonly long \fBSize\fP"
.br
.RI "Size of the file in bytes "
.ti -1c
.RI "readonly string \fBName\fP"
.br
.RI "Name of the file "
.ti -1c
.RI "readonly string \fBPath\fP"
.br
.RI "Full path to the file\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBCreationTime\fP\fC [get]\fP"
.br
.ti -1c
.RI "DateTime \fBLastAccesTime\fP\fC [get]\fP"
.br
.RI "Gets the last access time in local time\&. "
.ti -1c
.RI "DateTime \fBLastWriteTime\fP\fC [get]\fP"
.br
.RI "Gets the last access time in local time\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains information about a file returned by the FastDirectoryEnumerator class\&. 
.br
 

Thanks to: wilsone8 https://www.codeproject.com/Articles/38959/A-Faster-Directory-Enumerator
.SH "Member Function Documentation"
.PP 
.SS "override string JBToolkit\&.Windows\&.FileData\&.ToString ()"

.PP
Returns a T:System\&.String that represents the current T:System\&.Object\&. 
.PP
\fBReturns\fP
.RS 4
A T:System\&.String that represents the current T:System\&.Object\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "readonly FileAttributes JBToolkit\&.Windows\&.FileData\&.Attributes"

.PP
Attributes of the file\&. 
.SS "readonly DateTime JBToolkit\&.Windows\&.FileData\&.CreationTimeUtc"

.PP
File creation time in UTC 
.SS "readonly DateTime JBToolkit\&.Windows\&.FileData\&.LastAccessTimeUtc"

.PP
File last access time in UTC 
.SS "readonly DateTime JBToolkit\&.Windows\&.FileData\&.LastWriteTimeUtc"

.PP
File last write time in UTC 
.SS "readonly string JBToolkit\&.Windows\&.FileData\&.Name"

.PP
Name of the file 
.SS "readonly string JBToolkit\&.Windows\&.FileData\&.Path"

.PP
Full path to the file\&. 
.SS "readonly long JBToolkit\&.Windows\&.FileData\&.Size"

.PP
Size of the file in bytes 
.SH "Property Documentation"
.PP 
.SS "DateTime JBToolkit\&.Windows\&.FileData\&.CreationTime\fC [get]\fP"

.SS "DateTime JBToolkit\&.Windows\&.FileData\&.LastAccesTime\fC [get]\fP"

.PP
Gets the last access time in local time\&. 
.SS "DateTime JBToolkit\&.Windows\&.FileData\&.LastWriteTime\fC [get]\fP"

.PP
Gets the last access time in local time\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
