.TH "JBToolkit.Culture.CultureHelper" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBToolkit.Culture.CultureHelper \- Current culture helper  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBGloballySetCultureToGB\fP ()"
.br
.RI "GB uses the date format: dd-MM-yyyy "
.in -1c
.SH "Detailed Description"
.PP 
Current culture helper 


.SH "Member Function Documentation"
.PP 
.SS "static void JBToolkit\&.Culture\&.CultureHelper\&.GloballySetCultureToGB ()\fC [static]\fP"

.PP
GB uses the date format: dd-MM-yyyy 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
