.TH "List" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
List
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.AlbumCollection\fP, \fBYTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.ArtistCollection\fP, \fBYTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylistCollection\fP, \fBYTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.PlaylistSongCollection\fP, and \fBYTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.SongCollection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
