.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Repos/MusicFileRepo.cs" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Repos/MusicFileRepo.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.Repos\&.MusicFileRepo\fP"
.br
.RI "Music File database repository access\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.Repos\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
