.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Business/MusicDataFetcher.cs" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Business/MusicDataFetcher.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Business\&.MusicDataFetcher\fP"
.br
.RI "Gets meta data / tag information from the music file itself and looks up any missing data using a \fBMusicBrainz\fP API implementation (for instance album cover art, in which it will lookup CoverArtArchive: https://coverartarchive.org/ "
.ti -1c
.RI "class \fBYTMusicUploader\&.Business\&.MusicDataFetcher\&.TrackAndReleaseMbId\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Business\&.MusicFileMetaData\fP"
.br
.RI "Custom music file meta tag object "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Business\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
