.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/NameCredit.cs" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/NameCredit.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.NameCredit\fP"
.br
.RI "\fBArtist\fP credits indicate who is the main credited artist (or artists) for releases, release groups, tracks and recordings\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\&.Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
