.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/CustomControls/OptimisedMetroForm.cs" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/CustomControls/OptimisedMetroForm.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.OptimisedMetroForm\fP"
.br
.RI "Abstract form to inherit that uses the MetroForms styler, and optimises buffering, drawing, size grips, resizing shadow, allows custom tooltip for each control by putting a string in the control's 'Tag' property and handles client screen DPI not set to 100% more effectively\&. "
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.AbstractControlDescriptionProvider< TAbstract, TBase >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.WinForms\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
