.TH "OptimisedMetroForm" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptimisedMetroForm
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Dialogues\&.ConnectToYTMusic\fP, \fBYTMusicUploader\&.Dialogues\&.IssueLog\fP, \fBYTMusicUploader\&.Dialogues\&.ManageYTMusic\fP, \fBYTMusicUploader\&.Dialogues\&.UploadLog\fP, and \fBYTMusicUploader\&.MainForm\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
