.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Playlist/Content/PlaylistParserFactory.cs" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Playlist/Content/PlaylistParserFactory.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistParserFactory\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.Playlist\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\fP { \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\&.M3U\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\&.M3U8\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\&.HLSMaster\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\&.HlsMedia\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\&.PLS\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\&.WPL\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\&.ZPL\fP }"
.br
.RI "Music playlist library implementation "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
