.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/Rating.cs" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/Rating.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Rating\fP"
.br
.RI "\fBRating\fP information\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\&.Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
