.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/Recording.cs" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/Recording.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Recording\fP"
.br
.RI "A recording is an entity in \fBMusicBrainz\fP which can be linked to tracks on releases\&. Each track must always be associated with a single recording, but a recording can be linked to any number of tracks\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\&.Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
