.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Requests/Playlists/RemovePlaylistItems.cs" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Requests/Playlists/RemovePlaylistItems.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.Requests\fP"
.br
.RI "YouTube Music API Request Methods "
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.Requests\&.Playlists\fP"
.br
.RI "YouTube Music API request methods specifically for playlist manipulation "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
