.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/CustomControls/RoundButton.cs" 3 "Tue Aug 25 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/CustomControls/RoundButton.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.WinForms\&.RoundButton\fP"
.br
.RI "Nicer looking 'round' edge button "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.WinForms\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJBToolkit\&.WinForms\&.MouseState\fP { \fBJBToolkit\&.WinForms\&.MouseState\&.Enter\fP, \fBJBToolkit\&.WinForms\&.MouseState\&.Leave\fP, \fBJBToolkit\&.WinForms\&.MouseState\&.Down\fP, \fBJBToolkit\&.WinForms\&.MouseState\&.Up\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
