.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/SearchResultsContext.cs" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/SearchResultsContext.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Responsecontext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Servicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Param\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Contents\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Tabbedsearchresultsrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Tab\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Tabrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Endpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Searchendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Content\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Sectionlistrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Content1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicshelfrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Shelfdivider\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicshelfdividerrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Content2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicresponsivelistitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Thumbnail\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Thumbnail1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Thumbnail2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Overlay\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicitemthumbnailoverlayrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Background\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Verticalgradient\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Content3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicplaybuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Playnavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchendpointmusicsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchendpointmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Playicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Pauseicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Playingicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Accessibilityplaydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Accessibilitydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Accessibilitypausedata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Accessibilitydata1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Menu\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Menurenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Accessibility\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Accessibilitydata2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Item\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Menunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Text\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Icon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Navigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchplaylistendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Addtoplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Confirmdialogendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Content4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Confirmdialogrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Title\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Confirmbutton\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Text1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Command\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicdeleteprivatelyownedentitycommand\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Cancelbutton\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Text2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Dialogmessage\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Menuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Text3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Icon1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Serviceendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Queueaddendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Queuetarget\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Command1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Addtotoastaction\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Item1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Notificationtextrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Successresponsetext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Toplevelbutton\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Likebuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Target\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Serviceendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Likeendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Target1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Navigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpointcontextsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpointcontextmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Flexcolumn\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicresponsivelistitemflexcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Text4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Navigationendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpointcontextsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Browseendpointcontextmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchendpointmusicsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchendpointmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Fixedcolumn\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicresponsivelistitemfixedcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Text5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Run8\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.RequestModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
