.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/SearchResults.cs" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Providers/RequestModels/SearchResults.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Responsecontext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Servicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Param\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Contents\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Tabbedsearchresultsrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Tab\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Tabrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Endpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Searchendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Content\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Sectionlistrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Content1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicshelfrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Shelfdivider\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicshelfdividerrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Content2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicresponsivelistitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Thumbnail\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Thumbnail1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Thumbnail2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Overlay\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicitemthumbnailoverlayrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Background\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Verticalgradient\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Content3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicplaybuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Playnavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Watchplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Watchendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Watchendpointmusicsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Watchendpointmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Playicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Pauseicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Playingicon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Accessibilityplaydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Accessibilitydata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Accessibilitypausedata\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Accessibilitydata1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Menu\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Menurenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Accessibility\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Accessibilitydata2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Item\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Menunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Text\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Icon\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Navigationendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Watchplaylistendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Addtoplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Confirmdialogendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Content4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Confirmdialogrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Title\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Confirmbutton\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Buttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Text1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Command\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicdeleteprivatelyownedentitycommand\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Cancelbutton\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Buttonrenderer1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Text2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Dialogmessage\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Menuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Text3\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Icon1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Serviceendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Queueaddendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Queuetarget\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Command1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Addtotoastaction\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Item1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Notificationtextrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Successresponsetext\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run6\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Toplevelbutton\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Likebuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Target\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Serviceendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Likeendpoint\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Target1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Navigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpointcontextsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpointcontextmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Flexcolumn\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicresponsivelistitemflexcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Text4\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run7\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Navigationendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpoint2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpointcontextsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Browseendpointcontextmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Watchendpoint1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Watchendpointmusicsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Watchendpointmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Fixedcolumn\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Musicresponsivelistitemfixedcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Text5\fP"
.br
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Run8\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.RequestModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
