.TH "System" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExtensions\fP"
.br
.RI "Application Extension methods "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
