.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Helpers/ThrottleStream.cs" 3 "Sun Aug 23 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/Helpers/ThrottleStream.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJBToolkit\&.StreamHelpers\&.ThrottledStream\fP"
.br
.RI "Throttle a stream -> Very useful for throttle HttpWebRequest uploads / downloads\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBJBToolkit\fP"
.br
.ti -1c
.RI "namespace \fBJBToolkit\&.StreamHelpers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
