.TH "TypeDescriptionProvider" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeDescriptionProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBToolkit\&.WinForms\&.AbstractControlDescriptionProvider< TAbstract, TBase >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
