.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/Url.cs" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/MusicBrainz/Entities/Url.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Url\fP"
.br
.RI "A URL in \fBMusicBrainz\fP is a specific entity representing a regular internet Uniform Resource Locator\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.MusicBrainz\&.API\&.Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
