.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Business/Pipes/WcfServer.cs" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Business/Pipes/WcfServer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Business\&.Pipes\&.WcfServer\fP"
.br
.RI "WCF Named pipe server - To receive data fro, an existing \fBYTMusicUploader\fP process "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Business\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Business\&.Pipes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
