.TH "D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Playlist/Models/WplPlaylist.cs" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Repositories/YTMusicUploader/YTMusicUploader/Providers/Playlist/Models/WplPlaylist.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.WplPlaylist\fP"
.br
.RI "Music playlist library implementation "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBYTMusicUploader\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.Playlist\fP"
.br
.ti -1c
.RI "namespace \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
