.TH "YTMusicUploader.MusicBrainz.API.Entities.Label" 3 "Wed Aug 26 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Label \- \fBLabel\fP information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the \fBMusicBrainz\fP id\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name\&. "
.ti -1c
.RI "string \fBDisambiguation\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the disambiguation\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBLabel\fP information\&. 


.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Label\&.Disambiguation\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the disambiguation\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Label\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the \fBMusicBrainz\fP id\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Label\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
