.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Musicresponsivelistitemfixedcolumnrenderer" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Musicresponsivelistitemfixedcolumnrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBText5\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBdisplayPriority\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBsize\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Musicresponsivelistitemfixedcolumnrenderer\&.displayPriority\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Musicresponsivelistitemfixedcolumnrenderer\&.size\fC [get]\fP, \fC [set]\fP"

.SS "\fBText5\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Musicresponsivelistitemfixedcolumnrenderer\&.text\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
