.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Responsecontext" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Responsecontext
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBvisitorData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBmaxAgeSeconds\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBServicetrackingparam\fP[] \fBserviceTrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Responsecontext\&.maxAgeSeconds\fC [get]\fP, \fC [set]\fP"

.SS "\fBServicetrackingparam\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Responsecontext\&.serviceTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Responsecontext\&.visitorData\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
