.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Menunavigationitemrenderer" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Menunavigationitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBText\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIcon\fP \fBicon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNavigationendpoint\fP \fBnavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBIcon\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Menunavigationitemrenderer\&.icon\fC [get]\fP, \fC [set]\fP"

.SS "\fBNavigationendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Menunavigationitemrenderer\&.navigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBText\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Menunavigationitemrenderer\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Menunavigationitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
