.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Cancelbutton" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Cancelbutton
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBButtonrenderer1\fP \fBbuttonRenderer\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBButtonrenderer1\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Cancelbutton\&.buttonRenderer\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
