.TH "YTMusicUploader.Providers.Playlist.Models.HlsMediaPlaylistEntry" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.HlsMediaPlaylistEntry \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylistEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHlsMediaPlaylistEntry\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBDuration\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBMediaSequence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBDiscontinuity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBByteRange\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBKey\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMap\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime? \fBProgramDateTime\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.HlsMediaPlaylistEntry ()"

.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.ByteRange\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.Discontinuity\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.Duration\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.Key\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.Map\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.MediaSequence\fC [get]\fP, \fC [set]\fP"

.SS "DateTime? YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.ProgramDateTime\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\&.Title\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
