.TH "YTMusicUploader.Providers.RequestModels" 3 "Wed Aug 26 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIRequestModel\fP"
.br
.ti -1c
.RI "class \fBSearchContext\fP"
.br
.RI "Deserialised HttpWebRequest body to send to YouTube Music to perform a search of uploaded songs "
.ti -1c
.RI "class \fBSearchResult\fP"
.br
.RI "Deserialised HttpWebRequest response body send by YouTube Music of search results "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
