.TH "YTMusicUploader.Providers.Playlist.Content.PlaylistParserFactory" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.PlaylistParserFactory
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIPlaylistParser\fP< \fBIBasePlaylist\fP > \fBGetPlaylistParser\fP (string fileType)"
.br
.ti -1c
.RI "static \fBIPlaylistParser\fP< \fBIBasePlaylist\fP > \fBGetPlaylistParser\fP (\fBPlaylistType\fP playlistType)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBIPlaylistParser\fP<\fBIBasePlaylist\fP> YTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistParserFactory\&.GetPlaylistParser (\fBPlaylistType\fP playlistType)\fC [static]\fP"

.SS "static \fBIPlaylistParser\fP<\fBIBasePlaylist\fP> YTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistParserFactory\&.GetPlaylistParser (string fileType)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
