.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Browseendpoint1" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Browseendpoint1
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBbrowseId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBrowseendpointcontextsupportedconfigs1\fP \fBbrowseEndpointContextSupportedConfigs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBBrowseendpointcontextsupportedconfigs1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Browseendpoint1\&.browseEndpointContextSupportedConfigs\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Browseendpoint1\&.browseId\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
