.TH "YTMusicUploader.MusicBrainz.API.Entities.Area" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Area \- Areas are geographic regions or settlements\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the \fBMusicBrainz\fP id\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name\&. "
.ti -1c
.RI "string \fBType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the type\&. "
.ti -1c
.RI "string \fBDisambiguation\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the disambiguation\&. "
.ti -1c
.RI "\fBList\fP< string > \fBIsoCodes\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the iso-3166-1 codes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Areas are geographic regions or settlements\&. 


.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Area\&.Disambiguation\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the disambiguation\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Area\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the \fBMusicBrainz\fP id\&. 
.SS "\fBList\fP<string> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Area\&.IsoCodes\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the iso-3166-1 codes\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Area\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Area\&.Type\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
