.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Navigationendpoint4" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Navigationendpoint4
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBWatchplaylistendpoint1\fP \fBwatchPlaylistEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPlaylisteditorendpoint\fP \fBplaylistEditorEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Navigationendpoint4\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlaylisteditorendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Navigationendpoint4\&.playlistEditorEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBWatchplaylistendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Navigationendpoint4\&.watchPlaylistEndpoint\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
