.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Musictworowitemrenderer1" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Musictworowitemrenderer1
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBThumbnailrenderer1\fP \fBthumbnailRenderer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBaspectRatio\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTitle3\fP \fBtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNavigationendpoint6\fP \fBnavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSubtitle1\fP \fBsubtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMenu1\fP \fBmenu\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBThumbnailoverlay1\fP \fBthumbnailOverlay\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\&.aspectRatio\fC [get]\fP, \fC [set]\fP"

.SS "\fBMenu1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\&.menu\fC [get]\fP, \fC [set]\fP"

.SS "\fBNavigationendpoint6\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\&.navigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBSubtitle1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\&.subtitle\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnailoverlay1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\&.thumbnailOverlay\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnailrenderer1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\&.thumbnailRenderer\fC [get]\fP, \fC [set]\fP"

.SS "\fBTitle3\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\&.title\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Musictworowitemrenderer1\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
