.TH "YTMusicUploader.Providers.Playlist.Content.PlaylistToTextHelper" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.PlaylistToTextHelper \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBToText\fP (\fBIBasePlaylist\fP playlist)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Member Function Documentation"
.PP 
.SS "static string YTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistToTextHelper\&.ToText (\fBIBasePlaylist\fP playlist)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
