.TH "YTMusicUploader.Providers.Playlist.Models.BasePlaylistEntry" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.BasePlaylistEntry \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylistEntry\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.M3uPlaylistEntry\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.PlsPlaylistEntry\fP, \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.WplPlaylistEntry\fP, and \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.ZplPlaylistEntry\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPath\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylistEntry\&.Path\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
