.TH "YTMusicUploader.Business.Pipes.IIpcClient" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.Pipes.IIpcClient
.SH SYNOPSIS
.br
.PP
.PP
Inherited by YTMusicUploader\&.Business\&.Pipes\&.WcfClient\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSend\fP (string data)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void YTMusicUploader\&.Business\&.Pipes\&.IIpcClient\&.Send (string data)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
