.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContinuationContext.Menuserviceitemrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContinuationContext.Menuserviceitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBText3\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIcon1\fP \fBicon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBServiceendpoint1\fP \fBserviceEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBIcon1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Menuserviceitemrenderer\&.icon\fC [get]\fP, \fC [set]\fP"

.SS "\fBServiceendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Menuserviceitemrenderer\&.serviceEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBText3\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Menuserviceitemrenderer\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Menuserviceitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
