.TH "YTMusicUploader.Providers.RequestModels.DeletePlaylistItemRequestContext.Capabilities" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.DeletePlaylistItemRequestContext.Capabilities
.SH SYNOPSIS
.br
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
