.TH "YTMusicUploader.Providers.RequestModels.SearchContext.Request" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchContext.Request
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBList\fP< \fBInternalExperimentFlag\fP > \fBinternalExperimentFlags\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBsessionIndex\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBList\fP<\fBInternalExperimentFlag\fP> YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Request\&.internalExperimentFlags\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Request\&.sessionIndex\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
