.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Servicetrackingparam" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Servicetrackingparam
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBservice\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBParam\fP[] \fB_params\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBParam\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Servicetrackingparam\&._params\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Servicetrackingparam\&.service\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
