.TH "YTMusicUploader.Providers.RequestModels.SearchResult.Endpoint" 3 "Mon Aug 24 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResult.Endpoint
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSearchEndpoint\fP \fBsearchEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Endpoint\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "\fBSearchEndpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.Endpoint\&.searchEndpoint\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
