.TH "YTMusicUploader.MusicBrainz.API.Entities" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCollections\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArea\fP"
.br
.RI "Areas are geographic regions or settlements\&. "
.ti -1c
.RI "class \fBArtist\fP"
.br
.RI "An artist is generally a musician (or musician persona), group of musicians or other music professional (like a producer or engineer)\&. "
.ti -1c
.RI "class \fBCoverArtArchive\fP"
.br
.RI "Cover Art Archive information\&. "
.ti -1c
.RI "class \fBDisc\fP"
.br
.ti -1c
.RI "class \fBLabel\fP"
.br
.RI "\fBLabel\fP information\&. "
.ti -1c
.RI "class \fBLabelInfo\fP"
.br
.ti -1c
.RI "class \fBLifeSpan\fP"
.br
.ti -1c
.RI "class \fBMedium\fP"
.br
.RI "Physical representation of a release\&. "
.ti -1c
.RI "class \fBNameCredit\fP"
.br
.RI "\fBArtist\fP credits indicate who is the main credited artist (or artists) for releases, release groups, tracks and recordings\&. "
.ti -1c
.RI "class \fBRating\fP"
.br
.RI "\fBRating\fP information\&. "
.ti -1c
.RI "class \fBRecording\fP"
.br
.RI "A recording is an entity in \fBMusicBrainz\fP which can be linked to tracks on releases\&. Each track must always be associated with a single recording, but a recording can be linked to any number of tracks\&. "
.ti -1c
.RI "class \fBRelation\fP"
.br
.RI "Relationships are a way to represent all the different ways in which entities are connected to each other and to URLs outside \fBMusicBrainz\fP\&. "
.ti -1c
.RI "class \fBRelease\fP"
.br
.RI "A \fBMusicBrainz\fP release represents the unique release (i\&.e\&. issuing) of a product on a specific date with specific release information such as the country, label, barcode and packaging\&. "
.ti -1c
.RI "class \fBReleaseGroup\fP"
.br
.RI "A release group is used to group several different releases into a single logical entity\&. "
.ti -1c
.RI "class \fBTag\fP"
.br
.ti -1c
.RI "class \fBTextRepresentation\fP"
.br
.ti -1c
.RI "class \fBTrack\fP"
.br
.RI "In \fBMusicBrainz\fP, a track is the way a recording is represented on a particular release (or, more exactly, on a particular medium)\&. "
.ti -1c
.RI "class \fBUrl\fP"
.br
.RI "A URL in \fBMusicBrainz\fP is a specific entity representing a regular internet Uniform Resource Locator\&. "
.ti -1c
.RI "class \fBWork\fP"
.br
.RI "In \fBMusicBrainz\fP terminology, a work is a distinct intellectual or artistic creation, which can be expressed in the form of one or more audio recordings\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
