.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Confirmdialogrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Confirmdialogrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTitle4\fP \fBtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDialogmessage\fP[] \fBdialogMessages\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBConfirmbutton\fP \fBconfirmButton\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCancelbutton\fP \fBcancelButton\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBCancelbutton\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Confirmdialogrenderer\&.cancelButton\fC [get]\fP, \fC [set]\fP"

.SS "\fBConfirmbutton\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Confirmdialogrenderer\&.confirmButton\fC [get]\fP, \fC [set]\fP"

.SS "\fBDialogmessage\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Confirmdialogrenderer\&.dialogMessages\fC [get]\fP, \fC [set]\fP"

.SS "\fBTitle4\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Confirmdialogrenderer\&.title\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Confirmdialogrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
