.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistRequestContext.Context" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistRequestContext.Context
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBClient\fP \fBclient\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCapabilities\fP \fBcapabilities\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBRequest\fP \fBrequest\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBClicktracking\fP \fBclickTracking\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBActiveplayers\fP \fBactivePlayers\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBUser\fP \fBuser\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBActiveplayers\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.Context\&.activePlayers\fC [get]\fP, \fC [set]\fP"

.SS "\fBCapabilities\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.Context\&.capabilities\fC [get]\fP, \fC [set]\fP"

.SS "\fBClicktracking\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.Context\&.clickTracking\fC [get]\fP, \fC [set]\fP"

.SS "\fBClient\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.Context\&.client\fC [get]\fP, \fC [set]\fP"

.SS "\fBRequest\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.Context\&.request\fC [get]\fP, \fC [set]\fP"

.SS "\fBUser\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.Context\&.user\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
