.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Playnavigationendpoint" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Playnavigationendpoint
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBWatchplaylistendpoint\fP \fBwatchPlaylistEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBWatchendpoint\fP \fBwatchEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Playnavigationendpoint\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "\fBWatchendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Playnavigationendpoint\&.watchEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBWatchplaylistendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Playnavigationendpoint\&.watchPlaylistEndpoint\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
