.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Menurenderer" 3 "Sun Nov 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Menurenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBItem\fP[] \fBitems\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBToplevelbutton\fP[] \fBtopLevelButtons\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibility\fP \fBaccessibility\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAccessibility\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Menurenderer\&.accessibility\fC [get]\fP, \fC [set]\fP"

.SS "\fBItem\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Menurenderer\&.items\fC [get]\fP, \fC [set]\fP"

.SS "\fBToplevelbutton\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Menurenderer\&.topLevelButtons\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Menurenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
