.TH "YTMusicUploader.Dialogues" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Dialogues
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplicationLog\fP"
.br
.RI "Application Log (info and error) Dialogue "
.ti -1c
.RI "class \fBConnectToYTMusic\fP"
.br
.RI "Shows a WebView2 control https://docs.microsoft.com/en-us/microsoft-edge/webview2/ "
.ti -1c
.RI "class \fBIssueLog\fP"
.br
.RI "Upload Issues Log Dialogue "
.ti -1c
.RI "class \fBManageYTMusic\fP"
.br
.RI "Dialogue Form to delete song / albums from YT Music "
.ti -1c
.RI "class \fBUploadLog\fP"
.br
.RI "Success Upload Log Dialogue "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
