.TH "YTMusicUploader.Providers.Playlist.Models.PlsPlaylist" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.PlsPlaylist \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist< PlsPlaylistEntry >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlsPlaylist\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNumberOfEntries\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Providers\&.Playlist\&.Models\&.PlsPlaylist\&.PlsPlaylist ()"

.SH "Property Documentation"
.PP 
.SS "int YTMusicUploader\&.Providers\&.Playlist\&.Models\&.PlsPlaylist\&.NumberOfEntries\fC [get]\fP"

.SS "int YTMusicUploader\&.Providers\&.Playlist\&.Models\&.PlsPlaylist\&.Version\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
