.TH "YTMusicUploader.Providers.DataModels.IDbModel" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.DataModels.IDbModel
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< \fBDbOperationResult\fP > \fBSave\fP ()"
.br
.ti -1c
.RI "Task< \fBDbOperationResult\fP > \fBDelete\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Task<\fBDbOperationResult\fP> YTMusicUploader\&.Providers\&.DataModels\&.IDbModel\&.Delete ()"

.PP
Implemented in \fBYTMusicUploader\&.Providers\&.DataModels\&.MusicFile\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.Log\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.WatchFolder\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.Settings\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.PlaylistFile\fP, and \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SS "Task<\fBDbOperationResult\fP> YTMusicUploader\&.Providers\&.DataModels\&.IDbModel\&.Save ()"

.PP
Implemented in \fBYTMusicUploader\&.Providers\&.DataModels\&.MusicFile\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.Log\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.PlaylistFile\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.Settings\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.WatchFolder\fP, and \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SH "Property Documentation"
.PP 
.SS "int YTMusicUploader\&.Providers\&.DataModels\&.IDbModel\&.Id\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
