.TH "YTMusicUploader.Providers.RequestModels.SearchResult" 3 "Tue Aug 25 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResult \- Deserialised HttpWebRequest response body send by YouTube Music of search results  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.RequestModels\&.IRequestModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContent\fP"
.br
.ti -1c
.RI "class \fBContent2\fP"
.br
.ti -1c
.RI "class \fBContent3\fP"
.br
.ti -1c
.RI "class \fBContents\fP"
.br
.ti -1c
.RI "class \fBEndpoint\fP"
.br
.ti -1c
.RI "class \fBIcon\fP"
.br
.ti -1c
.RI "class \fBItemSectionRenderer\fP"
.br
.ti -1c
.RI "class \fBMessageRenderer\fP"
.br
.ti -1c
.RI "class \fBParam\fP"
.br
.ti -1c
.RI "class \fBResponseContext\fP"
.br
.ti -1c
.RI "class \fBRun\fP"
.br
.ti -1c
.RI "class \fBSearchEndpoint\fP"
.br
.ti -1c
.RI "class \fBSectionListRenderer\fP"
.br
.ti -1c
.RI "class \fBServiceTrackingParam\fP"
.br
.ti -1c
.RI "class \fBTab\fP"
.br
.ti -1c
.RI "class \fBTabbedSearchResultsRenderer\fP"
.br
.ti -1c
.RI "class \fBTabRenderer\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBResponseContext\fP \fBresponseContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContents\fP \fBcontents\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Deserialised HttpWebRequest response body send by YouTube Music of search results 


.SH "Property Documentation"
.PP 
.SS "\fBContents\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.contents\fC [get]\fP, \fC [set]\fP"

.SS "\fBResponseContext\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.responseContext\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
