.TH "YTMusicUploader.Providers.RequestModels.SearchResult.ItemSectionRenderer" 3 "Wed Aug 26 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResult.ItemSectionRenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBContent3\fP > \fBcontents\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "List<\fBContent3\fP> YTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.ItemSectionRenderer\&.contents\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\&.ItemSectionRenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
