.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Navigationendpoint2" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Navigationendpoint2
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBWatchendpoint1\fP \fBwatchEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBrowseendpoint1\fP \fBbrowseEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBBrowseendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Navigationendpoint2\&.browseEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Navigationendpoint2\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "\fBWatchendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Navigationendpoint2\&.watchEndpoint\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
