.TH "YTMusicUploader.MusicBrainz.API.Entities.Track" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Track \- In \fBMusicBrainz\fP, a track is the way a recording is represented on a particular release (or, more exactly, on a particular medium)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the \fBMusicBrainz\fP id\&. "
.ti -1c
.RI "string \fBNumber\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the number\&. "
.ti -1c
.RI "int \fBPosition\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the position\&. "
.ti -1c
.RI "int? \fBLength\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the length\&. "
.ti -1c
.RI "\fBRecording\fP \fBRecording\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the recording\&. "
.in -1c
.SH "Detailed Description"
.PP 
In \fBMusicBrainz\fP, a track is the way a recording is represented on a particular release (or, more exactly, on a particular medium)\&. 


.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Track\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the \fBMusicBrainz\fP id\&. 
.SS "int? YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Track\&.Length\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the length\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Track\&.Number\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the number\&. 
.SS "int YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Track\&.Position\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the position\&. 
.SS "\fBRecording\fP YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Track\&.Recording\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the recording\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
