.TH "YTMusicUploader.Providers.Playlist.Content.PlsContent" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.PlsContent \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistParser< PlsPlaylist >\fP, and \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistWriter< PlsPlaylist >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBToText\fP (\fBPlsPlaylist\fP playlist)"
.br
.ti -1c
.RI "\fBPlsPlaylist\fP \fBGetFromStream\fP (Stream stream)"
.br
.ti -1c
.RI "\fBPlsPlaylist\fP \fBGetFromString\fP (string playlistString)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Member Function Documentation"
.PP 
.SS "\fBPlsPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlsContent\&.GetFromStream (Stream stream)"

.SS "\fBPlsPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlsContent\&.GetFromString (string playlistString)"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlsContent\&.ToText (\fBPlsPlaylist\fP playlist)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
