.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Musicplaylisteditheaderrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Musicplaylisteditheaderrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTitle3\fP \fBtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBEdittitle\fP \fBeditTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDescription\fP \fBdescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBEditdescription\fP \fBeditDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBprivacy\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBplaylistId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCollaborationsettingscommand\fP \fBcollaborationSettingsCommand\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPrivacydropdown\fP \fBprivacyDropdown\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBCollaborationsettingscommand\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.collaborationSettingsCommand\fC [get]\fP, \fC [set]\fP"

.SS "\fBDescription\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.description\fC [get]\fP, \fC [set]\fP"

.SS "\fBEditdescription\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.editDescription\fC [get]\fP, \fC [set]\fP"

.SS "\fBEdittitle\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.editTitle\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.playlistId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.privacy\fC [get]\fP, \fC [set]\fP"

.SS "\fBPrivacydropdown\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.privacyDropdown\fC [get]\fP, \fC [set]\fP"

.SS "\fBTitle3\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.title\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaylisteditheaderrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
