.TH "YTMusicUploader.Providers.RequestModels" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddPlaylistItemContext\fP"
.br
.RI "Deserialised HttpWebRequest request body sent for adding a playlist item "
.ti -1c
.RI "class \fBArtistCache\fP"
.br
.RI "Used to store temporary artist details from YouTube Music to be used for lookups "
.ti -1c
.RI "class \fBBrowseArtistRequestContext\fP"
.br
.RI "Deserialised HttpWebRequest request body sent for a YouTube Music search "
.ti -1c
.RI "class \fBBrowseArtistResultsContext\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.ti -1c
.RI "class \fBBrowseArtistResultsContinuationContext\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.ti -1c
.RI "class \fBBrowseArtistsResultsContext\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.ti -1c
.RI "class \fBBrowseArtistsResultsContinuationContext\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.ti -1c
.RI "class \fBBrowsePlaylistResultsContext\fP"
.br
.ti -1c
.RI "class \fBBrowsePlaylistsResultsContext\fP"
.br
.ti -1c
.RI "class \fBBrowsePlaylistsResultsContinuationContext\fP"
.br
.ti -1c
.RI "class \fBCreatePlaylistRequestContext\fP"
.br
.RI "Deserialised HttpWebRequest request body sent for creating a playlist "
.ti -1c
.RI "class \fBDeleteFromYTMusicRequestContext\fP"
.br
.RI "Deserialised HttpWebRequest request body sent for a YouTube Music entity deletion "
.ti -1c
.RI "class \fBDeletePlaylistItemRequestContext\fP"
.br
.RI "Deserialised HttpWebRequest request body sent for deleting a playlist item "
.ti -1c
.RI "class \fBDeletePlaylistRequestContext\fP"
.br
.RI "Deserialised HttpWebRequest request body sent for deleting a playlist "
.ti -1c
.RI "interface \fBIRequestModel\fP"
.br
.ti -1c
.RI "class \fBMusicManageTreeNodeModel\fP"
.br
.RI "Model for Manage YouTube Music dialogue's TreeView "
.ti -1c
.RI "class \fBSearchContext\fP"
.br
.RI "Deserialised HttpWebRequest body to send to YouTube Music to perform a search of uploaded songs "
.ti -1c
.RI "class \fBSearchResultContext\fP"
.br
.RI "Deserialised HttpWebRequest response body received from YouTube Music after a search "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
