.TH "YTMusicUploader.Providers.RequestModels.SearchContext.Client" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchContext.Client
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBbrowserName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBbrowserVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBclientName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBclientVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< object > \fBexperimentIds\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBexperimentsToken\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBgl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBhl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBLocationInfo\fP \fBlocationInfo\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMusicAppInfo\fP \fBmusicAppInfo\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBosName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBosVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fButcOffsetMinutes\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.browserName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.browserVersion\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.clientName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.clientVersion\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<object> YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.experimentIds\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.experimentsToken\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.gl\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.hl\fC [get]\fP, \fC [set]\fP"

.SS "\fBLocationInfo\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.locationInfo\fC [get]\fP, \fC [set]\fP"

.SS "\fBMusicAppInfo\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.musicAppInfo\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.osName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.osVersion\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.Client\&.utcOffsetMinutes\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
