.TH "YTMusicUploader.Helpers" 3 "Tue Aug 25 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Helpers
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFuzzyLogic\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImageHelper\fP"
.br
.RI "Image helper methods "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
