.TH "YTMusicUploader.Business.PlaylistProcessor" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.PlaylistProcessor \- Responsible for scanning library playlist file and either creating them on YT Music or adding to them on YT Music  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlaylistProcessor\fP (\fBMainForm\fP mainForm)"
.br
.ti -1c
.RI "void \fBProcess\fP ()"
.br
.RI "Execute the playlist management process "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBList\fP< \fBPlaylistFile\fP > \fBPlaylistFiles\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "OnlinePlaylistCollection \fBOnlinePlaylists\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBStopped\fP = false\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsible for scanning library playlist file and either creating them on YT Music or adding to them on YT Music 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Business\&.PlaylistProcessor\&.PlaylistProcessor (\fBMainForm\fP mainForm)"

.SH "Member Function Documentation"
.PP 
.SS "void YTMusicUploader\&.Business\&.PlaylistProcessor\&.Process ()"

.PP
Execute the playlist management process 
.SH "Property Documentation"
.PP 
.SS "OnlinePlaylistCollection YTMusicUploader\&.Business\&.PlaylistProcessor\&.OnlinePlaylists\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<\fBPlaylistFile\fP> YTMusicUploader\&.Business\&.PlaylistProcessor\&.PlaylistFiles\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Business\&.PlaylistProcessor\&.Stopped = false\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
