.TH "YTMusicUploader.Providers.Playlist.Content.IPlaylistParser< out out T >" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.IPlaylistParser< out out T > \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBGetFromStream\fP (Stream stream)"
.br
.ti -1c
.RI "T \fBGetFromString\fP (string playlistString)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIBasePlaylist\fP
.SH "Member Function Documentation"
.PP 
.SS "T \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistParser\fP< out out T >\&.GetFromStream (Stream stream)"

.SS "T \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistParser\fP< out out T >\&.GetFromString (string playlistString)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
