.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Title1" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Title1
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRun9\fP[] \fBruns\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBRun9\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Title1\&.runs\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
