.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Text" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Text
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRun\fP[] \fBruns\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBRun\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Text\&.runs\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
