.TH "YTMusicUploader.Providers.Models.DbModels" 3 "Mon Aug 24 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Models.DbModels
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Models\&.IDbModel\fP\&.
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.Models\&.MusicFile\fP, \fBYTMusicUploader\&.Providers\&.Models\&.Settings\fP, and \fBYTMusicUploader\&.Providers\&.Models\&.WatchFolder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract \fBDbOperationResult\fP \fBSave\fP ()"
.br
.ti -1c
.RI "abstract \fBDbOperationResult\fP \fBDelete\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP = \-1\fC [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "abstract \fBDbOperationResult\fP YTMusicUploader\&.Providers\&.Models\&.DbModels\&.Delete ()\fC [pure virtual]\fP"

.PP
Implements \fBYTMusicUploader\&.Providers\&.Models\&.IDbModel\fP\&.
.PP
Implemented in \fBYTMusicUploader\&.Providers\&.Models\&.MusicFile\fP, \fBYTMusicUploader\&.Providers\&.Models\&.WatchFolder\fP, and \fBYTMusicUploader\&.Providers\&.Models\&.Settings\fP\&.
.SS "abstract \fBDbOperationResult\fP YTMusicUploader\&.Providers\&.Models\&.DbModels\&.Save ()\fC [pure virtual]\fP"

.PP
Implements \fBYTMusicUploader\&.Providers\&.Models\&.IDbModel\fP\&.
.PP
Implemented in \fBYTMusicUploader\&.Providers\&.Models\&.MusicFile\fP, \fBYTMusicUploader\&.Providers\&.Models\&.Settings\fP, and \fBYTMusicUploader\&.Providers\&.Models\&.WatchFolder\fP\&.
.SH "Property Documentation"
.PP 
.SS "int YTMusicUploader\&.Providers\&.Models\&.DbModels\&.Id = \-1\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
