.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Itemsectiontabbedheaderrenderer" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Itemsectiontabbedheaderrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTab1\fP[] \fBtabs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBEnditem\fP[] \fBendItems\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBEnditem\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Itemsectiontabbedheaderrenderer\&.endItems\fC [get]\fP, \fC [set]\fP"

.SS "\fBTab1\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Itemsectiontabbedheaderrenderer\&.tabs\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Itemsectiontabbedheaderrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
