.TH "YTMusicUploader.Providers.Playlist.Models.HlsPlaylistEntry" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.HlsPlaylistEntry \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylistEntry\fP\&.
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\fP, and \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylistEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHlsPlaylistEntry\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< string, string > \fBCustomProperties\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< string > \fBComments\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylistEntry\&.HlsPlaylistEntry ()"

.SH "Property Documentation"
.PP 
.SS "\fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylistEntry\&.Comments\fC [get]\fP, \fC [set]\fP"

.SS "Dictionary<string, string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylistEntry\&.CustomProperties\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
