.TH "YTMusicUploader.Business.RegistrySettings" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.RegistrySettings \- Windows registry helper methods  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static async Task \fBSetStartWithWindows\fP (bool startWithWindows)"
.br
.RI "For setting whether the app starts with Windows or not\&. Uses the 'CurrentVersion\\Run' sub key in the users key "
.in -1c
.SH "Detailed Description"
.PP 
Windows registry helper methods 


.SH "Member Function Documentation"
.PP 
.SS "static async Task YTMusicUploader\&.Business\&.RegistrySettings\&.SetStartWithWindows (bool startWithWindows)\fC [static]\fP"

.PP
For setting whether the app starts with Windows or not\&. Uses the 'CurrentVersion\\Run' sub key in the users key 
.PP
\fBParameters\fP
.RS 4
\fIstartWithWindows\fP Set to start with windows if true, false otherwise
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
