.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Musicplaybuttonrenderer" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Musicplaybuttonrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPlaynavigationendpoint\fP \fBplayNavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPlayicon\fP \fBplayIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPauseicon\fP \fBpauseIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBiconColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBbackgroundColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBactiveBackgroundColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBloadingIndicatorColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPlayingicon\fP \fBplayingIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBiconLoadingColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBactiveScaleFactor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBbuttonSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBrippleTarget\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibilityplaydata\fP \fBaccessibilityPlayData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibilitypausedata\fP \fBaccessibilityPauseData\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAccessibilitypausedata\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.accessibilityPauseData\fC [get]\fP, \fC [set]\fP"

.SS "\fBAccessibilityplaydata\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.accessibilityPlayData\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.activeBackgroundColor\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.activeScaleFactor\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.backgroundColor\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.buttonSize\fC [get]\fP, \fC [set]\fP"

.SS "long YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.iconColor\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.iconLoadingColor\fC [get]\fP, \fC [set]\fP"

.SS "long YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.loadingIndicatorColor\fC [get]\fP, \fC [set]\fP"

.SS "\fBPauseicon\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.pauseIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlayicon\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.playIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlayingicon\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.playingIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlaynavigationendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.playNavigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.rippleTarget\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicplaybuttonrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
