.TH "YTMusicUploader.Providers.DataModels.DbModels" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.DataModels.DbModels
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.DataModels\&.IDbModel\fP\&.
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.DataModels\&.Log\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.MusicFile\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.Settings\fP, and \fBYTMusicUploader\&.Providers\&.DataModels\&.WatchFolder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract Task< \fBDbOperationResult\fP > \fBSave\fP ()"
.br
.ti -1c
.RI "abstract Task< \fBDbOperationResult\fP > \fBDelete\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP = \-1\fC [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "abstract Task<\fBDbOperationResult\fP> YTMusicUploader\&.Providers\&.DataModels\&.DbModels\&.Delete ()\fC [pure virtual]\fP"

.PP
Implements \fBYTMusicUploader\&.Providers\&.DataModels\&.IDbModel\fP\&.
.PP
Implemented in \fBYTMusicUploader\&.Providers\&.DataModels\&.MusicFile\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.Log\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.WatchFolder\fP, and \fBYTMusicUploader\&.Providers\&.DataModels\&.Settings\fP\&.
.SS "abstract Task<\fBDbOperationResult\fP> YTMusicUploader\&.Providers\&.DataModels\&.DbModels\&.Save ()\fC [pure virtual]\fP"

.PP
Implements \fBYTMusicUploader\&.Providers\&.DataModels\&.IDbModel\fP\&.
.PP
Implemented in \fBYTMusicUploader\&.Providers\&.DataModels\&.MusicFile\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.Log\fP, \fBYTMusicUploader\&.Providers\&.DataModels\&.Settings\fP, and \fBYTMusicUploader\&.Providers\&.DataModels\&.WatchFolder\fP\&.
.SH "Property Documentation"
.PP 
.SS "int YTMusicUploader\&.Providers\&.DataModels\&.DbModels\&.Id = \-1\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
