.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Musicresponsivelistitemflexcolumnrenderer" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Musicresponsivelistitemflexcolumnrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBText4\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBdisplayPriority\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicresponsivelistitemflexcolumnrenderer\&.displayPriority\fC [get]\fP, \fC [set]\fP"

.SS "\fBText4\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Musicresponsivelistitemflexcolumnrenderer\&.text\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
