.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Item" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Item
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMenunavigationitemrenderer\fP \fBmenuNavigationItemRenderer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMenuserviceitemrenderer\fP \fBmenuServiceItemRenderer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTogglemenuserviceitemrenderer\fP \fBtoggleMenuServiceItemRenderer\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBMenunavigationitemrenderer\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Item\&.menuNavigationItemRenderer\fC [get]\fP, \fC [set]\fP"

.SS "\fBMenuserviceitemrenderer\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Item\&.menuServiceItemRenderer\fC [get]\fP, \fC [set]\fP"

.SS "\fBTogglemenuserviceitemrenderer\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Item\&.toggleMenuServiceItemRenderer\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
