.TH "YTMusicUploader.Providers.Playlist.Content.M3uContent" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.M3uContent \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistParser< M3uPlaylist >\fP, and \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistWriter< M3uPlaylist >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBToText\fP (\fBM3uPlaylist\fP playlist)"
.br
.ti -1c
.RI "\fBM3uPlaylist\fP \fBGetFromStream\fP (Stream stream)"
.br
.ti -1c
.RI "\fBM3uPlaylist\fP \fBGetFromString\fP (string playlistString)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Member Function Documentation"
.PP 
.SS "\fBM3uPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.M3uContent\&.GetFromStream (Stream stream)"

.SS "\fBM3uPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.M3uContent\&.GetFromString (string playlistString)"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Content\&.M3uContent\&.ToText (\fBM3uPlaylist\fP playlist)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
