.TH "YTMusicUploader.Providers" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDataModels\fP"
.br
.ti -1c
.RI "namespace \fBRepos\fP"
.br
.ti -1c
.RI "namespace \fBRequestModels\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataAccess\fP"
.br
.RI "Abastract database repository access class\&. "
.ti -1c
.RI "class \fBDbOperationResult\fP"
.br
.RI "Database process execution and query result object\&. Contains if there's any errors and the time taken to perform the database operation\&. "
.ti -1c
.RI "class \fBRequests\fP"
.br
.RI "YouTube Music API Request Methods "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
