.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Menunavigationitemrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Menunavigationitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBText\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIcon1\fP \fBicon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNavigationendpoint4\fP \fBnavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBIcon1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menunavigationitemrenderer\&.icon\fC [get]\fP, \fC [set]\fP"

.SS "\fBNavigationendpoint4\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menunavigationitemrenderer\&.navigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBText\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menunavigationitemrenderer\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Menunavigationitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
