.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContinuationContext.Musictworowitemrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContinuationContext.Musictworowitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBThumbnailrenderer\fP \fBthumbnailRenderer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBaspectRatio\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTitle\fP \fBtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSubtitle\fP \fBsubtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNavigationendpoint2\fP \fBnavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMenu\fP \fBmenu\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBThumbnailoverlay\fP \fBthumbnailOverlay\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Musictworowitemrenderer\&.aspectRatio\fC [get]\fP, \fC [set]\fP"

.SS "\fBMenu\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Musictworowitemrenderer\&.menu\fC [get]\fP, \fC [set]\fP"

.SS "\fBNavigationendpoint2\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Musictworowitemrenderer\&.navigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBSubtitle\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Musictworowitemrenderer\&.subtitle\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnailoverlay\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Musictworowitemrenderer\&.thumbnailOverlay\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnailrenderer\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Musictworowitemrenderer\&.thumbnailRenderer\fC [get]\fP, \fC [set]\fP"

.SS "\fBTitle\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Musictworowitemrenderer\&.title\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.Musictworowitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
