.TH "YTMusicUploader.Providers.Playlist.Models.WplPlaylist" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.WplPlaylist \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist< WplPlaylistEntry >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBAuthor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBGenerator\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBGuid\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBItemCount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "TimeSpan \fBTotalDuration\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.WplPlaylist\&.Author\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.WplPlaylist\&.Generator\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.WplPlaylist\&.Guid\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.Playlist\&.Models\&.WplPlaylist\&.ItemCount\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.WplPlaylist\&.Title\fC [get]\fP, \fC [set]\fP"

.SS "TimeSpan YTMusicUploader\&.Providers\&.Playlist\&.Models\&.WplPlaylist\&.TotalDuration\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
