.TH "YTMusicUploader.Providers.Playlist.Content" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasePlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBHlsMasterContent\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBHlsMediaContent\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "interface \fBIPlaylistParser\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "interface \fBIPlaylistWriter\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBM3uContent\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBPlaylistParserFactory\fP"
.br
.ti -1c
.RI "class \fBPlaylistToTextHelper\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBPlsContent\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBWplContent\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBZplContent\fP"
.br
.RI "Music playlist library implementation "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPlaylistType\fP { \fBPlaylistType\&.M3U\fP, \fBPlaylistType\&.M3U8\fP, \fBPlaylistType\&.HLSMaster\fP, \fBPlaylistType\&.HlsMedia\fP, \fBPlaylistType\&.PLS\fP, \fBPlaylistType\&.WPL\fP, \fBPlaylistType\&.ZPL\fP }"
.br
.RI "Music playlist library implementation "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.PlaylistType\fP\fC [strong]\fP"

.PP
Music playlist library implementation See https://github.com/tmk907/PlaylistsNET 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIM3U \fP\fP
.TP
\fB\fIM3U8 \fP\fP
.TP
\fB\fIHLSMaster \fP\fP
.TP
\fB\fIHlsMedia \fP\fP
.TP
\fB\fIPLS \fP\fP
.TP
\fB\fIWPL \fP\fP
.TP
\fB\fIZPL \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
