.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Command" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Command
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAddtotoastaction\fP \fBaddToToastAction\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAddtotoastaction\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Command\&.addToToastAction\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Command\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
