.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Buttonrenderer4" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Buttonrenderer4
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBstyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBsize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBText10\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIcon5\fP \fBicon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNavigationendpoint4\fP \fBnavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibility2\fP \fBaccessibility\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibilitydata6\fP \fBaccessibilityData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtargetId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAccessibility2\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.accessibility\fC [get]\fP, \fC [set]\fP"

.SS "\fBAccessibilitydata6\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.accessibilityData\fC [get]\fP, \fC [set]\fP"

.SS "\fBIcon5\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.icon\fC [get]\fP, \fC [set]\fP"

.SS "\fBNavigationendpoint4\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.navigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.size\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.style\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.targetId\fC [get]\fP, \fC [set]\fP"

.SS "\fBText10\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer4\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
