.TH "YTMusicUploader.Providers.Repos.SettingsRepo" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Repos.SettingsRepo \- Application settings database repository access\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.DataAccess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task< \fBSettings\fP > \fBLoad\fP ()"
.br
.RI "Loads the application settings data from the database "
.ti -1c
.RI "async Task< \fBDbOperationResult\fP > \fBUpdate\fP (\fBSettings\fP settings)"
.br
.RI "Updates the application settings data in the database "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Application settings database repository access\&. 


.SH "Member Function Documentation"
.PP 
.SS "async Task<\fBSettings\fP> YTMusicUploader\&.Providers\&.Repos\&.SettingsRepo\&.Load ()"

.PP
Loads the application settings data from the database 
.PP
\fBReturns\fP
.RS 4
Setting model object
.RE
.PP

.SS "async Task<\fBDbOperationResult\fP> YTMusicUploader\&.Providers\&.Repos\&.SettingsRepo\&.Update (\fBSettings\fP settings)"

.PP
Updates the application settings data in the database 
.PP
\fBParameters\fP
.RS 4
\fIsettings\fP Settings model object
.RE
.PP
\fBReturns\fP
.RS 4
\fBDbOperationResult\fP - Showing success or fail, with messages and stats
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
