.TH "YTMusicUploader.Providers.RequestModels.IRequestModel" 3 "Tue Aug 25 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.IRequestModel
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\fP, and \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResult\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
