.TH "YTMusicUploader.Business.MusicBrainz.FileRequestCache" 3 "Mon Aug 24 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.MusicBrainz.FileRequestCache \- Caches requests to \fBMusicBrainz\fP API on disk\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIRequestCache\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileRequestCache\fP ()"
.br
.ti -1c
.RI "\fBFileRequestCache\fP (string path)"
.br
.ti -1c
.RI "async Task \fBAdd\fP (string request, \fBStream\fP response)"
.br
.ti -1c
.RI "Task< bool > \fBTryGetCachedItem\fP (string request, out \fBStream\fP stream)"
.br
.ti -1c
.RI "int \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TimeSpan \fBTimeout\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the timeout for a cache entry to expire\&. "
.in -1c
.SH "Detailed Description"
.PP 
Caches requests to \fBMusicBrainz\fP API on disk\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Business\&.MusicBrainz\&.FileRequestCache\&.FileRequestCache ()"

.SS "YTMusicUploader\&.Business\&.MusicBrainz\&.FileRequestCache\&.FileRequestCache (string path)"

.SH "Member Function Documentation"
.PP 
.SS "async Task YTMusicUploader\&.Business\&.MusicBrainz\&.FileRequestCache\&.Add (string request, \fBStream\fP response)"

.SS "int YTMusicUploader\&.Business\&.MusicBrainz\&.FileRequestCache\&.Cleanup ()"

.SS "void YTMusicUploader\&.Business\&.MusicBrainz\&.FileRequestCache\&.Clear ()"

.SS "Task<bool> YTMusicUploader\&.Business\&.MusicBrainz\&.FileRequestCache\&.TryGetCachedItem (string request, out \fBStream\fP stream)"

.SH "Property Documentation"
.PP 
.SS "TimeSpan YTMusicUploader\&.Business\&.MusicBrainz\&.FileRequestCache\&.Timeout\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the timeout for a cache entry to expire\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
