.TH "YTMusicUploader.Providers.RequestModels.ArtistCache.Alumb" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.ArtistCache.Alumb
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCoverArtUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBEntityId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSongCollection\fP \fBSongs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Alumb\&.CoverArtUrl\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Alumb\&.EntityId\fC [get]\fP, \fC [set]\fP"

.SS "\fBSongCollection\fP YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Alumb\&.Songs\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Alumb\&.Title\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
