.TH "YTMusicUploader.Dialogues.IssueLog" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Dialogues.IssueLog \- Upload Issues Log Dialogue  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOptimisedMetroForm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIssueLog\fP (\fBMainForm\fP mainForm)"
.br
.RI "Form to display upload issues\&. Data fetched from the local database\&. "
.ti -1c
.RI "void \fBPopulate\fP ()"
.br
.RI "Populates the \fBDataGridView\fP control with data\&. "
.ti -1c
.RI "\fBList\fP< \fBMusicFile\fP > \fBSortData\fP (\fBList\fP< \fBMusicFile\fP > list, string column, bool ascending)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Upload Issues Log Dialogue 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Dialogues\&.IssueLog\&.IssueLog (\fBMainForm\fP mainForm)"

.PP
Form to display upload issues\&. Data fetched from the local database\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void YTMusicUploader\&.Dialogues\&.IssueLog\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "void YTMusicUploader\&.Dialogues\&.IssueLog\&.Populate ()"

.PP
Populates the \fBDataGridView\fP control with data\&. 
.SS "\fBList\fP<\fBMusicFile\fP> YTMusicUploader\&.Dialogues\&.IssueLog\&.SortData (\fBList\fP< \fBMusicFile\fP > list, string column, bool ascending)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
