.TH "YTMusicUploader.Providers.Playlist.Models" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasePlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBBasePlaylistEntry\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBHlsMasterPlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBHlsMasterPlaylistEntry\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBHlsMediaPlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBHlsMediaPlaylistEntry\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBHlsPlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBHlsPlaylistEntry\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "interface \fBIBasePlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBM3uPlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBM3uPlaylistEntry\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBPlsPlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBPlsPlaylistEntry\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBWplPlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBWplPlaylistEntry\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBZplPlaylist\fP"
.br
.RI "Music playlist library implementation "
.ti -1c
.RI "class \fBZplPlaylistEntry\fP"
.br
.RI "Music playlist library implementation "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
