.TH "YTMusicUploader.Providers.Playlist.Content.BasePlaylist" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.BasePlaylist \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
