.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistRequestContext" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistRequestContext \- Deserialised HttpWebRequest request body received for a YouTube Music search  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.RequestModels\&.IRequestModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActiveplayers\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBCapabilities\fP"
.br
.ti -1c
.RI "class \fBClicktracking\fP"
.br
.ti -1c
.RI "class \fBClient\fP"
.br
.ti -1c
.RI "class \fBContext\fP"
.br
.ti -1c
.RI "class \fBInternalexperimentflag\fP"
.br
.ti -1c
.RI "class \fBLocationinfo\fP"
.br
.ti -1c
.RI "class \fBMusicappinfo\fP"
.br
.ti -1c
.RI "class \fBRequest\fP"
.br
.ti -1c
.RI "class \fBUser\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBContext\fP \fBcontext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBbrowseId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBrowseendpointcontextsupportedconfigs\fP \fBbrowseEndpointContextSupportedConfigs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Deserialised HttpWebRequest request body received for a YouTube Music search 


.SH "Property Documentation"
.PP 
.SS "\fBBrowseendpointcontextsupportedconfigs\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.browseEndpointContextSupportedConfigs\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.browseId\fC [get]\fP, \fC [set]\fP"

.SS "\fBContext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\&.context\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
