.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Musicresponsivelistitemrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Musicresponsivelistitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBThumbnail\fP \fBthumbnail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBOverlay\fP \fBoverlay\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFlexcolumn\fP[] \fBflexColumns\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFixedcolumn\fP[] \fBfixedColumns\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMenu\fP \fBmenu\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBFixedcolumn\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Musicresponsivelistitemrenderer\&.fixedColumns\fC [get]\fP, \fC [set]\fP"

.SS "\fBFlexcolumn\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Musicresponsivelistitemrenderer\&.flexColumns\fC [get]\fP, \fC [set]\fP"

.SS "\fBMenu\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Musicresponsivelistitemrenderer\&.menu\fC [get]\fP, \fC [set]\fP"

.SS "\fBOverlay\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Musicresponsivelistitemrenderer\&.overlay\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnail\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Musicresponsivelistitemrenderer\&.thumbnail\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Musicresponsivelistitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
