.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContinuationContext" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContinuationContext
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccessibility\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata1\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata2\fP"
.br
.ti -1c
.RI "class \fBAccessibilitypausedata\fP"
.br
.ti -1c
.RI "class \fBAccessibilityplaydata\fP"
.br
.ti -1c
.RI "class \fBAddtoplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBAddtotoastaction\fP"
.br
.ti -1c
.RI "class \fBBackground\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint2\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer1\fP"
.br
.ti -1c
.RI "class \fBCancelbutton\fP"
.br
.ti -1c
.RI "class \fBCommand\fP"
.br
.ti -1c
.RI "class \fBConfirmbutton\fP"
.br
.ti -1c
.RI "class \fBConfirmdialogendpoint\fP"
.br
.ti -1c
.RI "class \fBConfirmdialogrenderer\fP"
.br
.ti -1c
.RI "class \fBContent\fP"
.br
.ti -1c
.RI "class \fBContent1\fP"
.br
.ti -1c
.RI "class \fBContinuation\fP"
.br
.ti -1c
.RI "class \fBContinuationcontents\fP"
.br
.ti -1c
.RI "class \fBDeleteplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBDialogmessage\fP"
.br
.ti -1c
.RI "class \fBGridcontinuation\fP"
.br
.ti -1c
.RI "class \fBIcon\fP"
.br
.ti -1c
.RI "class \fBIcon1\fP"
.br
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBItem1\fP"
.br
.ti -1c
.RI "class \fBItem2\fP"
.br
.ti -1c
.RI "class \fBMenu\fP"
.br
.ti -1c
.RI "class \fBMenunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMenurenderer\fP"
.br
.ti -1c
.RI "class \fBMenuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicitemthumbnailoverlayrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicplaybuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBMusictworowitemrenderer\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint2\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint3\fP"
.br
.ti -1c
.RI "class \fBNextcontinuationdata\fP"
.br
.ti -1c
.RI "class \fBNotificationtextrenderer\fP"
.br
.ti -1c
.RI "class \fBParam\fP"
.br
.ti -1c
.RI "class \fBPauseicon\fP"
.br
.ti -1c
.RI "class \fBPlayicon\fP"
.br
.ti -1c
.RI "class \fBPlayingicon\fP"
.br
.ti -1c
.RI "class \fBPlaylisteditorendpoint\fP"
.br
.ti -1c
.RI "class \fBPlaynavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBQueueaddendpoint\fP"
.br
.ti -1c
.RI "class \fBQueuetarget\fP"
.br
.ti -1c
.RI "class \fBResponsecontext\fP"
.br
.ti -1c
.RI "class \fBRun\fP"
.br
.ti -1c
.RI "class \fBRun1\fP"
.br
.ti -1c
.RI "class \fBRun2\fP"
.br
.ti -1c
.RI "class \fBRun3\fP"
.br
.ti -1c
.RI "class \fBRun4\fP"
.br
.ti -1c
.RI "class \fBRun5\fP"
.br
.ti -1c
.RI "class \fBRun6\fP"
.br
.ti -1c
.RI "class \fBRun7\fP"
.br
.ti -1c
.RI "class \fBRun8\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint1\fP"
.br
.ti -1c
.RI "class \fBServicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBShareentityendpoint\fP"
.br
.ti -1c
.RI "class \fBSubtitle\fP"
.br
.ti -1c
.RI "class \fBSuccessresponsetext\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.ti -1c
.RI "class \fBText1\fP"
.br
.ti -1c
.RI "class \fBText2\fP"
.br
.ti -1c
.RI "class \fBText3\fP"
.br
.ti -1c
.RI "class \fBThumbnail\fP"
.br
.ti -1c
.RI "class \fBThumbnail1\fP"
.br
.ti -1c
.RI "class \fBThumbnailoverlay\fP"
.br
.ti -1c
.RI "class \fBThumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBTitle\fP"
.br
.ti -1c
.RI "class \fBTitle1\fP"
.br
.ti -1c
.RI "class \fBVerticalgradient\fP"
.br
.ti -1c
.RI "class \fBWatchplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBWatchplaylistendpoint1\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBResponsecontext\fP \fBresponseContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContinuationcontents\fP \fBcontinuationContents\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBContinuationcontents\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.continuationContents\fC [get]\fP, \fC [set]\fP"

.SS "\fBResponsecontext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.responseContext\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContinuationContext\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
