.TH "YTMusicUploader.MusicBrainz.API" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCache\fP"
.br
.ti -1c
.RI "namespace \fBEntities\fP"
.br
.ti -1c
.RI "namespace \fBResources\fP"
.br
.ti -1c
.RI "namespace \fBServices\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMusicBrainzClient\fP"
.br
.RI "\fBMusicBrainz\fP client\&. "
.ti -1c
.RI "class \fBQueryParameters\fP"
.br
.RI "Helper for building \fBMusicBrainz\fP query strings\&. "
.ti -1c
.RI "class \fBQueryResult\fP"
.br
.RI "Abstract base class for \fBMusicBrainz\fP queries returning lists (with paging support)\&. "
.ti -1c
.RI "class \fBUrlBuilder\fP"
.br
.RI "Helper class to build \fBMusicBrainz\fP webservice urls\&. "
.ti -1c
.RI "class \fBWebServiceException\fP"
.br
.RI "\fBException\fP containing error information returned by the \fBMusicBrainz\fP webservice\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
