.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Collaborationsettingscommand" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Collaborationsettingscommand
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPlaylisteditorendpoint1\fP \fBplaylistEditorEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Collaborationsettingscommand\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlaylisteditorendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Collaborationsettingscommand\&.playlistEditorEndpoint\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
