.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Accessibilitypausedata" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Accessibilitypausedata
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAccessibilitydata1\fP \fBaccessibilityData\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAccessibilitydata1\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Accessibilitypausedata\&.accessibilityData\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
