.TH "YTMusicUploader.Helpers.FileSystemWatcherPoller.PollDiscoveredChangeArgs" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Helpers.FileSystemWatcherPoller.PollDiscoveredChangeArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPollDiscoveredChangeArgs\fP (string message)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMessage\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.PollDiscoveredChangeArgs\&.PollDiscoveredChangeArgs (string message)"

.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.PollDiscoveredChangeArgs\&.Message\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
