.TH "YTMusicUploader.Providers.RequestModels.DeletePlaylistRequestContext.Capabilities" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.DeletePlaylistRequestContext.Capabilities
.SH SYNOPSIS
.br
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
