.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Tabrenderer" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Tabrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBselected\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContent\fP \fBcontent\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBContent\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Tabrenderer\&.content\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Tabrenderer\&.selected\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Tabrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
