.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Edittitle" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Edittitle
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRun25\fP[] \fBruns\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBRun25\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Edittitle\&.runs\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
