.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Togglebuttonrenderer" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Togglebuttonrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisToggled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisDisabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDefaulticon1\fP \fBdefaultIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDefaulttext1\fP \fBdefaultText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBToggledicon1\fP \fBtoggledIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBToggledtext1\fP \fBtoggledText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBDefaulticon1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglebuttonrenderer\&.defaultIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBDefaulttext1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglebuttonrenderer\&.defaultText\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglebuttonrenderer\&.isDisabled\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglebuttonrenderer\&.isToggled\fC [get]\fP, \fC [set]\fP"

.SS "\fBToggledicon1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglebuttonrenderer\&.toggledIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBToggledtext1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglebuttonrenderer\&.toggledText\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglebuttonrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
