.TH "YTMusicUploader.Providers.Playlist.Models.HlsMasterPlaylist" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.HlsMasterPlaylist \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylist< HlsMasterPlaylistEntry >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHlsMasterPlaylist\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBList\fP< string > \fBMedia\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< string > \fBIFrameStreamInf\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< string > \fBSessionData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< string > \fBSessionKey\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylist\&.HlsMasterPlaylist ()"

.SH "Property Documentation"
.PP 
.SS "\fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylist\&.IFrameStreamInf\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylist\&.Media\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylist\&.SessionData\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylist\&.SessionKey\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
