.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Musicinlinebadgerenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Musicinlinebadgerenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIcon2\fP \fBicon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibilitydata3\fP \fBaccessibilityData\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAccessibilitydata3\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicinlinebadgerenderer\&.accessibilityData\fC [get]\fP, \fC [set]\fP"

.SS "\fBIcon2\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicinlinebadgerenderer\&.icon\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicinlinebadgerenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
