.TH "YTMusicUploader.Providers.Requests.UploadCheckCache.MusicFileCacheObject" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Requests.UploadCheckCache.MusicFileCacheObject
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMusicFilePath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMbId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBReleaseMbId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBEntityId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBResult\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.Requests\&.UploadCheckCache\&.MusicFileCacheObject\&.EntityId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Requests\&.UploadCheckCache\&.MusicFileCacheObject\&.MbId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Requests\&.UploadCheckCache\&.MusicFileCacheObject\&.MusicFilePath\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Requests\&.UploadCheckCache\&.MusicFileCacheObject\&.ReleaseMbId\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.Requests\&.UploadCheckCache\&.MusicFileCacheObject\&.Result\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
