.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Menuserviceitemrenderer" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Menuserviceitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBText\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIcon\fP \fBicon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBServiceendpoint\fP \fBserviceEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBIcon\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Menuserviceitemrenderer\&.icon\fC [get]\fP, \fC [set]\fP"

.SS "\fBServiceendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Menuserviceitemrenderer\&.serviceEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBText\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Menuserviceitemrenderer\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Menuserviceitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
