.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContinuationContext.Navigationendpoint1" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContinuationContext.Navigationendpoint1
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBrowseendpoint\fP \fBbrowseEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBBrowseendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Navigationendpoint1\&.browseEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Navigationendpoint1\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
