.TH "YTMusicUploader.Helpers.FileSystemWatcherPoller" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Helpers.FileSystemWatcherPoller
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileSystemWatcher\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileDataComparer\fP"
.br
.ti -1c
.RI "class \fBPollDiscoveredChangeArgs\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBPollDiscoveredChangeHander\fP (object objects, \fBPollDiscoveredChangeArgs\fP args)"
.br
.ti -1c
.RI "\fBFileSystemWatcherPoller\fP ()"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBPollFrequency\fP = 3600000\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBPollDiscoveredChangeHander\fP \fBOnPollDiscoveredChange\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.FileSystemWatcherPoller ()"

.SH "Member Function Documentation"
.PP 
.SS "delegate void YTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.PollDiscoveredChangeHander (object objects, \fBPollDiscoveredChangeArgs\fP args)"

.SS "void YTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.Start ()"

.SS "void YTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.Stop ()"

.SH "Property Documentation"
.PP 
.SS "int YTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.PollFrequency = 3600000\fC [get]\fP, \fC [set]\fP"

.SH "Event Documentation"
.PP 
.SS "\fBPollDiscoveredChangeHander\fP YTMusicUploader\&.Helpers\&.FileSystemWatcherPoller\&.OnPollDiscoveredChange"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
