.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Dropdownrenderer" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Dropdownrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEntry\fP[] \fBentries\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtargetId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBEntry\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Dropdownrenderer\&.entries\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Dropdownrenderer\&.targetId\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
