.TH "YTMusicUploader.MusicBrainz.API.Entities.Medium" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Medium \- Physical representation of a release\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBTrackCount\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the number of tracks\&. "
.ti -1c
.RI "int \fBPosition\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the position\&. "
.ti -1c
.RI "string \fBFormat\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the format\&. "
.ti -1c
.RI "\fBList\fP< \fBDisc\fP > \fBDiscs\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the disc list\&. "
.ti -1c
.RI "\fBList\fP< \fBTrack\fP > \fBTracks\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the track list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Physical representation of a release\&. 


.SH "Property Documentation"
.PP 
.SS "\fBList\fP<\fBDisc\fP> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Medium\&.Discs\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the disc list\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Medium\&.Format\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the format\&. 
.SS "int YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Medium\&.Position\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the position\&. 
.SS "int YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Medium\&.TrackCount\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the number of tracks\&. 
.SS "\fBList\fP<\fBTrack\fP> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Medium\&.Tracks\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the track list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
