.TH "YTMusicUploader.MusicBrainz.API.Cache" 3 "Sun Nov 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Cache
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileRequestCache\fP"
.br
.RI "Caches requests to \fBMusicBrainz\fP \fBAPI\fP on disk\&. "
.ti -1c
.RI "interface \fBIRequestCache\fP"
.br
.RI "A simple cache interface\&. "
.ti -1c
.RI "class \fBNullCache\fP"
.br
.RI "A cache that does not cache anything\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
