.TH "YTMusicUploader.Providers.Playlist.Utils" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Utils \- Music playlist library implementation (static utilities class)  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBMakeAbsolutePath\fP (string folderPath, string filePath)"
.br
.ti -1c
.RI "static string \fBMakeRelativePath\fP (string folderPath, string fileAbsolutePath)"
.br
.ti -1c
.RI "static bool \fBIsAbsolutePath\fP (string path)"
.br
.ti -1c
.RI "static bool \fBIsRelativePath\fP (string path)"
.br
.ti -1c
.RI "static bool \fBIsStream\fP (string path)"
.br
.ti -1c
.RI "static string \fBUnEscape\fP (string content)"
.br
.ti -1c
.RI "static string \fBEscape\fP (string content)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation (static utilities class) 

See https://github.com/tmk907/PlaylistsNET 
.SH "Member Function Documentation"
.PP 
.SS "static string YTMusicUploader\&.Providers\&.Playlist\&.Utils\&.Escape (string content)\fC [static]\fP"

.SS "static bool YTMusicUploader\&.Providers\&.Playlist\&.Utils\&.IsAbsolutePath (string path)\fC [static]\fP"

.SS "static bool YTMusicUploader\&.Providers\&.Playlist\&.Utils\&.IsRelativePath (string path)\fC [static]\fP"

.SS "static bool YTMusicUploader\&.Providers\&.Playlist\&.Utils\&.IsStream (string path)\fC [static]\fP"

.SS "static string YTMusicUploader\&.Providers\&.Playlist\&.Utils\&.MakeAbsolutePath (string folderPath, string filePath)\fC [static]\fP"

.SS "static string YTMusicUploader\&.Providers\&.Playlist\&.Utils\&.MakeRelativePath (string folderPath, string fileAbsolutePath)\fC [static]\fP"

.SS "static string YTMusicUploader\&.Providers\&.Playlist\&.Utils\&.UnEscape (string content)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
