.TH "YTMusicUploader.Providers.Playlist" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBContent\fP"
.br
.ti -1c
.RI "namespace \fBModels\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlaylistReader\fP"
.br
.RI "For reading music playlist files (\&.m3u, \&.m3u8, \&.wpl, \&.pls, \&.zpl) "
.ti -1c
.RI "class \fBUtils\fP"
.br
.RI "Music playlist library implementation (static utilities class) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
