.TH "YTMusicUploader.MusicBrainz.API.Entities.Relation" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Relation \- Relationships are a way to represent all the different ways in which entities are connected to each other and to URLs outside \fBMusicBrainz\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the relation type\&. "
.ti -1c
.RI "string \fBTypeId\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the relation type ID\&. "
.ti -1c
.RI "string \fBTargetType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the relation target type\&. "
.ti -1c
.RI "string \fBDirection\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the relation direction\&. "
.ti -1c
.RI "string \fBBegin\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the begin date\&. "
.ti -1c
.RI "string \fBEnd\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the end date\&. "
.ti -1c
.RI "bool? \fBEnded\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the relation ended or not\&. "
.ti -1c
.RI "string[] \fBAttributes\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a list of attributes\&. "
.ti -1c
.RI "\fBUrl\fP \fBUrl\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the url relationship (include url-rels)\&. "
.ti -1c
.RI "\fBArtist\fP \fBArtist\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the artist relationship (include artist-rels)\&. "
.ti -1c
.RI "\fBWork\fP \fBWork\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the work relationship (include work-rels)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Relationships are a way to represent all the different ways in which entities are connected to each other and to URLs outside \fBMusicBrainz\fP\&. 


.SH "Property Documentation"
.PP 
.SS "\fBArtist\fP YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.Artist\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the artist relationship (include artist-rels)\&. 
.SS "string [] YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.Attributes\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a list of attributes\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.Begin\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the begin date\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.Direction\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the relation direction\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.End\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the end date\&. 
.SS "bool? YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.Ended\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the relation ended or not\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.TargetType\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the relation target type\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.Type\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the relation type\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.TypeId\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the relation type ID\&. 
.SS "\fBUrl\fP YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.Url\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the url relationship (include url-rels)\&. 
.SS "\fBWork\fP YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Relation\&.Work\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the work relationship (include work-rels)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
