.TH "YTMusicUploader.Business" 3 "Mon Aug 24 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMusicBrainz\fP"
.br
.ti -1c
.RI "namespace \fBPipes\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileScanner\fP"
.br
.RI "Responsive for scanning library music files and adding and managing discovered files to the database\&. "
.ti -1c
.RI "class \fBFileUploader\fP"
.br
.RI "Responsive for managing uploading music files to YouTube Music\&. "
.ti -1c
.RI "class \fBMusicDataFetcher\fP"
.br
.RI "Gets meta data / tag information from the music file itself and looks up any missing data using a \fBMusicBrainz\fP API implementation (for instance album cover art, in which it will lookup CoverArtArchive: https://coverartarchive.org/ "
.ti -1c
.RI "class \fBMusicFileMetaData\fP"
.br
.RI "Custom music file meta tag object "
.ti -1c
.RI "class \fBThrottledStream\fP"
.br
.RI "Throttle a stream -> Very useful for throttle HttpWebRequest uploads / downloads\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
