.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext \- Deserialised HttpWebRequest response body received from YouTube Music after a search  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.RequestModels\&.IRequestModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccessibility\fP"
.br
.ti -1c
.RI "class \fBAccessibility1\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata1\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata2\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata3\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata4\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata5\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata6\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata7\fP"
.br
.ti -1c
.RI "class \fBAccessibilitypausedata\fP"
.br
.ti -1c
.RI "class \fBAccessibilityplaydata\fP"
.br
.ti -1c
.RI "class \fBAddtoplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBAddtotoastaction\fP"
.br
.ti -1c
.RI "class \fBBackground\fP"
.br
.ti -1c
.RI "class \fBBackgroundoverlay\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint2\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint3\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint4\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint5\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint6\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint7\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig3\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig4\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs3\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs4\fP"
.br
.ti -1c
.RI "class \fBCommand\fP"
.br
.ti -1c
.RI "class \fBContent\fP"
.br
.ti -1c
.RI "class \fBContent1\fP"
.br
.ti -1c
.RI "class \fBContent2\fP"
.br
.ti -1c
.RI "class \fBContent3\fP"
.br
.ti -1c
.RI "class \fBContent4\fP"
.br
.ti -1c
.RI "class \fBContent5\fP"
.br
.ti -1c
.RI "class \fBContents\fP"
.br
.ti -1c
.RI "class \fBContinuation\fP"
.br
.ti -1c
.RI "class \fBDefaulticon\fP"
.br
.ti -1c
.RI "class \fBDefaultserviceendpoint\fP"
.br
.ti -1c
.RI "class \fBDefaulttext\fP"
.br
.ti -1c
.RI "class \fBDropdownitemrenderer\fP"
.br
.ti -1c
.RI "class \fBDropdownrenderer\fP"
.br
.ti -1c
.RI "class \fBEndicon\fP"
.br
.ti -1c
.RI "class \fBEnditem\fP"
.br
.ti -1c
.RI "class \fBEndpoint\fP"
.br
.ti -1c
.RI "class \fBEntry\fP"
.br
.ti -1c
.RI "class \fBFlexcolumn\fP"
.br
.ti -1c
.RI "class \fBHeader\fP"
.br
.ti -1c
.RI "class \fBHeader1\fP"
.br
.ti -1c
.RI "class \fBIcon\fP"
.br
.ti -1c
.RI "class \fBIcon1\fP"
.br
.ti -1c
.RI "class \fBIcon2\fP"
.br
.ti -1c
.RI "class \fBIcon3\fP"
.br
.ti -1c
.RI "class \fBIconlinkrenderer\fP"
.br
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBItem1\fP"
.br
.ti -1c
.RI "class \fBItem2\fP"
.br
.ti -1c
.RI "class \fBItemsectionrenderer\fP"
.br
.ti -1c
.RI "class \fBItemsectiontabbedheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBItemsectiontabrenderer\fP"
.br
.ti -1c
.RI "class \fBLabel\fP"
.br
.ti -1c
.RI "class \fBLikeendpoint\fP"
.br
.ti -1c
.RI "class \fBLikeendpoint1\fP"
.br
.ti -1c
.RI "class \fBMenu\fP"
.br
.ti -1c
.RI "class \fBMenu1\fP"
.br
.ti -1c
.RI "class \fBMenunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMenunavigationitemrenderer1\fP"
.br
.ti -1c
.RI "class \fBMenurenderer\fP"
.br
.ti -1c
.RI "class \fBMenurenderer1\fP"
.br
.ti -1c
.RI "class \fBMenuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMusiccarouselshelfbasicheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBMusiccarouselshelfrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicitemthumbnailoverlayrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicplaybuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemflexcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicshelfdividerrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicshelfrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicthumbnailrenderer1\fP"
.br
.ti -1c
.RI "class \fBMusictworowitemrenderer\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint2\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint3\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint4\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint5\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint6\fP"
.br
.ti -1c
.RI "class \fBNextcontinuationdata\fP"
.br
.ti -1c
.RI "class \fBNotificationtextrenderer\fP"
.br
.ti -1c
.RI "class \fBOnselectcommand\fP"
.br
.ti -1c
.RI "class \fBParam\fP"
.br
.ti -1c
.RI "class \fBPauseicon\fP"
.br
.ti -1c
.RI "class \fBPlayicon\fP"
.br
.ti -1c
.RI "class \fBPlayingicon\fP"
.br
.ti -1c
.RI "class \fBPlaynavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBQueueaddendpoint\fP"
.br
.ti -1c
.RI "class \fBQueuetarget\fP"
.br
.ti -1c
.RI "class \fBResponsecontext\fP"
.br
.ti -1c
.RI "class \fBRun\fP"
.br
.ti -1c
.RI "class \fBRun1\fP"
.br
.ti -1c
.RI "class \fBRun10\fP"
.br
.ti -1c
.RI "class \fBRun11\fP"
.br
.ti -1c
.RI "class \fBRun12\fP"
.br
.ti -1c
.RI "class \fBRun2\fP"
.br
.ti -1c
.RI "class \fBRun3\fP"
.br
.ti -1c
.RI "class \fBRun4\fP"
.br
.ti -1c
.RI "class \fBRun5\fP"
.br
.ti -1c
.RI "class \fBRun6\fP"
.br
.ti -1c
.RI "class \fBRun7\fP"
.br
.ti -1c
.RI "class \fBRun8\fP"
.br
.ti -1c
.RI "class \fBRun9\fP"
.br
.ti -1c
.RI "class \fBSectionlistrenderer\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint\fP"
.br
.ti -1c
.RI "class \fBServicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBShareentityendpoint\fP"
.br
.ti -1c
.RI "class \fBShelfdivider\fP"
.br
.ti -1c
.RI "class \fBSinglecolumnbrowseresultsrenderer\fP"
.br
.ti -1c
.RI "class \fBSubtitle\fP"
.br
.ti -1c
.RI "class \fBSuccessresponsetext\fP"
.br
.ti -1c
.RI "class \fBTab\fP"
.br
.ti -1c
.RI "class \fBTab1\fP"
.br
.ti -1c
.RI "class \fBTabrenderer\fP"
.br
.ti -1c
.RI "class \fBTarget\fP"
.br
.ti -1c
.RI "class \fBTarget1\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.ti -1c
.RI "class \fBText1\fP"
.br
.ti -1c
.RI "class \fBText2\fP"
.br
.ti -1c
.RI "class \fBText3\fP"
.br
.ti -1c
.RI "class \fBThumbnail\fP"
.br
.ti -1c
.RI "class \fBThumbnail1\fP"
.br
.ti -1c
.RI "class \fBThumbnail2\fP"
.br
.ti -1c
.RI "class \fBThumbnail3\fP"
.br
.ti -1c
.RI "class \fBThumbnail4\fP"
.br
.ti -1c
.RI "class \fBThumbnailoverlay\fP"
.br
.ti -1c
.RI "class \fBThumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBTitle\fP"
.br
.ti -1c
.RI "class \fBTitle1\fP"
.br
.ti -1c
.RI "class \fBTitle2\fP"
.br
.ti -1c
.RI "class \fBToggledicon\fP"
.br
.ti -1c
.RI "class \fBToggledserviceendpoint\fP"
.br
.ti -1c
.RI "class \fBToggledtext\fP"
.br
.ti -1c
.RI "class \fBTogglemenuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBTooltip\fP"
.br
.ti -1c
.RI "class \fBVerticalgradient\fP"
.br
.ti -1c
.RI "class \fBVerticalgradient1\fP"
.br
.ti -1c
.RI "class \fBWatchendpoint\fP"
.br
.ti -1c
.RI "class \fBWatchendpoint1\fP"
.br
.ti -1c
.RI "class \fBWatchendpoint2\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicconfig\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBWatchplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBWatchplaylistendpoint1\fP"
.br
.ti -1c
.RI "class \fBWatchplaylistendpoint2\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBResponsecontext\fP \fBresponseContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContents\fP \fBcontents\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Deserialised HttpWebRequest response body received from YouTube Music after a search 


.SH "Property Documentation"
.PP 
.SS "\fBContents\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.contents\fC [get]\fP, \fC [set]\fP"

.SS "\fBResponsecontext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.responseContext\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
