.TH "YTMusicUploader.Providers.Repos" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Repos
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMusicFileRepo\fP"
.br
.RI "Music File database repository access\&. "
.ti -1c
.RI "class \fBSettingsRepo\fP"
.br
.RI "Application settings database repository access\&. "
.ti -1c
.RI "class \fBWatchFolderRepo\fP"
.br
.RI "Library watch folders database repository access "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
