.TH "YTMusicUploader.MusicBrainz.API.Entities.Collections.ReleaseList" 3 "Wed Aug 26 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Collections.ReleaseList \- List of releases returned by \fBMusicBrainz\fP search requests\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.MusicBrainz\&.API\&.QueryResult\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBRelease\fP > \fBItems\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the list of artists\&. "
.in -1c
.SH "Detailed Description"
.PP 
List of releases returned by \fBMusicBrainz\fP search requests\&. 


.SH "Property Documentation"
.PP 
.SS "List<\fBRelease\fP> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Collections\&.ReleaseList\&.Items\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the list of artists\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
