.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Dropdownitemrenderer" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Dropdownitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLabel\fP \fBlabel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisSelected\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBOnselectcommand\fP \fBonSelectCommand\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Dropdownitemrenderer\&.isSelected\fC [get]\fP, \fC [set]\fP"

.SS "\fBLabel\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Dropdownitemrenderer\&.label\fC [get]\fP, \fC [set]\fP"

.SS "\fBOnselectcommand\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Dropdownitemrenderer\&.onSelectCommand\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
