.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContinuationContext" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContinuationContext \- Deserialised HttpWebRequest response body received from YouTube Music after a search  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.RequestModels\&.IRequestModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccessibility\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBContent\fP"
.br
.ti -1c
.RI "class \fBContinuation\fP"
.br
.ti -1c
.RI "class \fBContinuationcontents\fP"
.br
.ti -1c
.RI "class \fBFlexcolumn\fP"
.br
.ti -1c
.RI "class \fBIcon\fP"
.br
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBMenu\fP"
.br
.ti -1c
.RI "class \fBMenunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMenurenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemflexcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicshelfcontinuation\fP"
.br
.ti -1c
.RI "class \fBMusicshelfdividerrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBNextcontinuationdata\fP"
.br
.ti -1c
.RI "class \fBParam\fP"
.br
.ti -1c
.RI "class \fBResponsecontext\fP"
.br
.ti -1c
.RI "class \fBRun\fP"
.br
.ti -1c
.RI "class \fBRun1\fP"
.br
.ti -1c
.RI "class \fBServicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBShelfdivider\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.ti -1c
.RI "class \fBText1\fP"
.br
.ti -1c
.RI "class \fBThumbnail\fP"
.br
.ti -1c
.RI "class \fBThumbnail1\fP"
.br
.ti -1c
.RI "class \fBThumbnail2\fP"
.br
.ti -1c
.RI "class \fBWatchplaylistendpoint\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBResponsecontext\fP \fBresponseContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContinuationcontents\fP \fBcontinuationContents\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Deserialised HttpWebRequest response body received from YouTube Music after a search 


.SH "Property Documentation"
.PP 
.SS "\fBContinuationcontents\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.continuationContents\fC [get]\fP, \fC [set]\fP"

.SS "\fBResponsecontext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.responseContext\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
