.TH "YTMusicUploader.Providers.Playlist.PlaylistReader" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.PlaylistReader \- For reading music playlist files (\&.m3u, \&.m3u8, \&.wpl, \&.pls, \&.zpl)  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPlaylistFile\fP \fBReadPlaylistFile\fP (string path)"
.br
.RI "Read a playlist file from a give path and returns a PlaylistFile (Data Model) complete with absolute paths well as reading the meta "
.in -1c
.SH "Detailed Description"
.PP 
For reading music playlist files (\&.m3u, \&.m3u8, \&.wpl, \&.pls, \&.zpl) 

Thanks to: tmk907: https://github.com/tmk907/PlaylistsNET
.SH "Member Function Documentation"
.PP 
.SS "static \fBPlaylistFile\fP YTMusicUploader\&.Providers\&.Playlist\&.PlaylistReader\&.ReadPlaylistFile (string path)\fC [static]\fP"

.PP
Read a playlist file from a give path and returns a PlaylistFile (Data Model) complete with absolute paths well as reading the meta 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP Path to playlist file
.RE
.PP
\fBReturns\fP
.RS 4
PlaylistFile (Data Model)
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
