.TH "YTMusicUploader.Providers.RequestModels.ArtistCache" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.ArtistCache \- Used to store temporary artist details from YouTube Music to be used for lookups  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlbumCollection\fP"
.br
.ti -1c
.RI "class \fBAlbumSongCollection\fP"
.br
.ti -1c
.RI "class \fBAlumb\fP"
.br
.ti -1c
.RI "class \fBArtist\fP"
.br
.ti -1c
.RI "class \fBArtistCollection\fP"
.br
.ti -1c
.RI "class \fBOnlinePlaylist\fP"
.br
.ti -1c
.RI "class \fBOnlinePlaylistCollection\fP"
.br
.ti -1c
.RI "class \fBPlaylistSong\fP"
.br
.ti -1c
.RI "class \fBPlaylistSongCollection\fP"
.br
.ti -1c
.RI "class \fBSong\fP"
.br
.ti -1c
.RI "class \fBSongCollection\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBLastSetTime\fP = DateTime\&.Now\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBArtistCollection\fP \fBArtists\fP = new \fBArtistCollection\fP()\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBOnlinePlaylistCollection\fP \fBPlaylists\fP = new \fBOnlinePlaylistCollection\fP()\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to store temporary artist details from YouTube Music to be used for lookups 


.SH "Property Documentation"
.PP 
.SS "\fBArtistCollection\fP YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Artists = new \fBArtistCollection\fP()\fC [get]\fP, \fC [set]\fP"

.SS "DateTime YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.LastSetTime = DateTime\&.Now\fC [get]\fP, \fC [set]\fP"

.SS "\fBOnlinePlaylistCollection\fP YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Playlists = new \fBOnlinePlaylistCollection\fP()\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
