.TH "YTMusicUploader.Providers.RequestModels.ArtistCache.Artist" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.ArtistCache.Artist
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBArtistName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBBrowseId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAlbumSongCollection\fP \fBAlbumSongCollection\fP = new \fBAlbumSongCollection\fP()\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAlbumSongCollection\fP YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Artist\&.AlbumSongCollection = new \fBAlbumSongCollection\fP()\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Artist\&.ArtistName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Artist\&.BrowseId\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
