.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Buttonrenderer" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Buttonrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBstyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBsize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisDisabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBText1\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCommand\fP \fBcommand\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBCommand\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer\&.command\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer\&.isDisabled\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer\&.size\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer\&.style\fC [get]\fP, \fC [set]\fP"

.SS "\fBText1\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
