.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Nextcontinuationdata" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Nextcontinuationdata
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBcontinuation\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Nextcontinuationdata\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Nextcontinuationdata\&.continuation\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
