.TH "YTMusicUploader.Providers.Playlist.Models.IBasePlaylist" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.IBasePlaylist \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBList\fP< string > \fBGetTracksPaths\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFileName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Member Function Documentation"
.PP 
.SS "\fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.IBasePlaylist\&.GetTracksPaths ()"

.PP
Implemented in \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist< T >\fP\&.
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.IBasePlaylist\&.FileName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.IBasePlaylist\&.Path\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
