.TH "YTMusicUploader.Providers.Playlist.Models.HlsPlaylist< T >" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.HlsPlaylist< T > \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHlsPlaylist\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< string > \fBComments\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAllowCache\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBHlsPlaylistEntry\fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylist\fP< T >\&.\fBHlsPlaylist\fP ()"

.SH "Property Documentation"
.PP 
.SS "string \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylist\fP< T >\&.AllowCache\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<string> \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylist\fP< T >\&.Comments\fC [get]\fP, \fC [set]\fP"

.SS "string \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylist\fP< T >\&.Name\fC [get]\fP, \fC [set]\fP"

.SS "int \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylist\fP< T >\&.Version\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
