.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Musicshelfrenderer" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Musicshelfrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBContent5\fP[] \fBcontents\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContinuation\fP[] \fBcontinuations\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBShelfdivider\fP \fBshelfDivider\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBautoReloadWhenEmpty\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicshelfrenderer\&.autoReloadWhenEmpty\fC [get]\fP, \fC [set]\fP"

.SS "\fBContent5\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicshelfrenderer\&.contents\fC [get]\fP, \fC [set]\fP"

.SS "\fBContinuation\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicshelfrenderer\&.continuations\fC [get]\fP, \fC [set]\fP"

.SS "\fBShelfdivider\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicshelfrenderer\&.shelfDivider\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicshelfrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
