.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Queueaddendpoint1" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Queueaddendpoint1
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBQueuetarget1\fP \fBqueueTarget\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBqueueInsertPosition\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCommand2\fP[] \fBcommands\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBCommand2\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Queueaddendpoint1\&.commands\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Queueaddendpoint1\&.queueInsertPosition\fC [get]\fP, \fC [set]\fP"

.SS "\fBQueuetarget1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Queueaddendpoint1\&.queueTarget\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
