.TH "YTMusicUploader.Providers.DataModels" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.DataModels
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDbModels\fP"
.br
.ti -1c
.RI "interface \fBIDbModel\fP"
.br
.ti -1c
.RI "class \fBLog\fP"
.br
.RI "Information or error log object "
.ti -1c
.RI "class \fBMusicFile\fP"
.br
.RI "Music library file and status "
.ti -1c
.RI "class \fBSettings\fP"
.br
.RI "Application settings data "
.ti -1c
.RI "class \fBWatchFolder\fP"
.br
.RI "Selected libraries to scan and watch data "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
