.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Likeendpoint" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Likeendpoint
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBstatus\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTarget\fP \fBtarget\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAction\fP[] \fBactions\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAction\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Likeendpoint\&.actions\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Likeendpoint\&.status\fC [get]\fP, \fC [set]\fP"

.SS "\fBTarget\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Likeendpoint\&.target\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
