.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Musictworowitemrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Musictworowitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBThumbnailrenderer\fP \fBthumbnailRenderer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBaspectRatio\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTitle1\fP \fBtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSubtitle\fP \fBsubtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNavigationendpoint3\fP \fBnavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMenu\fP \fBmenu\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibilitydata3\fP \fBaccessibilityData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBThumbnailoverlay\fP \fBthumbnailOverlay\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAccessibilitydata3\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.accessibilityData\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.aspectRatio\fC [get]\fP, \fC [set]\fP"

.SS "\fBMenu\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.menu\fC [get]\fP, \fC [set]\fP"

.SS "\fBNavigationendpoint3\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.navigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBSubtitle\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.subtitle\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnailoverlay\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.thumbnailOverlay\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnailrenderer\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.thumbnailRenderer\fC [get]\fP, \fC [set]\fP"

.SS "\fBTitle1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.title\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musictworowitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
