.TH "YTMusicUploader.Dialogues.ApplicationLog" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Dialogues.ApplicationLog \- Application Log (info and error) Dialogue  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOptimisedMetroForm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApplicationLog\fP ()"
.br
.RI "Form to display upload issues\&. Data fetched from the local database\&. "
.ti -1c
.RI "void \fBPopulate\fP ()"
.br
.RI "Populates the \fBDataGridView\fP control with data\&. "
.ti -1c
.RI "\fBList\fP< \fBLog\fP > \fBSortData\fP (\fBList\fP< \fBLog\fP > list, string column, bool ascending)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ToolTip \fBRefreshTooltip\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application Log (info and error) Dialogue 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Dialogues\&.ApplicationLog\&.ApplicationLog ()"

.PP
Form to display upload issues\&. Data fetched from the local database\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void YTMusicUploader\&.Dialogues\&.ApplicationLog\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "void YTMusicUploader\&.Dialogues\&.ApplicationLog\&.Populate ()"

.PP
Populates the \fBDataGridView\fP control with data\&. 
.SS "\fBList\fP<\fBLog\fP> YTMusicUploader\&.Dialogues\&.ApplicationLog\&.SortData (\fBList\fP< \fBLog\fP > list, string column, bool ascending)"

.SH "Property Documentation"
.PP 
.SS "ToolTip YTMusicUploader\&.Dialogues\&.ApplicationLog\&.RefreshTooltip\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
