.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Menunavigationitemrenderer" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Menunavigationitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBText1\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIcon2\fP \fBicon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNavigationendpoint1\fP \fBnavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBIcon2\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Menunavigationitemrenderer\&.icon\fC [get]\fP, \fC [set]\fP"

.SS "\fBNavigationendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Menunavigationitemrenderer\&.navigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBText1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Menunavigationitemrenderer\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Menunavigationitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
