.TH "YTMusicUploader.Providers.Playlist.Models.HlsMasterPlaylistEntry" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.HlsMasterPlaylistEntry \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylistEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHlsMasterPlaylistEntry\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int? \fBProgramId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBBandwidth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int? \fBAverageBandwidth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< string > \fBCodecs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBResolution\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double? \fBFrameRate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBHdcpLevel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAudio\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBVideo\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSubtitles\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBClosedCaptions\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.HlsMasterPlaylistEntry ()"

.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.Audio\fC [get]\fP, \fC [set]\fP"

.SS "int? YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.AverageBandwidth\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.Bandwidth\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.ClosedCaptions\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.Codecs\fC [get]\fP, \fC [set]\fP"

.SS "double? YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.FrameRate\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.HdcpLevel\fC [get]\fP, \fC [set]\fP"

.SS "int? YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.ProgramId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.Resolution\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.Subtitles\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMasterPlaylistEntry\&.Video\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
