.TH "YTMusicUploader.Providers.RequestModels.CreatePlaylistRequestContext.Client" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.CreatePlaylistRequestContext.Client
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclientName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBclientVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBhl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBgl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "object[] \fBexperimentIds\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBexperimentsToken\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBbrowserName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBbrowserVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBosName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBosVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBplatform\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fButcOffsetMinutes\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBLocationinfo\fP \fBlocationInfo\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMusicappinfo\fP \fBmusicAppInfo\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.browserName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.browserVersion\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.clientName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.clientVersion\fC [get]\fP, \fC [set]\fP"

.SS "object [] YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.experimentIds\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.experimentsToken\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.gl\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.hl\fC [get]\fP, \fC [set]\fP"

.SS "\fBLocationinfo\fP YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.locationInfo\fC [get]\fP, \fC [set]\fP"

.SS "\fBMusicappinfo\fP YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.musicAppInfo\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.osName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.osVersion\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.platform\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.CreatePlaylistRequestContext\&.Client\&.utcOffsetMinutes\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
