.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Background" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Background
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBVerticalgradient\fP \fBverticalGradient\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBVerticalgradient\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Background\&.verticalGradient\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
