.TH "YTMusicUploader.MusicBrainz.API.Services" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Services
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArtistService\fP"
.br
.ti -1c
.RI "interface \fBIArtistService\fP"
.br
.RI "Interface defining the artist service\&. "
.ti -1c
.RI "interface \fBIRecordingService\fP"
.br
.RI "Interface defining the recording service\&. "
.ti -1c
.RI "interface \fBIReleaseGroupService\fP"
.br
.RI "Interface defining the release-group service\&. "
.ti -1c
.RI "interface \fBIReleaseService\fP"
.br
.RI "Interface defining the release service\&. "
.ti -1c
.RI "interface \fBIWorkService\fP"
.br
.ti -1c
.RI "class \fBRecordingService\fP"
.br
.ti -1c
.RI "class \fBReleaseGroupService\fP"
.br
.ti -1c
.RI "class \fBReleaseService\fP"
.br
.ti -1c
.RI "class \fBWorkService\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
