.TH "YTMusicUploader.Business.MusicDataFetcher.TrackAndReleaseMbId" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.MusicDataFetcher.TrackAndReleaseMbId
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMbId\fP = string\&.Empty\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBReleaseMbId\fP = string\&.Empty\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Business\&.MusicDataFetcher\&.TrackAndReleaseMbId\&.MbId = string\&.Empty\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Business\&.MusicDataFetcher\&.TrackAndReleaseMbId\&.ReleaseMbId = string\&.Empty\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
