.TH "YTMusicUploader.Business.EdgeDependencyChecker" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.EdgeDependencyChecker \- Used for checking Edge Core file dependencies  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBCheckEdgeCoreFilesArePresentAndCorrect\fP ()"
.br
.RI "Check all the required Edge Core files are present and are the right byte site (i\&.e\&. have copied over successfully) "
.in -1c
.SH "Detailed Description"
.PP 
Used for checking Edge Core file dependencies 


.SH "Member Function Documentation"
.PP 
.SS "static bool YTMusicUploader\&.Business\&.EdgeDependencyChecker\&.CheckEdgeCoreFilesArePresentAndCorrect ()\fC [static]\fP"

.PP
Check all the required Edge Core files are present and are the right byte site (i\&.e\&. have copied over successfully) 
.PP
\fBReturns\fP
.RS 4
True is valid, false otherwise
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
