.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Watchplaylistendpoint1" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Watchplaylistendpoint1
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBplaylistId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fB_params\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchplaylistendpoint1\&._params\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Watchplaylistendpoint1\&.playlistId\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
