.TH "YTMusicUploader.Providers" 3 "Sun Aug 23 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBModels\fP"
.br
.ti -1c
.RI "namespace \fBRepos\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataAccess\fP"
.br
.RI "Abastract database repository access class\&. "
.ti -1c
.RI "class \fBDbOperationResult\fP"
.br
.RI "Database process execution and query result object\&. Contains if there's any errors and the time taken to perform the database operation\&. "
.ti -1c
.RI "class \fBRequests\fP"
.br
.RI "HttpWebRequest POST request to send to YouTube to check if the user's is authenticated (signed in) by determining if a generic request is successful given the current authentication cookie value we have stored\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
