.TH "YTMusicUploader.Providers.RequestModels.DeletePlaylistRequestContext" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.DeletePlaylistRequestContext \- Deserialised HttpWebRequest request body sent for deleting a playlist  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActiveplayers\fP"
.br
.ti -1c
.RI "class \fBCapabilities\fP"
.br
.ti -1c
.RI "class \fBClicktracking\fP"
.br
.ti -1c
.RI "class \fBClient\fP"
.br
.ti -1c
.RI "class \fBContext\fP"
.br
.ti -1c
.RI "class \fBInternalexperimentflag\fP"
.br
.ti -1c
.RI "class \fBLocationinfo\fP"
.br
.ti -1c
.RI "class \fBMusicappinfo\fP"
.br
.ti -1c
.RI "class \fBRequest\fP"
.br
.ti -1c
.RI "class \fBUser\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBContext\fP \fBcontext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBplaylistId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Deserialised HttpWebRequest request body sent for deleting a playlist 


.SH "Property Documentation"
.PP 
.SS "\fBContext\fP YTMusicUploader\&.Providers\&.RequestModels\&.DeletePlaylistRequestContext\&.context\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.DeletePlaylistRequestContext\&.playlistId\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
