.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Musicitemthumbnailoverlayrenderer" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Musicitemthumbnailoverlayrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBackground\fP \fBbackground\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContent3\fP \fBcontent\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBcontentPosition\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBdisplayStyle\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBBackground\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Musicitemthumbnailoverlayrenderer\&.background\fC [get]\fP, \fC [set]\fP"

.SS "\fBContent3\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Musicitemthumbnailoverlayrenderer\&.content\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Musicitemthumbnailoverlayrenderer\&.contentPosition\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Musicitemthumbnailoverlayrenderer\&.displayStyle\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
