.TH "YTMusicUploader.Providers.Playlist.Models.PlsPlaylistEntry" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.PlsPlaylistEntry \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylistEntry\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "TimeSpan \fBLength\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNr\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Property Documentation"
.PP 
.SS "TimeSpan YTMusicUploader\&.Providers\&.Playlist\&.Models\&.PlsPlaylistEntry\&.Length\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.Playlist\&.Models\&.PlsPlaylistEntry\&.Nr\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.PlsPlaylistEntry\&.Title\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
