.TH "YTMusicUploader.Business.Pipes.DataReceivedEventArgs" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.Pipes.DataReceivedEventArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataReceivedEventArgs\fP (string data)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Business\&.Pipes\&.DataReceivedEventArgs\&.DataReceivedEventArgs (string data)"

.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Business\&.Pipes\&.DataReceivedEventArgs\&.Data\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
