.TH "YTMusicUploader.Business.Pipes.IIpcServer" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.Pipes.IIpcServer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIDisposable\fP\&.
.PP
Inherited by YTMusicUploader\&.Business\&.Pipes\&.WcfServer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBDataReceivedEventArgs\fP > \fBReceived\fP"
.br
.ti -1c
.RI "EventHandler< \fBEventArgs\fP > \fBFaulted\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void YTMusicUploader\&.Business\&.Pipes\&.IIpcServer\&.Start ()"

.SS "void YTMusicUploader\&.Business\&.Pipes\&.IIpcServer\&.Stop ()"

.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBEventArgs\fP> YTMusicUploader\&.Business\&.Pipes\&.IIpcServer\&.Faulted"

.SS "EventHandler<\fBDataReceivedEventArgs\fP> YTMusicUploader\&.Business\&.Pipes\&.IIpcServer\&.Received"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
