.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Likebuttonrenderer" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Likebuttonrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTarget\fP \fBtarget\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBlikeStatus\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBlikesAllowed\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBServiceendpoint1\fP[] \fBserviceEndpoints\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Likebuttonrenderer\&.likesAllowed\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Likebuttonrenderer\&.likeStatus\fC [get]\fP, \fC [set]\fP"

.SS "\fBServiceendpoint1\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Likebuttonrenderer\&.serviceEndpoints\fC [get]\fP, \fC [set]\fP"

.SS "\fBTarget\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Likebuttonrenderer\&.target\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Likebuttonrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
