.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContinuationContext.Musicthumbnailrenderer" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContinuationContext.Musicthumbnailrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBThumbnail1\fP \fBthumbnail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBthumbnailCrop\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBthumbnailScale\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBThumbnail1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicthumbnailrenderer\&.thumbnail\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicthumbnailrenderer\&.thumbnailCrop\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicthumbnailrenderer\&.thumbnailScale\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Musicthumbnailrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
