.TH "YTMusicUploader.Providers.Playlist.Content.HlsMasterContent" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.HlsMasterContent \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistParser< HlsMasterPlaylist >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHlsMasterPlaylist\fP \fBGetFromStream\fP (Stream stream)"
.br
.ti -1c
.RI "\fBHlsMasterPlaylist\fP \fBGetFromString\fP (string playlistString)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Member Function Documentation"
.PP 
.SS "\fBHlsMasterPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.HlsMasterContent\&.GetFromStream (Stream stream)"

.SS "\fBHlsMasterPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.HlsMasterContent\&.GetFromString (string playlistString)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
