.TH "YTMusicUploader.Providers.RequestModels.ArtistCache.OnlinePlaylistCollection" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.ArtistCache.OnlinePlaylistCollection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBList< OnlinePlaylist >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRemovePlayistItem\fP (string playlistEntityId, string trackVideoId)"
.br
.ti -1c
.RI "void \fBRemovePlaylist\fP (string playlistEntityId)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylistCollection\&.RemovePlayistItem (string playlistEntityId, string trackVideoId)"

.SS "void YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylistCollection\&.RemovePlaylist (string playlistEntityId)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
