.TH "YTMusicUploader.MusicBrainz.API.Entities.Disc" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Disc
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the \fBMusicBrainz\fP id\&. "
.ti -1c
.RI "int \fBSectors\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the number of sectors\&. "
.ti -1c
.RI "\fBList\fP< int > \fBOffsets\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the track offsets\&. "
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Disc\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the \fBMusicBrainz\fP id\&. 
.SS "\fBList\fP<int> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Disc\&.Offsets\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the track offsets\&. 
.SS "int YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Disc\&.Sectors\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the number of sectors\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
