.TH "YTMusicUploader.Providers.RequestModels.ArtistCache" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.ArtistCache \- Used to store temporary artist details from YouTube Music to be used for lookups  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArtist\fP"
.br
.ti -1c
.RI "class \fBSong\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBLastSetTime\fP = DateTime\&.Now\fC [get, set]\fP"
.br
.ti -1c
.RI "List< \fBArtist\fP > \fBArtists\fP = new List<\fBArtist\fP>()\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to store temporary artist details from YouTube Music to be used for lookups 


.SH "Property Documentation"
.PP 
.SS "List<\fBArtist\fP> YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.Artists = new List<\fBArtist\fP>()\fC [get]\fP, \fC [set]\fP"

.SS "DateTime YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.LastSetTime = DateTime\&.Now\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
