.TH "YTMusicUploader.MusicBrainz.API.Entities.Url" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Url \- A URL in \fBMusicBrainz\fP is a specific entity representing a regular internet Uniform Resource Locator\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the id\&. "
.ti -1c
.RI "string \fBResource\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the resource\&. "
.in -1c
.SH "Detailed Description"
.PP 
A URL in \fBMusicBrainz\fP is a specific entity representing a regular internet Uniform Resource Locator\&. 


.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Url\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the id\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Url\&.Resource\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the resource\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
