.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Navigationendpoint" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Navigationendpoint
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAddtoplaylistendpoint\fP \fBaddToPlaylistEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBrowseendpoint\fP \fBbrowseEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBConfirmdialogendpoint\fP \fBconfirmDialogEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAddtoplaylistendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Navigationendpoint\&.addToPlaylistEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBBrowseendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Navigationendpoint\&.browseEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Navigationendpoint\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "\fBConfirmdialogendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Navigationendpoint\&.confirmDialogEndpoint\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
