.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Target" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Target
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBvideoId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Target\&.videoId\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
