.TH "YTMusicUploader.Providers.RequestModels.ArtistCache.PlaylistSongCollection" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.ArtistCache.PlaylistSongCollection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBList< PlaylistSong >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
