.TH "YTMusicUploader.Helpers.SystemInfo" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Helpers.SystemInfo \- Basic system info - To determine multi-threading settings to minimise resource hogging  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCpuCores\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic system info - To determine multi-threading settings to minimise resource hogging 


.SH "Property Documentation"
.PP 
.SS "int YTMusicUploader\&.Helpers\&.SystemInfo\&.CpuCores\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
