.TH "YTMusicUploader.Business" 3 "Sun Aug 23 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileScanner\fP"
.br
.RI "Responsive for scanning library music files and adding and managing discovered files to the database\&. "
.ti -1c
.RI "class \fBFileUploader\fP"
.br
.RI "Responsive for managing uploading music files to YouTube Music\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
