.TH "YTMusicUploader.Dialogues.UploadLog" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Dialogues.UploadLog \- Form to display upload successes\&. Data fetched from the local database\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOptimisedMetroForm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUploadLog\fP (\fBMainForm\fP mainForm)"
.br
.RI "Form to display upload successes\&. Data fetched from the local database\&. "
.ti -1c
.RI "void \fBPopulate\fP ()"
.br
.RI "Populates the \fBDataGridView\fP control with data\&. "
.ti -1c
.RI "List< \fBMusicFile\fP > \fBSortData\fP (List< \fBMusicFile\fP > list, string column, bool ascending)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Form to display upload successes\&. Data fetched from the local database\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Dialogues\&.UploadLog\&.UploadLog (\fBMainForm\fP mainForm)"

.PP
Form to display upload successes\&. Data fetched from the local database\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void YTMusicUploader\&.Dialogues\&.UploadLog\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "void YTMusicUploader\&.Dialogues\&.UploadLog\&.Populate ()"

.PP
Populates the \fBDataGridView\fP control with data\&. 
.SS "List<\fBMusicFile\fP> YTMusicUploader\&.Dialogues\&.UploadLog\&.SortData (List< \fBMusicFile\fP > list, string column, bool ascending)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
