.TH "YTMusicUploader.Dialogues.ConnectToYTMusic" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Dialogues.ConnectToYTMusic \- Shows a WebView2 control https://docs.microsoft.com/en-us/microsoft-edge/webview2/  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOptimisedMetroForm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectToYTMusic\fP (\fBMainForm\fP mainForm)"
.br
.RI "Shows a WebView2 control https://docs.microsoft.com/en-us/microsoft-edge/webview2/ "
.ti -1c
.RI "void \fBCloseForm\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "WebView2 \fBBrowserControl\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Shows a WebView2 control https://docs.microsoft.com/en-us/microsoft-edge/webview2/ 

Seems to be the only browser control I've found that will actually display YouTube music\&. This control is used purely so users can sign into YouTube and automatically grab the authentication cookie that lets you upload music to\&.
.PP
DEPENDENCY: Microsoft Edge (Canary Channel) required\&. It's been packed with the installer for convienience\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Dialogues\&.ConnectToYTMusic\&.ConnectToYTMusic (\fBMainForm\fP mainForm)"

.PP
Shows a WebView2 control https://docs.microsoft.com/en-us/microsoft-edge/webview2/ Seems to be the only browser control I've found that will actually display YouTube music\&. This control is used purely so users can sign into YouTube and automatically grab the authentication cookie that lets you upload music to\&.
.PP
DEPENDENCY: Microsoft Edge (Canary Channel) required\&. It's been packed with the installer for convienience\&.
.SH "Member Function Documentation"
.PP 
.SS "void YTMusicUploader\&.Dialogues\&.ConnectToYTMusic\&.CloseForm ()"

.SS "override void YTMusicUploader\&.Dialogues\&.ConnectToYTMusic\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "WebView2 YTMusicUploader\&.Dialogues\&.ConnectToYTMusic\&.BrowserControl\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
