.TH "YTMusicUploader.Providers.RequestModels.ArtistCache.OnlinePlaylist" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.ArtistCache.OnlinePlaylist
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPrivacyStatusEmum\fP { \fBPrivacyStatusEmum\&.Private\fP, \fBPrivacyStatusEmum\&.Public\fP, \fBPrivacyStatusEmum\&.Unlisted\fP }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBBrowseId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSubtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCoverArtUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDuration\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPrivacyStatusEmum\fP? \fBPrivacyStatus\fP = null\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPlaylistSongCollection\fP \fBSongs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBYTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.PrivacyStatusEmum\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPrivate \fP\fP
.TP
\fB\fIPublic \fP\fP
.TP
\fB\fIUnlisted \fP\fP
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.BrowseId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.CoverArtUrl\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.Description\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.Duration\fC [get]\fP, \fC [set]\fP"

.SS "\fBPrivacyStatusEmum\fP? YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.PrivacyStatus = null\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlaylistSongCollection\fP YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.Songs\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.Subtitle\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.OnlinePlaylist\&.Title\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
