.TH "YTMusicUploader.Dialogues.ManageYTMusic" 3 "Sun Nov 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Dialogues.ManageYTMusic \- Dialogue Form to delete song / albums from YT Music  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOptimisedMetroForm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBManageYTMusic\fP (\fBMainForm\fP mainForm)"
.br
.RI "Form to manage (see and delete) music currently uploaded to YouTube music "
.ti -1c
.RI "void \fBChangeCount\fP (TreeNode node)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Dialogue Form to delete song / albums from YT Music 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Dialogues\&.ManageYTMusic\&.ManageYTMusic (\fBMainForm\fP mainForm)"

.PP
Form to manage (see and delete) music currently uploaded to YouTube music 
.SH "Member Function Documentation"
.PP 
.SS "void YTMusicUploader\&.Dialogues\&.ManageYTMusic\&.ChangeCount (TreeNode node)"

.SS "override void YTMusicUploader\&.Dialogues\&.ManageYTMusic\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
