.TH "YTMusicUploader.Providers.RequestModels.MusicManageTreeNodeModel" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.MusicManageTreeNodeModel
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBNodeTypeEnum\fP { \fBNodeTypeEnum\&.Root\fP, \fBNodeTypeEnum\&.Artist\fP, \fBNodeTypeEnum\&.Album\fP, \fBNodeTypeEnum\&.Song\fP }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBNodeTypeEnum\fP \fBNodeType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBArtistTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAlbumTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSongTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDuration\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUploaded\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDatabaseExistence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBEntityOrBrowseId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMbId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCovertArtUrl\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBYTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.NodeTypeEnum\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRoot \fP\fP
.TP
\fB\fIArtist \fP\fP
.TP
\fB\fIAlbum \fP\fP
.TP
\fB\fISong \fP\fP
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.AlbumTitle\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.ArtistTitle\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.CovertArtUrl\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.DatabaseExistence\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.Duration\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.EntityOrBrowseId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.MbId\fC [get]\fP, \fC [set]\fP"

.SS "\fBNodeTypeEnum\fP YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.NodeType\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.SongTitle\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.MusicManageTreeNodeModel\&.Uploaded\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
