.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.RequestModels\&.IRequestModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccessibility\fP"
.br
.ti -1c
.RI "class \fBAccessibility1\fP"
.br
.ti -1c
.RI "class \fBAccessibility2\fP"
.br
.ti -1c
.RI "class \fBAccessibility3\fP"
.br
.ti -1c
.RI "class \fBAccessibility4\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata1\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata2\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata3\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata4\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata5\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata6\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata7\fP"
.br
.ti -1c
.RI "class \fBAccessibilitypausedata\fP"
.br
.ti -1c
.RI "class \fBAccessibilityplaydata\fP"
.br
.ti -1c
.RI "class \fBAction\fP"
.br
.ti -1c
.RI "class \fBAction1\fP"
.br
.ti -1c
.RI "class \fBAddtoplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBAddtoplaylistendpoint1\fP"
.br
.ti -1c
.RI "class \fBAddtotoastaction\fP"
.br
.ti -1c
.RI "class \fBAddtotoastaction1\fP"
.br
.ti -1c
.RI "class \fBBackground\fP"
.br
.ti -1c
.RI "class \fBBadge\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint2\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer1\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer2\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer3\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer4\fP"
.br
.ti -1c
.RI "class \fBCancelbutton\fP"
.br
.ti -1c
.RI "class \fBCancelbutton1\fP"
.br
.ti -1c
.RI "class \fBCollaborationsettingscommand\fP"
.br
.ti -1c
.RI "class \fBCommand\fP"
.br
.ti -1c
.RI "class \fBCommand1\fP"
.br
.ti -1c
.RI "class \fBCommand2\fP"
.br
.ti -1c
.RI "class \fBConfirmbutton\fP"
.br
.ti -1c
.RI "class \fBConfirmbutton1\fP"
.br
.ti -1c
.RI "class \fBConfirmdialogendpoint\fP"
.br
.ti -1c
.RI "class \fBConfirmdialogendpoint1\fP"
.br
.ti -1c
.RI "class \fBConfirmdialogrenderer\fP"
.br
.ti -1c
.RI "class \fBConfirmdialogrenderer1\fP"
.br
.ti -1c
.RI "class \fBContent\fP"
.br
.ti -1c
.RI "class \fBContent1\fP"
.br
.ti -1c
.RI "class \fBContent2\fP"
.br
.ti -1c
.RI "class \fBContent3\fP"
.br
.ti -1c
.RI "class \fBContent4\fP"
.br
.ti -1c
.RI "class \fBContent5\fP"
.br
.ti -1c
.RI "class \fBContents\fP"
.br
.ti -1c
.RI "class \fBContinuation\fP"
.br
.ti -1c
.RI "class \fBCroppedsquarethumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBDefaulticon\fP"
.br
.ti -1c
.RI "class \fBDefaulticon1\fP"
.br
.ti -1c
.RI "class \fBDefaultserviceendpoint\fP"
.br
.ti -1c
.RI "class \fBDefaulttext\fP"
.br
.ti -1c
.RI "class \fBDefaulttext1\fP"
.br
.ti -1c
.RI "class \fBDeleteplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBDescription\fP"
.br
.ti -1c
.RI "class \fBDescriptiontext\fP"
.br
.ti -1c
.RI "class \fBDialogmessage\fP"
.br
.ti -1c
.RI "class \fBDialogmessage1\fP"
.br
.ti -1c
.RI "class \fBDropdownitemrenderer\fP"
.br
.ti -1c
.RI "class \fBDropdownrenderer\fP"
.br
.ti -1c
.RI "class \fBEditdescription\fP"
.br
.ti -1c
.RI "class \fBEditheader\fP"
.br
.ti -1c
.RI "class \fBEdittitle\fP"
.br
.ti -1c
.RI "class \fBEntry\fP"
.br
.ti -1c
.RI "class \fBFeedbackendpoint\fP"
.br
.ti -1c
.RI "class \fBFeedbackendpoint1\fP"
.br
.ti -1c
.RI "class \fBFixedcolumn\fP"
.br
.ti -1c
.RI "class \fBFlexcolumn\fP"
.br
.ti -1c
.RI "class \fBHeader\fP"
.br
.ti -1c
.RI "class \fBHeader1\fP"
.br
.ti -1c
.RI "class \fBIcon\fP"
.br
.ti -1c
.RI "class \fBIcon1\fP"
.br
.ti -1c
.RI "class \fBIcon2\fP"
.br
.ti -1c
.RI "class \fBIcon3\fP"
.br
.ti -1c
.RI "class \fBIcon4\fP"
.br
.ti -1c
.RI "class \fBIcon5\fP"
.br
.ti -1c
.RI "class \fBIcon6\fP"
.br
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBItem1\fP"
.br
.ti -1c
.RI "class \fBItem2\fP"
.br
.ti -1c
.RI "class \fBItem3\fP"
.br
.ti -1c
.RI "class \fBLabel\fP"
.br
.ti -1c
.RI "class \fBLikebuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBLikeendpoint\fP"
.br
.ti -1c
.RI "class \fBMenu\fP"
.br
.ti -1c
.RI "class \fBMenu1\fP"
.br
.ti -1c
.RI "class \fBMenunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMenunavigationitemrenderer1\fP"
.br
.ti -1c
.RI "class \fBMenurenderer\fP"
.br
.ti -1c
.RI "class \fBMenurenderer1\fP"
.br
.ti -1c
.RI "class \fBMenuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMenuserviceitemrenderer1\fP"
.br
.ti -1c
.RI "class \fBMorebutton\fP"
.br
.ti -1c
.RI "class \fBMusicdeleteprivatelyownedentitycommand\fP"
.br
.ti -1c
.RI "class \fBMusicdetailheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBMusiceditableplaylistdetailheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicinlinebadgerenderer\fP"
.br
.ti -1c
.RI "class \fBMusicitemthumbnailoverlayrenderer\fP"
.br
.ti -1c
.RI "class \fBMusiclibrarystatusupdatecommand\fP"
.br
.ti -1c
.RI "class \fBMusicplaybuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicplaylisteditheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicplaylistshelfrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemfixedcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemflexcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint2\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint3\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint4\fP"
.br
.ti -1c
.RI "class \fBNextcontinuationdata\fP"
.br
.ti -1c
.RI "class \fBNotificationtextrenderer\fP"
.br
.ti -1c
.RI "class \fBNotificationtextrenderer1\fP"
.br
.ti -1c
.RI "class \fBOverlay\fP"
.br
.ti -1c
.RI "class \fBParam\fP"
.br
.ti -1c
.RI "class \fBPauseicon\fP"
.br
.ti -1c
.RI "class \fBPlayicon\fP"
.br
.ti -1c
.RI "class \fBPlayingicon\fP"
.br
.ti -1c
.RI "class \fBPlaylisteditendpoint\fP"
.br
.ti -1c
.RI "class \fBPlaylisteditorendpoint\fP"
.br
.ti -1c
.RI "class \fBPlaylisteditorendpoint1\fP"
.br
.ti -1c
.RI "class \fBPlaylistitemdata\fP"
.br
.ti -1c
.RI "class \fBPlaynavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBPrivacydropdown\fP"
.br
.ti -1c
.RI "class \fBQueueaddendpoint\fP"
.br
.ti -1c
.RI "class \fBQueueaddendpoint1\fP"
.br
.ti -1c
.RI "class \fBQueuetarget\fP"
.br
.ti -1c
.RI "class \fBQueuetarget1\fP"
.br
.ti -1c
.RI "class \fBResponsecontext\fP"
.br
.ti -1c
.RI "class \fBRun\fP"
.br
.ti -1c
.RI "class \fBRun1\fP"
.br
.ti -1c
.RI "class \fBRun10\fP"
.br
.ti -1c
.RI "class \fBRun11\fP"
.br
.ti -1c
.RI "class \fBRun12\fP"
.br
.ti -1c
.RI "class \fBRun13\fP"
.br
.ti -1c
.RI "class \fBRun14\fP"
.br
.ti -1c
.RI "class \fBRun15\fP"
.br
.ti -1c
.RI "class \fBRun16\fP"
.br
.ti -1c
.RI "class \fBRun17\fP"
.br
.ti -1c
.RI "class \fBRun18\fP"
.br
.ti -1c
.RI "class \fBRun19\fP"
.br
.ti -1c
.RI "class \fBRun2\fP"
.br
.ti -1c
.RI "class \fBRun20\fP"
.br
.ti -1c
.RI "class \fBRun21\fP"
.br
.ti -1c
.RI "class \fBRun22\fP"
.br
.ti -1c
.RI "class \fBRun23\fP"
.br
.ti -1c
.RI "class \fBRun24\fP"
.br
.ti -1c
.RI "class \fBRun25\fP"
.br
.ti -1c
.RI "class \fBRun26\fP"
.br
.ti -1c
.RI "class \fBRun27\fP"
.br
.ti -1c
.RI "class \fBRun28\fP"
.br
.ti -1c
.RI "class \fBRun3\fP"
.br
.ti -1c
.RI "class \fBRun4\fP"
.br
.ti -1c
.RI "class \fBRun5\fP"
.br
.ti -1c
.RI "class \fBRun6\fP"
.br
.ti -1c
.RI "class \fBRun7\fP"
.br
.ti -1c
.RI "class \fBRun8\fP"
.br
.ti -1c
.RI "class \fBRun9\fP"
.br
.ti -1c
.RI "class \fBSecondsubtitle\fP"
.br
.ti -1c
.RI "class \fBSectionlistrenderer\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint1\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint2\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint3\fP"
.br
.ti -1c
.RI "class \fBServicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBShareentityendpoint\fP"
.br
.ti -1c
.RI "class \fBShareentityendpoint1\fP"
.br
.ti -1c
.RI "class \fBSinglecolumnbrowseresultsrenderer\fP"
.br
.ti -1c
.RI "class \fBSubtitle\fP"
.br
.ti -1c
.RI "class \fBSuccessresponsetext\fP"
.br
.ti -1c
.RI "class \fBSuccessresponsetext1\fP"
.br
.ti -1c
.RI "class \fBTab\fP"
.br
.ti -1c
.RI "class \fBTabrenderer\fP"
.br
.ti -1c
.RI "class \fBTarget\fP"
.br
.ti -1c
.RI "class \fBTarget1\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.ti -1c
.RI "class \fBText1\fP"
.br
.ti -1c
.RI "class \fBText10\fP"
.br
.ti -1c
.RI "class \fBText2\fP"
.br
.ti -1c
.RI "class \fBText3\fP"
.br
.ti -1c
.RI "class \fBText4\fP"
.br
.ti -1c
.RI "class \fBText5\fP"
.br
.ti -1c
.RI "class \fBText6\fP"
.br
.ti -1c
.RI "class \fBText7\fP"
.br
.ti -1c
.RI "class \fBText8\fP"
.br
.ti -1c
.RI "class \fBText9\fP"
.br
.ti -1c
.RI "class \fBThumbnail\fP"
.br
.ti -1c
.RI "class \fBThumbnail1\fP"
.br
.ti -1c
.RI "class \fBThumbnail2\fP"
.br
.ti -1c
.RI "class \fBThumbnail3\fP"
.br
.ti -1c
.RI "class \fBThumbnail4\fP"
.br
.ti -1c
.RI "class \fBThumbnail5\fP"
.br
.ti -1c
.RI "class \fBTitle\fP"
.br
.ti -1c
.RI "class \fBTitle1\fP"
.br
.ti -1c
.RI "class \fBTitle2\fP"
.br
.ti -1c
.RI "class \fBTitle3\fP"
.br
.ti -1c
.RI "class \fBTogglebuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBToggledicon\fP"
.br
.ti -1c
.RI "class \fBToggledicon1\fP"
.br
.ti -1c
.RI "class \fBToggledserviceendpoint\fP"
.br
.ti -1c
.RI "class \fBToggledtext\fP"
.br
.ti -1c
.RI "class \fBToggledtext1\fP"
.br
.ti -1c
.RI "class \fBTogglemenuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBToplevelbutton\fP"
.br
.ti -1c
.RI "class \fBToplevelbutton1\fP"
.br
.ti -1c
.RI "class \fBVerticalgradient\fP"
.br
.ti -1c
.RI "class \fBWatchendpoint\fP"
.br
.ti -1c
.RI "class \fBWatchendpoint1\fP"
.br
.ti -1c
.RI "class \fBWatchendpoint2\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicconfig\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicconfig2\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicsupportedconfigs2\fP"
.br
.ti -1c
.RI "class \fBWatchplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBWatchplaylistendpoint1\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBResponsecontext\fP \fBresponseContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContents\fP \fBcontents\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBHeader\fP \fBheader\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBContents\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.contents\fC [get]\fP, \fC [set]\fP"

.SS "\fBHeader\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.header\fC [get]\fP, \fC [set]\fP"

.SS "\fBResponsecontext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.responseContext\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
