.TH "YTMusicUploader.Providers.Playlist.Models.BasePlaylist< T >" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.BasePlaylist< T > \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.IBasePlaylist\fP\&.
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylist< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBList\fP< string > \fBGetTracksPaths\fP ()"
.br
.ti -1c
.RI "\fBBasePlaylist\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBList\fP< T > \fBPlaylistEntries\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFileName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBBasePlaylistEntry\fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist\fP< T >\&.\fBBasePlaylist\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBList\fP<string> \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist\fP< T >\&.GetTracksPaths ()"

.PP
Implements \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.IBasePlaylist\fP\&.
.SH "Property Documentation"
.PP 
.SS "string \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist\fP< T >\&.FileName\fC [get]\fP, \fC [set]\fP"

.SS "string \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist\fP< T >\&.Path\fC [get]\fP, \fC [set]\fP"

.SS "\fBList\fP<T> \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist\fP< T >\&.PlaylistEntries\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
