.TH "YTMusicUploader.Providers.RequestModels.Navigationendpoint6" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.Navigationendpoint6
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCreateplaylistendpoint1\fP \fBcreatePlaylistEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBrowseendpoint8\fP \fBbrowseEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBBrowseendpoint8\fP YTMusicUploader\&.Providers\&.RequestModels\&.Navigationendpoint6\&.browseEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.Navigationendpoint6\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "\fBCreateplaylistendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.Navigationendpoint6\&.createPlaylistEndpoint\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
