.TH "YTMusicUploader.MusicBrainz.API.Entities.LifeSpan" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.LifeSpan
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBBegin\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the begin date\&. "
.ti -1c
.RI "string \fBEnd\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the end date\&. "
.ti -1c
.RI "bool? \fBEnded\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the life-span ended or not\&. "
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.LifeSpan\&.Begin\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the begin date\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.LifeSpan\&.End\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the end date\&. 
.SS "bool? YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.LifeSpan\&.Ended\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the life-span ended or not\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
