.TH "YTMusicUploader.Providers.Playlist.Models.HlsMediaPlaylist" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.HlsMediaPlaylist \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsPlaylist< HlsMediaPlaylistEntry >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHlsMediaPlaylist\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMediaSequence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int? \fBTargetDuration\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int? \fBDiscontinuitySequence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPlaylistType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBEndList\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIFramesOnly\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylist\&.HlsMediaPlaylist ()"

.SH "Property Documentation"
.PP 
.SS "int? YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylist\&.DiscontinuitySequence\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylist\&.EndList\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylist\&.IFramesOnly\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylist\&.MediaSequence\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylist\&.PlaylistType\fC [get]\fP, \fC [set]\fP"

.SS "int? YTMusicUploader\&.Providers\&.Playlist\&.Models\&.HlsMediaPlaylist\&.TargetDuration\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
