.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Musicdetailheaderrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Musicdetailheaderrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTitle1\fP \fBtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSubtitle\fP \fBsubtitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMenu1\fP \fBmenu\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBThumbnail3\fP \fBthumbnail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMorebutton\fP \fBmoreButton\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSecondsubtitle\fP \fBsecondSubtitle\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBMenu1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicdetailheaderrenderer\&.menu\fC [get]\fP, \fC [set]\fP"

.SS "\fBMorebutton\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicdetailheaderrenderer\&.moreButton\fC [get]\fP, \fC [set]\fP"

.SS "\fBSecondsubtitle\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicdetailheaderrenderer\&.secondSubtitle\fC [get]\fP, \fC [set]\fP"

.SS "\fBSubtitle\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicdetailheaderrenderer\&.subtitle\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnail3\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicdetailheaderrenderer\&.thumbnail\fC [get]\fP, \fC [set]\fP"

.SS "\fBTitle1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicdetailheaderrenderer\&.title\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Musicdetailheaderrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
