.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContinuationContext.Continuationcontents" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContinuationContext.Continuationcontents
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMusicshelfcontinuation\fP \fBmusicShelfContinuation\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBMusicshelfcontinuation\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContinuationContext\&.Continuationcontents\&.musicShelfContinuation\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
