.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Addtotoastaction" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Addtotoastaction
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBItem1\fP \fBitem\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBItem1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Addtotoastaction\&.item\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
