.TH "YTMusicUploader.Business.FileUploader" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.FileUploader \- Responsive for managing uploading music files to YouTube Music\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileUploader\fP (\fBMainForm\fP mainForm)"
.br
.ti -1c
.RI "async Task \fBProcess\fP ()"
.br
.RI "Execute the upload process "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBStopped\fP = true\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBArtistCache\fP \fBArtistCache\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsive for managing uploading music files to YouTube Music\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Business\&.FileUploader\&.FileUploader (\fBMainForm\fP mainForm)"

.SH "Member Function Documentation"
.PP 
.SS "async Task YTMusicUploader\&.Business\&.FileUploader\&.Process ()"

.PP
Execute the upload process 
.SH "Property Documentation"
.PP 
.SS "\fBArtistCache\fP YTMusicUploader\&.Business\&.FileUploader\&.ArtistCache\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Business\&.FileUploader\&.Stopped = true\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
