.TH "YTMusicUploader.AssemblyHelper" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.AssemblyHelper
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmbeddedResourceHelper\fP"
.br
.RI "Methods for extracting and utilising resources embedded in the DLL (including assemblies and command line utilities) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
