.TH "YTMusicUploader.Dialogues" 3 "Mon Aug 24 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Dialogues
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnectToYTMusic\fP"
.br
.RI "Shows a WebView2 control https://docs.microsoft.com/en-us/microsoft-edge/webview2/ "
.ti -1c
.RI "class \fBIssueLog\fP"
.br
.RI "Dialogue "
.ti -1c
.RI "class \fBUploadLog\fP"
.br
.RI "Form to display upload successes\&. Data fetched from the local database\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
