.TH "YTMusicUploader.MusicBrainz.API.Entities.LabelInfo" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.LabelInfo
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCatalogNumber\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the catalog-number\&. "
.ti -1c
.RI "\fBLabel\fP \fBLabel\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the label\&. "
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.LabelInfo\&.CatalogNumber\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the catalog-number\&. 
.SS "\fBLabel\fP YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.LabelInfo\&.Label\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the label\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
