.TH "YTMusicUploader.MusicBrainz.API.Entities.TextRepresentation" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.TextRepresentation
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBLanguage\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the language\&. "
.ti -1c
.RI "string \fBScript\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the script\&. "
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.TextRepresentation\&.Language\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the language\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.TextRepresentation\&.Script\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the script\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
