.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Shelfdivider" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext.Shelfdivider
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMusicshelfdividerrenderer\fP \fBmusicShelfDividerRenderer\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBMusicshelfdividerrenderer\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.Shelfdivider\&.musicShelfDividerRenderer\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
