.TH "YTMusicUploader.MusicBrainz.API.QueryParameters< T >.Node" 3 "Sun Nov 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.QueryParameters< T >.Node
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (string key, string value, bool negate)"
.br
.RI "Initializes a new instance of the \fBNode\fP class\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBKey\fP\fC [get]\fP"
.br
.RI "Gets the key of the node\&. "
.ti -1c
.RI "string \fBValue\fP\fC [get]\fP"
.br
.RI "Gets the value of the node\&. "
.ti -1c
.RI "bool \fBNegate\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the node should be negated\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBYTMusicUploader\&.MusicBrainz\&.API\&.QueryParameters\fP< T >\&.Node\&.Node (string key, string value, bool negate)"

.PP
Initializes a new instance of the \fBNode\fP class\&. 
.SH "Property Documentation"
.PP 
.SS "string \fBYTMusicUploader\&.MusicBrainz\&.API\&.QueryParameters\fP< T >\&.Node\&.Key\fC [get]\fP"

.PP
Gets the key of the node\&. 
.SS "bool \fBYTMusicUploader\&.MusicBrainz\&.API\&.QueryParameters\fP< T >\&.Node\&.Negate\fC [get]\fP"

.PP
Gets a value indicating whether the node should be negated\&. 
.SS "string \fBYTMusicUploader\&.MusicBrainz\&.API\&.QueryParameters\fP< T >\&.Node\&.Value\fC [get]\fP"

.PP
Gets the value of the node\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
