.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Dropdownitemrenderer" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Dropdownitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLabel\fP \fBlabel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisSelected\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibility4\fP \fBaccessibility\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBstringValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIcon6\fP \fBicon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDescriptiontext\fP \fBdescriptionText\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAccessibility4\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Dropdownitemrenderer\&.accessibility\fC [get]\fP, \fC [set]\fP"

.SS "\fBDescriptiontext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Dropdownitemrenderer\&.descriptionText\fC [get]\fP, \fC [set]\fP"

.SS "\fBIcon6\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Dropdownitemrenderer\&.icon\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Dropdownitemrenderer\&.isSelected\fC [get]\fP, \fC [set]\fP"

.SS "\fBLabel\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Dropdownitemrenderer\&.label\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Dropdownitemrenderer\&.stringValue\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
