.TH "YTMusicUploader.Providers.RequestModels.ArtistCache.PlaylistSong" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.ArtistCache.PlaylistSong
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBVideoId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSetVideoId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCoverArtUrl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDuration\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAlbumTitle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBArtistTitle\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.PlaylistSong\&.AlbumTitle\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.PlaylistSong\&.ArtistTitle\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.PlaylistSong\&.CoverArtUrl\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.PlaylistSong\&.Duration\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.PlaylistSong\&.SetVideoId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.PlaylistSong\&.Title\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.ArtistCache\&.PlaylistSong\&.VideoId\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
