.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Watchendpoint" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Watchendpoint
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBvideoId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBplaylistId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fB_params\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBWatchendpointmusicsupportedconfigs\fP \fBwatchEndpointMusicSupportedConfigs\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpoint\&._params\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpoint\&.playlistId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpoint\&.videoId\fC [get]\fP, \fC [set]\fP"

.SS "\fBWatchendpointmusicsupportedconfigs\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Watchendpoint\&.watchEndpointMusicSupportedConfigs\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
