.TH "YTMusicUploader.Providers.RequestModels.SearchContext" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchContext \- Deserialised HttpWebRequest body to send to YouTube Music to perform a search of uploaded songs  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.RequestModels\&.IRequestModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActivePlayers\fP"
.br
.ti -1c
.RI "class \fBCapabilities\fP"
.br
.ti -1c
.RI "class \fBClickTracking\fP"
.br
.ti -1c
.RI "class \fBClient\fP"
.br
.ti -1c
.RI "class \fBContext\fP"
.br
.ti -1c
.RI "class \fBInternalExperimentFlag\fP"
.br
.ti -1c
.RI "class \fBLocationInfo\fP"
.br
.ti -1c
.RI "class \fBMusicAppInfo\fP"
.br
.ti -1c
.RI "class \fBRequest\fP"
.br
.ti -1c
.RI "class \fBUser\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBContext\fP \fBcontext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBparameters\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBquery\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Deserialised HttpWebRequest body to send to YouTube Music to perform a search of uploaded songs 


.SH "Property Documentation"
.PP 
.SS "\fBContext\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.context\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.parameters\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\&.query\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
