.TH "YTMusicUploader" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBusiness\fP"
.br
.ti -1c
.RI "namespace \fBCustomControls\fP"
.br
.ti -1c
.RI "namespace \fBDialogues\fP"
.br
.ti -1c
.RI "namespace \fBMusicBrainz\fP"
.br
.ti -1c
.RI "namespace \fBProperties\fP"
.br
.ti -1c
.RI "namespace \fBProviders\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGlobal\fP"
.br
.RI "Globally accessible properties\&. Typically returns calculated values based on user preference or system configuration or from the application's App\&.config settings file "
.ti -1c
.RI "class \fBMainForm\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
