.TH "YTMusicUploader.Business" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPipes\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEdgeDependencyChecker\fP"
.br
.RI "Used for checking Edge Core file dependencies "
.ti -1c
.RI "class \fBFileScanner\fP"
.br
.RI "Responsive for scanning library music files and adding and managing discovered files to the database\&. "
.ti -1c
.RI "class \fBFileUploader\fP"
.br
.RI "Responsive for managing uploading music files to YouTube Music\&. "
.ti -1c
.RI "class \fBIdleProcessor\fP"
.br
.RI "Performs operations while the application is in idle state, such as retreiving data from \fBMusicBrainz\fP and updating the MusicFile database entries with the retreived data "
.ti -1c
.RI "class \fBMusicDataFetcher\fP"
.br
.RI "Gets meta data / tag information from the music file itself and looks up any missing data using a \fBMusicBrainz\fP API implementation (for instance album cover art, in which it will lookup CoverArtArchive: https://coverartarchive.org/ "
.ti -1c
.RI "class \fBMusicFileMetaData\fP"
.br
.RI "Custom music file meta tag object "
.ti -1c
.RI "class \fBQueueChecker\fP"
.br
.RI "Constantly watches for the folder watcher state changed variable (Queue) in order to queue a new process when the music library changes (file added, deleted etc) "
.ti -1c
.RI "class \fBRegistrySettings\fP"
.br
.RI "Windows registry helper methods "
.ti -1c
.RI "class \fBThrottledStream\fP"
.br
.RI "Throttle a stream -> Very useful for throttle HttpWebRequest uploads / downloads\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
