.TH "YTMusicUploader.Business.IdleProcessor" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.IdleProcessor \- Performs operations while the application is in idle state, such as retreiving data from \fBMusicBrainz\fP and updating the MusicFile database entries with the retreived data  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIdleProcessor\fP (\fBMainForm\fP mainForm)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBPaused\fP = true\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBStopped\fP = false\fC [get, set]\fP"
.br
.ti -1c
.RI "Thread \fBIdleProcessorThread\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Performs operations while the application is in idle state, such as retreiving data from \fBMusicBrainz\fP and updating the MusicFile database entries with the retreived data 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Business\&.IdleProcessor\&.IdleProcessor (\fBMainForm\fP mainForm)"

.SH "Property Documentation"
.PP 
.SS "Thread YTMusicUploader\&.Business\&.IdleProcessor\&.IdleProcessorThread\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Business\&.IdleProcessor\&.Paused = true\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Business\&.IdleProcessor\&.Stopped = false\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
