.TH "YTMusicUploader.MusicBrainz.API.Services.IWorkService" 3 "Sun Nov 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Services.IWorkService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.MusicBrainz\&.API\&.Services\&.WorkService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< \fBWork\fP > \fBGetAsync\fP (string id, params string[] inc)"
.br
.RI "Lookup a work in the \fBMusicBrainz\fP database\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Task<\fBWork\fP> YTMusicUploader\&.MusicBrainz\&.API\&.Services\&.IWorkService\&.GetAsync (string id, params string[] inc)"

.PP
Lookup a work in the \fBMusicBrainz\fP database\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP The work \fBMusicBrainz\fP id\&.
.br
\fIinc\fP A list of entities to include (subqueries)\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBYTMusicUploader\&.MusicBrainz\&.API\&.Services\&.WorkService\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
