.TH "YTMusicUploader.Providers.Playlist.Content.ZplContent" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.ZplContent \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistParser< ZplPlaylist >\fP, and \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistWriter< ZplPlaylist >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBToText\fP (\fBZplPlaylist\fP playlist)"
.br
.ti -1c
.RI "\fBZplPlaylist\fP \fBGetFromStream\fP (Stream stream)"
.br
.ti -1c
.RI "\fBZplPlaylist\fP \fBGetFromString\fP (string playlistString)"
.br
.ti -1c
.RI "string \fBUpdate\fP (\fBZplPlaylist\fP playlist, Stream stream)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Member Function Documentation"
.PP 
.SS "\fBZplPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.ZplContent\&.GetFromStream (Stream stream)"

.SS "\fBZplPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.ZplContent\&.GetFromString (string playlistString)"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Content\&.ZplContent\&.ToText (\fBZplPlaylist\fP playlist)"

.SS "string YTMusicUploader\&.Providers\&.Playlist\&.Content\&.ZplContent\&.Update (\fBZplPlaylist\fP playlist, Stream stream)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
