.TH "YTMusicUploader.Business.MusicFileMetaData" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.MusicFileMetaData \- Custom music file meta tag object  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMbId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBReleaseMbId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBArtist\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAlbum\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBTrack\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "TimeSpan \fBDuration\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBBitrate\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Custom music file meta tag object 


.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Business\&.MusicFileMetaData\&.Album\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Business\&.MusicFileMetaData\&.Artist\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Business\&.MusicFileMetaData\&.Bitrate\fC [get]\fP, \fC [set]\fP"

.SS "TimeSpan YTMusicUploader\&.Business\&.MusicFileMetaData\&.Duration\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Business\&.MusicFileMetaData\&.MbId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Business\&.MusicFileMetaData\&.ReleaseMbId\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Business\&.MusicFileMetaData\&.Track\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
