.TH "YTMusicUploader.Providers.RequestModels.SearchResultContext.Buttonrenderer1" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.SearchResultContext.Buttonrenderer1
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBstyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBsize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisDisabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBText2\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer1\&.isDisabled\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer1\&.size\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer1\&.style\fC [get]\fP, \fC [set]\fP"

.SS "\fBText2\fP YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer1\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\&.Buttonrenderer1\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
