.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Responsecontext" 3 "Sun Sep 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContext.Responsecontext
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBServicetrackingparam\fP[] \fBserviceTrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBServicetrackingparam\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\&.Responsecontext\&.serviceTrackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
