.TH "YTMusicUploader.Providers.Playlist.Content.HlsMediaContent" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.HlsMediaContent \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistParser< HlsMediaPlaylist >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHlsMediaPlaylist\fP \fBGetFromStream\fP (Stream stream)"
.br
.ti -1c
.RI "\fBHlsMediaPlaylist\fP \fBGetFromString\fP (string playlistString)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Member Function Documentation"
.PP 
.SS "\fBHlsMediaPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.HlsMediaContent\&.GetFromStream (Stream stream)"

.SS "\fBHlsMediaPlaylist\fP YTMusicUploader\&.Providers\&.Playlist\&.Content\&.HlsMediaContent\&.GetFromString (string playlistString)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
