.TH "YTMusicUploader.Helpers" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Helpers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileSystemWatcherPoller\fP"
.br
.ti -1c
.RI "class \fBInstalledApplicationHelper\fP"
.br
.RI "Checks if the YT Music Uploader application is installed and if so what version (used for auto update) "
.ti -1c
.RI "class \fBSystemInfo\fP"
.br
.RI "Basic system info - To determine multi-threading settings to minimise resource hogging "
.ti -1c
.RI "class \fBSystemInfoHelper\fP"
.br
.RI "Get basic system info - To determine multi-threading settings to minimise resource hogging "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
