.TH "YTMusicUploader.MusicBrainz.API.Entities.Rating" 3 "Mon Sep 14 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Rating \- \fBRating\fP information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBVotesCount\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the votes-count\&. "
.ti -1c
.RI "double? \fBValue\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the rating value\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBRating\fP information\&. 


.SH "Property Documentation"
.PP 
.SS "double? YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Rating\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the rating value\&. 
.SS "int YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.Rating\&.VotesCount\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the votes-count\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
