.TH "YTMusicUploader.Providers.DataModels.Settings" 3 "Tue Aug 25 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.DataModels.Settings \- Application settings data  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async override Task< \fBDbOperationResult\fP > \fBSave\fP ()"
.br
.RI "Updates the database "
.ti -1c
.RI "async override Task< \fBDbOperationResult\fP > \fBDelete\fP ()"
.br
.RI "Not implemented for the '\fBSettings\fP' model "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBStartWithWindows\fP = true\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBThrottleSpeed\fP = \-1\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAuthenticationCookie\fP = null\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application settings data 


.SH "Member Function Documentation"
.PP 
.SS "async override Task<\fBDbOperationResult\fP> YTMusicUploader\&.Providers\&.DataModels\&.Settings\&.Delete ()\fC [virtual]\fP"

.PP
Not implemented for the '\fBSettings\fP' model 
.PP
Implements \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SS "async override Task<\fBDbOperationResult\fP> YTMusicUploader\&.Providers\&.DataModels\&.Settings\&.Save ()\fC [virtual]\fP"

.PP
Updates the database 
.PP
\fBReturns\fP
.RS 4
\fBDbOperationResult\fP - Showing success or fail, with messages and stats
.RE
.PP

.PP
Implements \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.DataModels\&.Settings\&.AuthenticationCookie = null\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.DataModels\&.Settings\&.StartWithWindows = true\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.DataModels\&.Settings\&.ThrottleSpeed = \-1\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
