.TH "YTMusicUploader.MusicBrainz.API.Entities.Collections" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.Collections
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArtistList\fP"
.br
.RI "\fBList\fP of artists returned by \fBMusicBrainz\fP search requests\&. "
.ti -1c
.RI "class \fBArtistListBrowse\fP"
.br
.RI "\fBList\fP of artists returned by \fBMusicBrainz\fP browse requests\&. "
.ti -1c
.RI "class \fBRecordingList\fP"
.br
.RI "\fBList\fP of recordings returned by \fBMusicBrainz\fP search requests\&. "
.ti -1c
.RI "class \fBRecordingListBrowse\fP"
.br
.RI "\fBList\fP of recordings returned by \fBMusicBrainz\fP browse requests\&. "
.ti -1c
.RI "class \fBReleaseGroupList\fP"
.br
.RI "\fBList\fP of release-groups returned by \fBMusicBrainz\fP search requests\&. "
.ti -1c
.RI "class \fBReleaseGroupListBrowse\fP"
.br
.RI "\fBList\fP of release-groups returned by \fBMusicBrainz\fP browse requests\&. "
.ti -1c
.RI "class \fBReleaseList\fP"
.br
.RI "\fBList\fP of releases returned by \fBMusicBrainz\fP search requests\&. "
.ti -1c
.RI "class \fBReleaseListBrowse\fP"
.br
.RI "\fBList\fP of releases returned by \fBMusicBrainz\fP browse requests\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
