.TH "YTMusicUploader.Providers.Database.Upgrade" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Database.Upgrade
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCheckAndRun\fP ()"
.br
.RI "Runs on form load to ensure the database schema is at the latest version following an application upgrade "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void YTMusicUploader\&.Providers\&.Database\&.Upgrade\&.CheckAndRun ()\fC [static]\fP"

.PP
Runs on form load to ensure the database schema is at the latest version following an application upgrade 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
