.TH "D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/obj/x86/Release/YTMusicUploader.csproj.FileListAbsolute.txt" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/OneDrive/Documents/Work/Repositories/YTMusicUploader/YTMusicUploader/obj/x86/Release/YTMusicUploader.csproj.FileListAbsolute.txt
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
