.TH "YTMusicUploader.MusicBrainz.API.Cache.FileRequestCache" 3 "Sun Sep 13 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Cache.FileRequestCache \- Caches requests to \fBMusicBrainz\fP \fBAPI\fP on disk\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.IRequestCache\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileRequestCache\fP ()"
.br
.ti -1c
.RI "\fBFileRequestCache\fP (string path)"
.br
.ti -1c
.RI "async Task \fBAdd\fP (string request, Stream response)"
.br
.RI "Add a request and its response to the cache\&. "
.ti -1c
.RI "Task< bool > \fBTryGetCachedItem\fP (string request, out Stream stream)"
.br
.RI "Add a request and its response to the cache\&. "
.ti -1c
.RI "int \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TimeSpan \fBTimeout\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the timeout for a cache entry to expire\&. "
.in -1c
.SH "Detailed Description"
.PP 
Caches requests to \fBMusicBrainz\fP \fBAPI\fP on disk\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.FileRequestCache\&.FileRequestCache ()"

.SS "YTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.FileRequestCache\&.FileRequestCache (string path)"

.SH "Member Function Documentation"
.PP 
.SS "async Task YTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.FileRequestCache\&.Add (string request, Stream response)"

.PP
Add a request and its response to the cache\&. 
.PP
Implements \fBYTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.IRequestCache\fP\&.
.SS "int YTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.FileRequestCache\&.Cleanup ()"

.SS "void YTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.FileRequestCache\&.Clear ()"

.SS "Task<bool> YTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.FileRequestCache\&.TryGetCachedItem (string request, out Stream stream)"

.PP
Add a request and its response to the cache\&. 
.PP
\fBReturns\fP
.RS 4
True, if a cache entry matching the request was found\&.
.RE
.PP

.PP
Implements \fBYTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.IRequestCache\fP\&.
.SH "Property Documentation"
.PP 
.SS "TimeSpan YTMusicUploader\&.MusicBrainz\&.API\&.Cache\&.FileRequestCache\&.Timeout\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the timeout for a cache entry to expire\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
