.TH "YTMusicUploader.MusicBrainz.API.Entities.NameCredit" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.NameCredit \- \fBArtist\fP credits indicate who is the main credited artist (or artists) for releases, release groups, tracks and recordings\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBJoinPhrase\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the joinphrase\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the name\&. "
.ti -1c
.RI "\fBArtist\fP \fBArtist\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the artist\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBArtist\fP credits indicate who is the main credited artist (or artists) for releases, release groups, tracks and recordings\&. 


.SH "Property Documentation"
.PP 
.SS "\fBArtist\fP YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.NameCredit\&.Artist\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the artist\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.NameCredit\&.JoinPhrase\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the joinphrase\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.NameCredit\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
