.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Musicresponsivelistitemrenderer" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Musicresponsivelistitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBThumbnail2\fP \fBthumbnail\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFlexcolumn\fP[] \fBflexColumns\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMenu1\fP \fBmenu\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBflexColumnDisplayStyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNavigationendpoint6\fP \fBnavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBitemHeight\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemrenderer\&.flexColumnDisplayStyle\fC [get]\fP, \fC [set]\fP"

.SS "\fBFlexcolumn\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemrenderer\&.flexColumns\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemrenderer\&.itemHeight\fC [get]\fP, \fC [set]\fP"

.SS "\fBMenu1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemrenderer\&.menu\fC [get]\fP, \fC [set]\fP"

.SS "\fBNavigationendpoint6\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemrenderer\&.navigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBThumbnail2\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemrenderer\&.thumbnail\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Musicresponsivelistitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
