.TH "YTMusicUploader.MusicBrainz.API.Entities.ReleaseGroup" 3 "Sat Oct 10 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.ReleaseGroup \- A release group is used to group several different releases into a single logical entity\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBScore\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the score (only available in search results)\&. "
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the \fBMusicBrainz\fP id\&. "
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the title\&. "
.ti -1c
.RI "string \fBFirstReleaseDate\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the first release date\&. "
.ti -1c
.RI "string \fBPrimaryType\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the primary type\&. "
.ti -1c
.RI "\fBList\fP< string > \fBSecondaryTypes\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the secondary types\&. "
.ti -1c
.RI "\fBRating\fP \fBRating\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the rating\&. "
.ti -1c
.RI "\fBList\fP< \fBNameCredit\fP > \fBCredits\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a list of artists associated to this release-group\&. "
.ti -1c
.RI "\fBList\fP< \fBRelease\fP > \fBReleases\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a list of releases associated to this release-group\&. "
.ti -1c
.RI "\fBList\fP< \fBTag\fP > \fBTags\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a list of tags associated to this release-group\&. "
.ti -1c
.RI "\fBList\fP< \fBRelation\fP > \fBRelations\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a list of relations associated to this release-group\&. "
.in -1c
.SH "Detailed Description"
.PP 
A release group is used to group several different releases into a single logical entity\&. 


.SH "Property Documentation"
.PP 
.SS "\fBList\fP<\fBNameCredit\fP> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.Credits\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a list of artists associated to this release-group\&. var e = await ReleaseGroup\&.GetAsync(mbid, 'artists'); 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.FirstReleaseDate\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the first release date\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the \fBMusicBrainz\fP id\&. 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.PrimaryType\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the primary type\&. 
.SS "\fBRating\fP YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.Rating\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the rating\&. 
.SS "\fBList\fP<\fBRelation\fP> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.Relations\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a list of relations associated to this release-group\&. var e = await ReleaseGroup\&.GetAsync(mbid, 'url-rels'); 
.SS "\fBList\fP<\fBRelease\fP> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.Releases\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a list of releases associated to this release-group\&. var e = await ReleaseGroup\&.GetAsync(mbid, 'releases'); 
.SS "int YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.Score\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the score (only available in search results)\&. 
.SS "\fBList\fP<string> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.SecondaryTypes\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the secondary types\&. 
.SS "\fBList\fP<\fBTag\fP> YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.Tags\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a list of tags associated to this release-group\&. var e = await ReleaseGroup\&.GetAsync(mbid, 'tags'); 
.SS "string YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.ReleaseGroup\&.Title\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the title\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
