.TH "YTMusicUploader.Providers.RequestModels.IRequestModel" 3 "Sat Aug 29 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.IRequestModel
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistRequestContext\fP, \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContext\fP, \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\fP, \fBYTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\fP, \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchContext\fP, and \fBYTMusicUploader\&.Providers\&.RequestModels\&.SearchResultContext\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
