.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Buttonrenderer2" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Buttonrenderer2
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBstyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBsize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisDisabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBText7\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBServiceendpoint2\fP \fBserviceEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "bool YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer2\&.isDisabled\fC [get]\fP, \fC [set]\fP"

.SS "\fBServiceendpoint2\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer2\&.serviceEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer2\&.size\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer2\&.style\fC [get]\fP, \fC [set]\fP"

.SS "\fBText7\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer2\&.text\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Buttonrenderer2\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
