.TH "YTMusicUploader.Providers.Playlist.Content.IPlaylistWriter< T >" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Content.IPlaylistWriter< T > \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBToText\fP (T playlist)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIBasePlaylist\fP
.SH "Member Function Documentation"
.PP 
.SS "string \fBYTMusicUploader\&.Providers\&.Playlist\&.Content\&.IPlaylistWriter\fP< T >\&.ToText (T playlist)"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
