.TH "YTMusicUploader.Providers.Playlist.Models.M3uPlaylist" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.Playlist.Models.M3uPlaylist \- Music playlist library implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.Playlist\&.Models\&.BasePlaylist< M3uPlaylistEntry >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBM3uPlaylist\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBList\fP< string > \fBGetPlaylistFromCorruptM3u\fP (string playlistPath)"
.br
.RI "This handles playlists created in a particular version of VLC and saved as \&.mp3u\&. For some odd reason VLC isn't saving them correctly\&. In fact, you can't even open that playlist in VLC! "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsExtended\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBList\fP< string > \fBComments\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Music playlist library implementation 

See https://github.com/tmk907/PlaylistsNET 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "YTMusicUploader\&.Providers\&.Playlist\&.Models\&.M3uPlaylist\&.M3uPlaylist ()"

.SH "Member Function Documentation"
.PP 
.SS "static \fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.M3uPlaylist\&.GetPlaylistFromCorruptM3u (string playlistPath)\fC [static]\fP"

.PP
This handles playlists created in a particular version of VLC and saved as \&.mp3u\&. For some odd reason VLC isn't saving them correctly\&. In fact, you can't even open that playlist in VLC! None-the-less, the playlist does include the file paths, therefore we can parse them\&.
.PP
\fBParameters\fP
.RS 4
\fIplaylistPath\fP Full path to playlist file
.RE
.PP
\fBReturns\fP
.RS 4
Music file paths as a string list
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBList\fP<string> YTMusicUploader\&.Providers\&.Playlist\&.Models\&.M3uPlaylist\&.Comments\fC [get]\fP, \fC [set]\fP"

.SS "bool YTMusicUploader\&.Providers\&.Playlist\&.Models\&.M3uPlaylist\&.IsExtended\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
