.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Queueaddendpoint" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistsResultsContext.Queueaddendpoint
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBQueuetarget\fP \fBqueueTarget\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBqueueInsertPosition\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCommand\fP[] \fBcommands\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBCommand\fP [] YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Queueaddendpoint\&.commands\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Queueaddendpoint\&.queueInsertPosition\fC [get]\fP, \fC [set]\fP"

.SS "\fBQueuetarget\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistsResultsContext\&.Queueaddendpoint\&.queueTarget\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
