.TH "YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Togglemenuserviceitemrenderer" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowsePlaylistResultsContext.Togglemenuserviceitemrenderer
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDefaulttext\fP \fBdefaultText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDefaulticon\fP \fBdefaultIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDefaultserviceendpoint\fP \fBdefaultServiceEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBToggledtext\fP \fBtoggledText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBToggledicon\fP \fBtoggledIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBToggledserviceendpoint\fP \fBtoggledServiceEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBDefaulticon\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglemenuserviceitemrenderer\&.defaultIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBDefaultserviceendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglemenuserviceitemrenderer\&.defaultServiceEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBDefaulttext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglemenuserviceitemrenderer\&.defaultText\fC [get]\fP, \fC [set]\fP"

.SS "\fBToggledicon\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglemenuserviceitemrenderer\&.toggledIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBToggledserviceendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglemenuserviceitemrenderer\&.toggledServiceEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBToggledtext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglemenuserviceitemrenderer\&.toggledText\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowsePlaylistResultsContext\&.Togglemenuserviceitemrenderer\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
