.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Navigationendpoint4" 3 "Fri Nov 20 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistsResultsContext.Navigationendpoint4
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclickTrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBWatchplaylistendpoint\fP \fBwatchPlaylistEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAddtoplaylistendpoint\fP \fBaddToPlaylistEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBShareentityendpoint\fP \fBshareEntityEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBWatchendpoint1\fP \fBwatchEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBrowseendpoint4\fP \fBbrowseEndpoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAddtoplaylistendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint4\&.addToPlaylistEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBBrowseendpoint4\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint4\&.browseEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint4\&.clickTrackingParams\fC [get]\fP, \fC [set]\fP"

.SS "\fBShareentityendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint4\&.shareEntityEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBWatchendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint4\&.watchEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "\fBWatchplaylistendpoint\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistsResultsContext\&.Navigationendpoint4\&.watchPlaylistEndpoint\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
