.TH "YTMusicUploader.Providers.DataModels.WatchFolder" 3 "Mon Aug 24 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.DataModels.WatchFolder \- Selected libraries to scan and watch data  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBDbOperationResult\fP \fBSave\fP ()"
.br
.RI "Insert into the database "
.ti -1c
.RI "override \fBDbOperationResult\fP \fBDelete\fP ()"
.br
.RI "Delete from the database "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPath\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Selected libraries to scan and watch data 


.SH "Member Function Documentation"
.PP 
.SS "override \fBDbOperationResult\fP YTMusicUploader\&.Providers\&.DataModels\&.WatchFolder\&.Delete ()\fC [virtual]\fP"

.PP
Delete from the database 
.PP
\fBReturns\fP
.RS 4
\fBDbOperationResult\fP - Showing success or fail, with messages and stats
.RE
.PP

.PP
Implements \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SS "override \fBDbOperationResult\fP YTMusicUploader\&.Providers\&.DataModels\&.WatchFolder\&.Save ()\fC [virtual]\fP"

.PP
Insert into the database 
.PP
\fBReturns\fP
.RS 4
\fBDbOperationResult\fP - Showing success or fail, with messages and stats
.RE
.PP

.PP
Implements \fBYTMusicUploader\&.Providers\&.DataModels\&.DbModels\fP\&.
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Providers\&.DataModels\&.WatchFolder\&.Path\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
