.TH "YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext" 3 "Sat Nov 21 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.BrowseArtistResultsContinuationContext \- Deserialised HttpWebRequest response body received from YouTube Music after a search  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBYTMusicUploader\&.Providers\&.RequestModels\&.IRequestModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccessibility\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata1\fP"
.br
.ti -1c
.RI "class \fBAccessibilitydata2\fP"
.br
.ti -1c
.RI "class \fBAccessibilitypausedata\fP"
.br
.ti -1c
.RI "class \fBAccessibilityplaydata\fP"
.br
.ti -1c
.RI "class \fBAddtoplaylistendpoint\fP"
.br
.ti -1c
.RI "class \fBAddtotoastaction\fP"
.br
.ti -1c
.RI "class \fBBackground\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint\fP"
.br
.ti -1c
.RI "class \fBBrowseendpoint1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBBrowseendpointcontextsupportedconfigs1\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer\fP"
.br
.ti -1c
.RI "class \fBButtonrenderer1\fP"
.br
.ti -1c
.RI "class \fBCancelbutton\fP"
.br
.ti -1c
.RI "class \fBCommand\fP"
.br
.ti -1c
.RI "class \fBCommand1\fP"
.br
.ti -1c
.RI "class \fBConfirmbutton\fP"
.br
.ti -1c
.RI "class \fBConfirmdialogendpoint\fP"
.br
.ti -1c
.RI "class \fBConfirmdialogrenderer\fP"
.br
.ti -1c
.RI "class \fBContent\fP"
.br
.ti -1c
.RI "class \fBContent1\fP"
.br
.ti -1c
.RI "class \fBContent2\fP"
.br
.ti -1c
.RI "class \fBContinuationcontents\fP"
.br
.ti -1c
.RI "class \fBDialogmessage\fP"
.br
.ti -1c
.RI "class \fBFixedcolumn\fP"
.br
.ti -1c
.RI "class \fBFlexcolumn\fP"
.br
.ti -1c
.RI "class \fBHeader\fP"
.br
.ti -1c
.RI "class \fBIcon\fP"
.br
.ti -1c
.RI "class \fBIcon1\fP"
.br
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBItem1\fP"
.br
.ti -1c
.RI "class \fBLikebuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBLikeendpoint\fP"
.br
.ti -1c
.RI "class \fBMenu\fP"
.br
.ti -1c
.RI "class \fBMenunavigationitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMenurenderer\fP"
.br
.ti -1c
.RI "class \fBMenuserviceitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicdeleteprivatelyownedentitycommand\fP"
.br
.ti -1c
.RI "class \fBMusicheaderrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicitemthumbnailoverlayrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicplaybuttonrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemfixedcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemflexcolumnrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicresponsivelistitemrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicshelfcontinuation\fP"
.br
.ti -1c
.RI "class \fBMusicshelfdividerrenderer\fP"
.br
.ti -1c
.RI "class \fBMusicthumbnailrenderer\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBNavigationendpoint1\fP"
.br
.ti -1c
.RI "class \fBNotificationtextrenderer\fP"
.br
.ti -1c
.RI "class \fBOverlay\fP"
.br
.ti -1c
.RI "class \fBParam\fP"
.br
.ti -1c
.RI "class \fBPauseicon\fP"
.br
.ti -1c
.RI "class \fBPlayicon\fP"
.br
.ti -1c
.RI "class \fBPlayingicon\fP"
.br
.ti -1c
.RI "class \fBPlaynavigationendpoint\fP"
.br
.ti -1c
.RI "class \fBQueueaddendpoint\fP"
.br
.ti -1c
.RI "class \fBQueuetarget\fP"
.br
.ti -1c
.RI "class \fBResponsecontext\fP"
.br
.ti -1c
.RI "class \fBRun\fP"
.br
.ti -1c
.RI "class \fBRun1\fP"
.br
.ti -1c
.RI "class \fBRun2\fP"
.br
.ti -1c
.RI "class \fBRun3\fP"
.br
.ti -1c
.RI "class \fBRun4\fP"
.br
.ti -1c
.RI "class \fBRun5\fP"
.br
.ti -1c
.RI "class \fBRun6\fP"
.br
.ti -1c
.RI "class \fBRun7\fP"
.br
.ti -1c
.RI "class \fBRun8\fP"
.br
.ti -1c
.RI "class \fBRun9\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint\fP"
.br
.ti -1c
.RI "class \fBServiceendpoint1\fP"
.br
.ti -1c
.RI "class \fBServicetrackingparam\fP"
.br
.ti -1c
.RI "class \fBShelfdivider\fP"
.br
.ti -1c
.RI "class \fBSuccessresponsetext\fP"
.br
.ti -1c
.RI "class \fBTarget\fP"
.br
.ti -1c
.RI "class \fBTarget1\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.ti -1c
.RI "class \fBText1\fP"
.br
.ti -1c
.RI "class \fBText2\fP"
.br
.ti -1c
.RI "class \fBText3\fP"
.br
.ti -1c
.RI "class \fBText4\fP"
.br
.ti -1c
.RI "class \fBText5\fP"
.br
.ti -1c
.RI "class \fBThumbnail\fP"
.br
.ti -1c
.RI "class \fBThumbnail1\fP"
.br
.ti -1c
.RI "class \fBThumbnail2\fP"
.br
.ti -1c
.RI "class \fBTitle\fP"
.br
.ti -1c
.RI "class \fBTitle1\fP"
.br
.ti -1c
.RI "class \fBToplevelbutton\fP"
.br
.ti -1c
.RI "class \fBVerticalgradient\fP"
.br
.ti -1c
.RI "class \fBWatchendpoint\fP"
.br
.ti -1c
.RI "class \fBWatchendpoint1\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicconfig\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicconfig1\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicsupportedconfigs\fP"
.br
.ti -1c
.RI "class \fBWatchendpointmusicsupportedconfigs1\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBResponsecontext\fP \fBresponseContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBContinuationcontents\fP \fBcontinuationContents\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBHeader\fP \fBheader\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Deserialised HttpWebRequest response body received from YouTube Music after a search 


.SH "Property Documentation"
.PP 
.SS "\fBContinuationcontents\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.continuationContents\fC [get]\fP, \fC [set]\fP"

.SS "\fBHeader\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.header\fC [get]\fP, \fC [set]\fP"

.SS "\fBResponsecontext\fP YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.responseContext\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.BrowseArtistResultsContinuationContext\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
