.TH "YTMusicUploader.Helpers.SystemInfoHelper" 3 "Wed May 12 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Helpers.SystemInfoHelper \- Get basic system info - To determine multi-threading settings to minimise resource hogging  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSystemInfo\fP \fBGetSystemInfo\fP ()"
.br
.RI "Get basic system info - To determine multi-threading settings to minimise resource hogging "
.in -1c
.SH "Detailed Description"
.PP 
Get basic system info - To determine multi-threading settings to minimise resource hogging 


.SH "Member Function Documentation"
.PP 
.SS "static \fBSystemInfo\fP YTMusicUploader\&.Helpers\&.SystemInfoHelper\&.GetSystemInfo ()\fC [static]\fP"

.PP
Get basic system info - To determine multi-threading settings to minimise resource hogging 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
