.TH "YTMusicUploader.Providers.RequestModels.Musicplaybuttonrenderer1" 3 "Thu Dec 31 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Providers.RequestModels.Musicplaybuttonrenderer1
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPlaynavigationendpoint1\fP \fBplayNavigationEndpoint\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrackingParams\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPlayicon1\fP \fBplayIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPauseicon1\fP \fBpauseIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBiconColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBbackgroundColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBactiveBackgroundColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBloadingIndicatorColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPlayingicon1\fP \fBplayingIcon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBiconLoadingColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBactiveScaleFactor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBbuttonSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBrippleTarget\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibilityplaydata1\fP \fBaccessibilityPlayData\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAccessibilitypausedata1\fP \fBaccessibilityPauseData\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBAccessibilitypausedata1\fP YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.accessibilityPauseData\fC [get]\fP, \fC [set]\fP"

.SS "\fBAccessibilityplaydata1\fP YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.accessibilityPlayData\fC [get]\fP, \fC [set]\fP"

.SS "long YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.activeBackgroundColor\fC [get]\fP, \fC [set]\fP"

.SS "float YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.activeScaleFactor\fC [get]\fP, \fC [set]\fP"

.SS "long YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.backgroundColor\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.buttonSize\fC [get]\fP, \fC [set]\fP"

.SS "long YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.iconColor\fC [get]\fP, \fC [set]\fP"

.SS "int YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.iconLoadingColor\fC [get]\fP, \fC [set]\fP"

.SS "long YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.loadingIndicatorColor\fC [get]\fP, \fC [set]\fP"

.SS "\fBPauseicon1\fP YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.pauseIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlayicon1\fP YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.playIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlayingicon1\fP YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.playingIcon\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlaynavigationendpoint1\fP YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.playNavigationEndpoint\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.rippleTarget\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Providers\&.RequestModels\&.Musicplaybuttonrenderer1\&.trackingParams\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
