.TH "YTMusicUploader.Business.Pipes" 3 "Fri Aug 28 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Business.Pipes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataReceivedEventArgs\fP"
.br
.ti -1c
.RI "interface \fBIIpcClient\fP"
.br
.ti -1c
.RI "interface \fBIIpcServer\fP"
.br
.ti -1c
.RI "class \fBWcfClient\fP"
.br
.RI "WCF Named pipe client - To Send data to an existing \fBYTMusicUploader\fP process "
.ti -1c
.RI "class \fBWcfServer\fP"
.br
.RI "WCF Named pipe server - To receive data fro, an existing \fBYTMusicUploader\fP process "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
