.TH "YTMusicUploader.MusicBrainz.API.Entities.CoverArtArchive" 3 "Sun Nov 22 2020" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.MusicBrainz.API.Entities.CoverArtArchive \- Cover Art Archive information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Uri \fBGetCoverArtUri\fP (string releaseId)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBArtwork\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether artwork is available or not\&. "
.ti -1c
.RI "int \fBCount\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the count\&. "
.ti -1c
.RI "bool \fBFront\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether a front crover is available or not\&. "
.ti -1c
.RI "bool \fBBack\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether a back crover is available or not\&. "
.in -1c
.SH "Detailed Description"
.PP 
Cover Art Archive information\&. 


.SH "Member Function Documentation"
.PP 
.SS "static Uri YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.CoverArtArchive\&.GetCoverArtUri (string releaseId)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "bool YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.CoverArtArchive\&.Artwork\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether artwork is available or not\&. 
.SS "bool YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.CoverArtArchive\&.Back\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether a back crover is available or not\&. 
.SS "int YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.CoverArtArchive\&.Count\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the count\&. 
.SS "bool YTMusicUploader\&.MusicBrainz\&.API\&.Entities\&.CoverArtArchive\&.Front\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether a front crover is available or not\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
