.TH "YTMusicUploader.Helpers.InstalledApplicationHelper.InstalledProgram" 3 "Sat Apr 10 2021" "YT Music Uploader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YTMusicUploader.Helpers.InstalledApplicationHelper.InstalledProgram \- Checks if the YT Music Uploader application is installed and if so what version (used for auto update)  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPlatFormType\fP { \fBPlatFormType\&.X86\fP, \fBPlatFormType\&.X64\fP }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPlatFormType\fP \fBPlaform\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDisplayName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBInstalledDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPublisher\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUnninstallCommand\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBModifyPath\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Checks if the YT Music Uploader application is installed and if so what version (used for auto update) 


.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBYTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\&.PlatFormType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIX86 \fP\fP
.TP
\fB\fIX64 \fP\fP
.SH "Property Documentation"
.PP 
.SS "string YTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\&.DisplayName\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\&.InstalledDate\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\&.ModifyPath\fC [get]\fP, \fC [set]\fP"

.SS "\fBPlatFormType\fP YTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\&.Plaform\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\&.Publisher\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\&.UnninstallCommand\fC [get]\fP, \fC [set]\fP"

.SS "string YTMusicUploader\&.Helpers\&.InstalledApplicationHelper\&.InstalledProgram\&.Version\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for YT Music Uploader from the source code\&.
