var class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context =
[
    [ "Action", "dd/d61/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_action.html", "dd/d61/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_action" ],
    [ "Activeplayer", "d7/de1/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_activeplayer.html", "d7/de1/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_activeplayer" ],
    [ "Capabilities", "dc/d28/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_capabilities.html", null ],
    [ "Clicktracking", "df/d93/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_clicktracking.html", "df/d93/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_clicktracking" ],
    [ "Client", "dd/d3b/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_client.html", "dd/d3b/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_client" ],
    [ "Context", "df/dd3/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_context.html", "df/dd3/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_context" ],
    [ "Internalexperimentflag", "d9/d75/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_internalexperimentflag.html", "d9/d75/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_internalexperimentflag" ],
    [ "Locationinfo", "dc/dfb/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_locationinfo.html", "dc/dfb/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_locationinfo" ],
    [ "Musicappinfo", "dc/d38/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_musicappinfo.html", "dc/d38/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_musicappinfo" ],
    [ "Request", "da/deb/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_request.html", "da/deb/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_request" ],
    [ "User", "da/d89/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_user.html", "da/d89/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context_1_1_user" ],
    [ "actions", "df/de3/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context.html#a101b23606f2a4df7153ff976c22db0f4", null ],
    [ "context", "df/de3/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context.html#a9afb3c239d6921b4f831accd3d3048c3", null ],
    [ "playlistId", "df/de3/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context.html#a63c8a7f8d10fa7e87173d9f0c0cd152a", null ]
];