var namespace_y_t_music_uploader_1_1_providers_1_1_request_models =
[
    [ "AddPlaylistItemContext", "df/de3/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context.html", "df/de3/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_add_playlist_item_context" ],
    [ "ArtistCache", "d9/d84/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_artist_cache.html", "d9/d84/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_artist_cache" ],
    [ "BrowseArtistRequestContext", "d5/d4a/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artist_request_context.html", "d5/d4a/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artist_request_context" ],
    [ "BrowseArtistResultsContext", "d8/d20/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artist_results_context.html", "d8/d20/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artist_results_context" ],
    [ "BrowseArtistResultsContinuationContext", "de/d8e/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artist_results_continuation_context.html", "de/d8e/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artist_results_continuation_context" ],
    [ "BrowseArtistsResultsContext", "d7/dd2/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artists_results_context.html", "d7/dd2/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artists_results_context" ],
    [ "BrowseArtistsResultsContinuationContext", "df/d67/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artists_results_continuation_context.html", "df/d67/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_artists_results_continuation_context" ],
    [ "BrowsePlaylistResultsContext", "da/d91/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_playlist_results_context.html", "da/d91/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_playlist_results_context" ],
    [ "BrowsePlaylistsResultsContext", "d0/d35/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_playlists_results_context.html", "d0/d35/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_playlists_results_context" ],
    [ "BrowsePlaylistsResultsContinuationContext", "d3/d10/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_playlists_results_continuation_context.html", "d3/d10/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_browse_playlists_results_continuation_context" ],
    [ "CreatePlaylistRequestContext", "d6/d5e/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_create_playlist_request_context.html", "d6/d5e/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_create_playlist_request_context" ],
    [ "DeleteFromYTMusicRequestContext", "d3/d79/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_delete_from_y_t_music_request_context.html", "d3/d79/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_delete_from_y_t_music_request_context" ],
    [ "DeletePlaylistItemRequestContext", "d4/d1a/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_delete_playlist_item_request_context.html", "d4/d1a/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_delete_playlist_item_request_context" ],
    [ "DeletePlaylistRequestContext", "d2/dfd/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_delete_playlist_request_context.html", "d2/dfd/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_delete_playlist_request_context" ],
    [ "IRequestModel", "d4/d23/interface_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_i_request_model.html", null ],
    [ "MusicManageTreeNodeModel", "dd/d88/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_music_manage_tree_node_model.html", "dd/d88/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_music_manage_tree_node_model" ],
    [ "SearchContext", "db/d9e/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_search_context.html", "db/d9e/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_search_context" ],
    [ "SearchResultContext", "dc/dc5/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_search_result_context.html", "dc/dc5/class_y_t_music_uploader_1_1_providers_1_1_request_models_1_1_search_result_context" ]
];